### ISSUE TITLE
Smarter axis label -- allow string manipulate function in `labs` or `theme`

### ISSUE THREAD

**Issue by albert-ying** [tidyverse/ggplot2#4648] opened 2021-10-20 20:44 UTC
The current default behavior of ggplot2 is to use the column name as the axis label. This is usually bad as we tend to use lower-case character and '_' in the column name.

## Example

```
library(tidyverse)
tb = iris |>
  janitor::clean_names() |>
  as_tibble()

tb
```
```
# A tibble: 150 × 5
   sepal_length sepal_width petal_length petal_width species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1          5.1         3.5          1.4         0.2 setosa
 2          4.9         3            1.4         0.2 setosa
 3          4.7         3.2          1.3         0.2 setosa
 4          4.6         3.1          1.5         0.2 setosa
 5          5           3.6          1.4         0.2 setosa
 6          5.4         3.9          1.7         0.4 setosa
 7          4.6         3.4          1.4         0.3 setosa
 8          5           3.4          1.5         0.2 setosa
 9          4.4         2.9          1.4         0.2 setosa
10          4.9         3.1          1.5         0.1 setosa
# … with 140 more rows
```
### Default plot
```
p = tb |>
  ggplot(aes(sepal_length, sepal_width)) +
  geom_point() +
  theme_bw()

p
```
![image](https://user-images.githubusercontent.com/59846322/138168465-802810f4-fc6d-4431-8e62-02c53bd995e1.png)

### With better labeling
```
smart_label = function(lab) {
  str_replace(lab, "_", " ") |> str_to_title()
}

p$labels = p$labels |>
  map(smart_label)

p
```
![image](https://user-images.githubusercontent.com/59846322/138168958-11df9fcc-754d-4013-a00b-85af63166c72.png)

The second one looks more "normal". And even if it shouldn't be the default behavior, there should be an easy argument in `theme` or `labs` to toggle this behavior. Or allow user to supply the function to manipulate the labels.

**Comment by clauswilke** [comment] 2021-10-20 20:48
I guess the request here is to make the `name` argument in scales accept a function as input, just like the `labels` argument does.

**Comment by hadley** [comment] 2022-03-14 21:24
Closing as duplicate of #4313

**Closed by hadley** 2022-03-14 21:24 UTC
Labels: feature, guides :straight_ruler:
