### ISSUE TITLE
coord_trans() causes geom_hline() to draw incomplete lines

### ISSUE THREAD

**Issue by mafed** [tidyverse/ggplot2#2812] opened 2018-08-08 15:14 UTC
`geom_hline` draws incomplete lines when used together with `coord_trans`, regardless of their respective order of addition.

```r
mydf <- data.frame(x = 0L:20,
                   y = -10:10)
ggplot(data = mydf, aes(x, y)) + 
  geom_point() + 
  coord_trans(x = "log1p") +
  geom_hline(yintercept = c(-10, 10))
```
![image](https://user-images.githubusercontent.com/2510765/43846354-6e65e25e-9b2e-11e8-93a8-f30af8cd43bb.png)

**Comment by clauswilke** [comment] 2018-08-08 16:19
Duplicate of #2149?

**Closed** 2018-08-10 19:06 UTC
