### ISSUE TITLE
geom_area with negative y not working in ggplot2 3.2.0

### ISSUE THREAD

**Issue by vadimus202** [tidyverse/ggplot2#3390] opened 2019-07-03 18:01 UTC
In `ggplot2 3.1.1` the area under the curve handles negative values
```r
library(ggplot2)

set.seed(115)

ggplot(
    data.frame(
        x = 1:100,
        y = cumsum(rnorm(n = 100, mean = 0, sd = 3))
    ),
    aes(x, y)) +
    geom_area(fill = "pink", alpha = 0.5) +
    geom_path()
```
![image](https://user-images.githubusercontent.com/7230548/60614391-c957a700-9d9a-11e9-8292-02560322ed14.png)

In `ggplot2 3.2.0` something goes wrong:
```r
library(ggplot2)

set.seed(115)

ggplot(
    data.frame(
        x = 1:100,
        y = cumsum(rnorm(n = 100, mean = 0, sd = 3))
    ),
    aes(x, y)) +
    geom_area(fill = "pink", alpha = 0.5) +
    geom_path()
```
![image](https://user-images.githubusercontent.com/7230548/60614103-45052400-9d9a-11e9-923f-b9629765e241.png)

**Comment by yutannihilation** [comment] 2019-07-04 03:13
A simpler version of code (Sorry, I can't render the reprex right now...). Not sure what's happening here, but It seems something went wrong...

``` r
library(ggplot2)

d <- data.frame(
  x = 1:6,
  y = c(1, 2, 2, 1, 0, -1)
)

ggplot(d, aes(x, y)) +
  geom_area(fill = "pink", alpha = 0.5) +
  geom_point()

ggplot(d, aes(x, y - 1)) +
  geom_area(fill = "pink", alpha = 0.5) +
  geom_point()
```

**Comment by clauswilke** [comment] 2019-07-04 04:24
Rendered reprex below.

@thomasp85 Is this somehow related to the rewritten polygon rendering code? We may have to consider a hotfix release, since this is a serious regression.

``` r
library(ggplot2)

d <- data.frame(
  x = 1:6,
  y = c(1, 2, 2, 1, 0, -1)
)

ggplot(d, aes(x, y)) +
  geom_area(fill = "pink", alpha = 0.5) +
  geom_point()
```

![](https://i.imgur.com/pXtEiIJ.png)

``` r

ggplot(d, aes(x, y - 1)) +
  geom_area(fill = "pink", alpha = 0.5) +
  geom_point()
```

![](https://i.imgur.com/MTLvYIb.png)

<sup>Created on 2019-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment] 2019-07-04 06:56
I’ll look into it.

**Comment by thomasp85** [comment] 2019-07-04 07:23
This is due to `GeomArea`/`GeomRibbon` now sorting their data in `setup_data` instead of in `draw_panel`. `PositionStack` changes the ordering of the data and that is no longer resolved as it comes after `setup_data`.

There are two ways around this. 

1) Make sure PositionStack doesn't change the ordering of data
2) Make a secondary sort in `draw_panel()`

I generally prefer 1) as it is how I think positions should behave (i.e. not fiddle with data ordering), but it may have unforeseen consequences 🤷‍♂️

I agree this should be fixed in a hot fix (and we really should have some tests to catch this) cc @hadley

**Comment by hadley** [comment] 2019-07-04 11:51
1) sounds reasonable. And it shouldn't be too bad to do a patch release for this issue. Do we want to wait a week in case any other problems come in?

**Comment by thomasp85** [comment] 2019-07-04 11:52
Let's wait a week before we start release process

**Comment by karawoo** [comment] 2019-07-05 23:29
If I recall correctly, the ordering in PositionStack exists to fix my first ever bug report (#1552) 🙂. So it is there for a reason, but it's possible that reason has been obviated by other changes since. I can try to look into it this weekend.

**Comment by karawoo** [comment] 2019-07-17 17:29
I've opened a PR that will address this, but in the meantime `geom_ribbon()` still works:

``` r
library(ggplot2)

set.seed(115)

ggplot(
  data.frame(
    x = 1:100,
    y = cumsum(rnorm(n = 100, mean = 0, sd = 3))
  ),
  aes(x, y)) +
  geom_ribbon(aes(ymax = y, ymin = 0), fill = "pink", alpha = 0.5) +
  geom_path()
```

![](https://i.imgur.com/t8N1HAb.png)

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment] 2019-07-23 15:12
@thomasp85 @hadley 
> Let's wait a week before we start release process

Some weeks have passed. Do we start the process? While this issue should be hot-fixed, this might not be as serious as we thought at first in terms of the number of users affected, considering the fact there's no other issues filed than this one. So, if you are very busy (sorry, I don't think I can review #3401...), I think it's okay not to hurry so much.

But, I'm a bit worrying about that the CRAN check is all red probably due to #3394 (, which seems already fixed by @paleolimbot). Do you get any serious warnings about this from CRAN people?

https://cran.rstudio.com/web/checks/check_results_ggplot2.html

**Comment by thomasp85** [comment] 2019-07-23 15:25
I’m currently on vacation (this week and next).  I’ll begin release once I’m back

**Comment by yutannihilation** [comment] 2019-07-23 15:30
OK. Have a nice vacation!

**Closed** 2019-08-12 13:41 UTC
Labels: bug, layers :chart_with_upwards_trend:
