### ISSUE TITLE
geom_sf plotting points doesn't allow size<1

### ISSUE THREAD

**Issue by woodwards** [tidyverse/ggplot2#2313] opened 2017-10-30 17:39 UTC
I am plotting points with geom_sf. Using manual size, I found that sizes < 1 appear as if they were size = 1.

```r
# insert reprex here
library(sf)
library(maps)
library(ggplot2)

#points
data(meuse,package="sp")
meuse_sf <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992, agr = "constant")

summary(meuse_sf)

meuse_sf %>% ggplot() + geom_sf(size=0.01)
```

**Comment by hadley** [comment] 2017-10-30 17:57
Duplicate of #2275

**Closed by hadley** 2017-10-30 17:57 UTC
