### ISSUE TITLE
Feature request: scale_*_reverse() to work on all classes

### ISSUE THREAD

**Issue by jzadra** [tidyverse/ggplot2#3987] opened 2020-05-05 16:04 UTC
scale_*_reverse() currently only works on numeric.  It would be great if it would work on factors and character classes as well, as currently several extra bits of code have to be used to accomplish this, and that code also doesn't work with rlang references.

**Comment by smouksassi** [comment] 2020-05-06 07:59
this is a duplicate of https://github.com/tidyverse/ggplot2/issues/3115 and it has been fixed

**Comment by yutannihilation** [comment] 2020-05-13 13:15
Thanks, I too think this is already fixed.

@jzadra 
Could you provide a minimal reprex?

**Closed** 2020-08-31 08:52 UTC
