### ISSUE TITLE
Using coord_cartesian causing errors for the width of geom_bar

### ISSUE THREAD

**Issue by GBuchanon** [tidyverse/ggplot2#3155] opened 2019-02-20 00:46 UTC
The use of coord_cartesian causes the bin width of a bar to be miscalculated when the source data is contained in one bin.

The expected result is that coord_cartesian has no effect on the plot other than zooming.

```r
library(tidyverse)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date

dframe <- data.frame(
    month = c(rep(as.Date(seq(ymd('2009-02-01'), ymd('2009-10-01'), by = "1 month"))),
              rep(as.Date(seq(ymd('2008-08-01'), ymd('2009-4-01'), by = "1 month")))),
    val = rep(seq(1:9),2),
    cat = c(rep("a",9), rep("b", 9))
)

# first an example of the expected correct 
plot(ggplot(data=dframe %>% group_by(year = as.Date(cut.Date(month, "year")))) +
            aes(year, val) +
            stat_summary(fun.y = mean, na.rm = TRUE, geom = "bar") +
            coord_cartesian(xlim=c(ymd('2007-06-01'), ymd('2009-06-01'))) +
            facet_grid(cat~.)
)
```

![](https://i.imgur.com/llVx06R.png)

``` r

# this shows that if the date range does not extend over one year and coord_cartesian() is used
#   the plot produces a skinny width for the bar
plot(ggplot(data=dframe %>% filter(cat=="a") %>%
            group_by(year = as.Date(cut.Date(month, "year")))) +
            aes(year, val) +
            stat_summary(fun.y = mean, na.rm = TRUE, geom = "bar") +
            coord_cartesian(xlim=c(ymd('2007-06-01'), ymd('2009-06-01'))) 
)
```

![](https://i.imgur.com/YYkgHgl.png)

``` r

# plotting without the coord_cartesian() restriciton yields the correct bar width
plot(ggplot(data=dframe %>% filter(cat=="a") %>%
            group_by(year = as.Date(cut.Date(month, "year")))) +
            aes(year, val) +
            stat_summary(fun.y = mean, na.rm = TRUE, geom = "bar") 
)
```

![](https://i.imgur.com/rQShCb1.png)

<sup>Created on 2019-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>```

**Comment by karawoo** [comment] 2019-02-20 05:33
I believe this is the same issue as #2775

**Comment by yutannihilation** [comment] 2019-02-21 05:52
It seems so (about `resolution()`?). A simpler version of reprex:

``` r
library(ggplot2)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date

d <- data.frame(x = c(ymd("20080101"), ymd("20090101")), y = 1:2)

ggplot(d) +
  geom_col(aes(x, y)) +
  coord_cartesian(xlim = c(ymd("2007-06-01"), ymd("2009-06-01")))
```

![](https://i.imgur.com/36MTYyB.png)

``` r

ggplot(d[1,]) +
  geom_col(aes(x, y)) +
  coord_cartesian(xlim = c(ymd("2007-06-01"), ymd("2009-06-01")))
```

![](https://i.imgur.com/KMdIf1A.png)

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by yutannihilation** [comment] 2019-02-21 23:35
I'm closing this as a duplicate of #2775. Thanks, Kara.

**Closed by yutannihilation** 2019-02-21 23:35 UTC
