### ISSUE TITLE
Ignoring unknown aesthetics warning in geom_tile()

### ISSUE THREAD

**Issue by vadimus202** [tidyverse/ggplot2#2066] opened 2017-03-05 22:43 UTC
Unanticipated warning displayed below. The height and width aesthetics are definitely used and not ignored.
Thanks!

``` r
library(ggplot2)

df <- data.frame(
    x = rep(c(2, 5, 7, 9, 12), 2),
    y = rep(c(1, 2), each = 5),
    z = factor(rep(1:5, each = 2)),
    w = rep(diff(c(0, 4, 6, 8, 10, 14)), 2)
)
ggplot(df, aes(x, y)) +
    geom_tile(aes(fill = z, width = w), colour = "grey50")
#> Warning: Ignoring unknown aesthetics: width
```

![](http://i.imgur.com/O3brHbV.png)

**Comment by mexindian** [comment] 2017-04-05 09:11
Me as well. I'm getting the warning, but the `width` is definitely NOT ignored:

```ggplot(OngoingDF, aes(IndNumBetter) ) + 
      geom_bar(aes(y=Perc,width=0.15,fill=BehindBy),stat = "identity")  + 
      scale_fill_gradient(limits = c(LowLVL,0),low="red", high="green") +
      geom_point(aes(y=OldPer),shape=6,size=5) +
      geom_text( y=1,aes(label = tex2),vjust=2,hjust = 0) +
      geom_bar(aes(y=100,width=0.5),alpha=0.25,stat = "identity") +
      geom_text( y=1,aes(label = tex),vjust=-1.5,hjust = 0) +
      geom_hline(yintercept = OngoingDF$Perc.time[1],alpha=0.33) +
      annotate("text", x = 0, y = OngoingDF$Perc.time[1] + 1.5,hjust=0, label = "Today",angle=90,alpha=0.33) +
      coord_flip() +  
      ylab("Percent of yearly target & Percent of year") +   xlab(" ") +
      ggtitle(paste("Ongoing Indicator accomplishment (",forYear,")",sep=""))+
      theme_minimal() + theme(axis.text.y = element_text(size=15,face="bold"),
                              axis.title.x = element_text(face="bold", size=15),
                              title=element_text(face="bold",size=20))
Warning: Ignoring unknown aesthetics: width
Warning: Ignoring unknown aesthetics: width
```
yields:
![image](https://cloud.githubusercontent.com/assets/8094091/24698296/080bdaa4-19e8-11e7-87f2-7f739b4f4373.png)

while:
```ggplot(OngoingDF, aes(IndNumBetter) ) + 
      geom_bar(aes(y=Perc,fill=BehindBy),stat = "identity")  + 
      scale_fill_gradient(limits = c(LowLVL,0),low="red", high="green") +
      geom_point(aes(y=OldPer),shape=6,size=5) +
      geom_text( y=1,aes(label = tex2),vjust=2,hjust = 0) +
      geom_bar(aes(y=100),alpha=0.25,stat = "identity") +
      geom_text( y=1,aes(label = tex),vjust=-1.5,hjust = 0) +
      geom_hline(yintercept = OngoingDF$Perc.time[1],alpha=0.33) +
      annotate("text", x = 0, y = OngoingDF$Perc.time[1] + 1.5,hjust=0, label = "Today",angle=90,alpha=0.33) +
      coord_flip() +  
      ylab("Percent of yearly target & Percent of year") +   xlab(" ") +
      ggtitle(paste("Ongoing Indicator accomplishment (",forYear,")",sep=""))+
      theme_minimal() + theme(axis.text.y = element_text(size=15,face="bold"),
                              axis.title.x = element_text(face="bold", size=15),
                              title=element_text(face="bold",size=20))```

yields:
![image](https://cloud.githubusercontent.com/assets/8094091/24698354/391fd8e8-19e8-11e7-8ced-642c96c0f971.png)

**Comment by npjc** [comment] 2017-04-30 15:44
👍 same here. 

My reprex and info:

``` r
library(ggplot2)
```

### from `geom_tile` examples:

``` r
df <- data.frame(x = rep(c(2, 5, 7, 9, 12), 2), y = rep(c(1, 2), each = 5), 
  z = factor(rep(1:5, each = 2)), w = rep(diff(c(0, 4, 6, 8, 10, 14)), 2))
ggplot(df, aes(x, y)) + geom_tile(aes(x = x, y = y, fill = z, width = w), colour = "grey50", 
  width = 3)
#> Warning: Ignoring unknown aesthetics: width
```

![](http://i.imgur.com/Rpdniw0.png)

### Session Info

``` r
sessioninfo::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.4.0 (2017-04-21)
#>  os       macOS Sierra 10.12.4        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_CA.UTF-8                 
#>  tz       America/Chicago             
#>  date     2017-04-30                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       source                             
#>  backports     1.0.5      2017-01-18 CRAN (R 3.4.0)                     
#>  bitops        1.0-6      2013-08-17 CRAN (R 3.4.0)                     
#>  clisymbols    1.1.0      2017-01-27 cran (@1.1.0)                      
#>  colorspace    1.3-2      2016-12-14 CRAN (R 3.4.0)                     
#>  digest        0.6.12     2017-01-27 CRAN (R 3.4.0)                     
#>  evaluate      0.10       2016-10-11 CRAN (R 3.4.0)                     
#>  formatR       1.5        2017-04-25 CRAN (R 3.4.0)                     
#>  ggplot2     * 2.2.1      2016-12-30 CRAN (R 3.4.0)                     
#>  gtable        0.2.0      2016-02-26 CRAN (R 3.4.0)                     
#>  htmltools     0.3.5      2016-03-21 CRAN (R 3.4.0)                     
#>  knitr         1.15.1     2016-11-22 CRAN (R 3.4.0)                     
#>  labeling      0.3        2014-08-23 CRAN (R 3.4.0)                     
#>  lazyeval      0.2.0      2016-06-12 CRAN (R 3.4.0)                     
#>  magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                     
#>  munsell       0.4.3      2016-02-13 CRAN (R 3.4.0)                     
#>  plyr          1.8.4      2016-06-08 CRAN (R 3.4.0)                     
#>  Rcpp          0.12.10    2017-03-19 CRAN (R 3.4.0)                     
#>  RCurl         1.95-4.8   2016-03-01 CRAN (R 3.4.0)                     
#>  rmarkdown     1.5        2017-04-26 CRAN (R 3.4.0)                     
#>  rprojroot     1.2        2017-01-16 CRAN (R 3.4.0)                     
#>  scales        0.4.1      2016-11-09 CRAN (R 3.4.0)                     
#>  sessioninfo   0.0.0.9000 2017-04-26 Github (r-pkgs/sessioninfo@0a5b58f)
#>  stringi       1.1.5      2017-04-07 CRAN (R 3.4.0)                     
#>  stringr       1.2.0      2017-02-18 CRAN (R 3.4.0)                     
#>  tibble        1.3.0      2017-04-01 CRAN (R 3.4.0)                     
#>  withr         1.0.2      2016-06-20 CRAN (R 3.4.0)                     
#>  XML           3.98-1.6   2017-03-30 CRAN (R 3.4.0)                     
#>  yaml          2.1.14     2016-11-12 CRAN (R 3.4.0)
```

**Comment by hadley** [comment] 2017-06-01 12:44
Duplicate of #1904

**Closed by hadley** 2017-06-01 12:44 UTC
