### ISSUE TITLE
Partal matching 

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#5654] opened 2024-01-20 16:59 UTC
I'm preparing to send ggnewscale to CRAN and part of my test is warning against partial matching. This caught an issue that bubbled up from ggplot2 and probably gtable. 

I'm preparing to send ggnewscale to CRAN and part of my test is warning against partial matching. This caught an issue that bubbled up from ggplot2 and probably gtable. 

``` r
library(ggplot2)
options(warnPartialMatchDollar = TRUE)
options(warn = 2) 

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = factor(year)))
#> Error in vp$just: (converted from warning) partial match of 'just' to 'justification'
```

traceback (don't know how to print it automatically in the reprex)

```
  (converted from warning) partial match of 'just' to 'justification'
20.
doWithOneRestart(return(expr), restart)
19.
withOneRestart(expr, restarts[[1L]])
18.
withRestarts({
.Internal(.signalCondition(simpleWarning(msg, call), msg,
call))
.Internal(.dfltWarn(msg, call)) ...
17.
.signalSimpleWarning("partial match of 'just' to 'justification'",
base::quote(vp$just))
16.
valid.just(just)
15.
vpObject(x, y, width, height, valid.just(just), gp, clip, mask,
xscale, yscale, angle, layout, layout.pos.row, layout.pos.col,
name)
14.
valid.viewport(x, y, width, height, just, gp, clip, mask, xscale,
yscale, angle, layout, layout.pos.row, layout.pos.col, name)
13.
viewport(name = name, x = vp$x, y = vp$y, width = vp$width, height = vp$height,
just = vp$just, gp = vp$gp, xscale = vp$xscale, yscale = vp$yscale,
angle = vp$angle, clip = vp$clip)
12.
gtable(widths = width, heights = heights, name = name, vp = vp,
rownames = names(grobs))
11.
gtable_col(name = "guides", grobs = grobs, width = max(widths),
heights = heights, vp = vp) at guides-.R#680
10.
package_box(...) at ggproto.R#180
9.
(structure(function (...)
package_box(...), class = "ggproto_method"))(grobs = dots[[1L]][[4L]],
position = dots[[2L]][[4L]], theme = structure(list(line = structure(list(
colour = "black", linewidth = 0.5, linetype = 1, lineend = "butt", ...
8.
mapply(FUN = f, ..., SIMPLIFY = FALSE)
7.
Map(grobs = grobs, position = names(grobs), self$package_box,
MoreArgs = list(theme = theme)) at guides-.R#517
6.
assemble(..., self = self) at ggproto.R#180
5.
plot$guides$assemble(theme) at plot-build.R#185
4.
ggplot_gtable.ggplot_built(data) at plot-build.R#170
3.
ggplot_gtable(data) at plot.R#206
2.
print.ggplot(x)
1.
(function (x, ...)
UseMethod("print"))(x)
```
<sup>Created on 2024-01-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment] 2024-01-20 17:32
Yeah I noticed this too in your tests. I had a hard time figuring out what the root cause of this was, and still haven't.

**Comment by teunbrand** [comment] 2024-01-20 17:52
I'm now pretty much convinced that it is a gtable thing. It tries to extract the `vp$just` element, but its true name is `vp$justification`. Somewhere in the `viewport()` constructor, the `just` argument is set as a `justification` element in a list.

``` r
library(gtable)
library(grid)
options(warnPartialMatchDollar = TRUE)
options(warn = 2) 

gtable(
  widths = unit(1, "cm"),
  heights = unit(1, "cm"),
  vp = viewport()
)
#> Error in vp$just: (converted from warning) partial match of 'just' to 'justification'
```

<sup>Created on 2024-01-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment] 2024-01-21 06:33
Maybe this line?

https://github.com/r-lib/gtable/blob/c410a54ed331cb8480f39f2a7d32cce115c19f1d/R/gtable.R#L120

Confirmed a `viewport`'s element is `justification`, not `just` while the arg name is `just`.

https://github.com/wch/r-source/blob/90d5c6e24c0867625ac3425d1b2d95cc11e3964b/src/library/grid/R/viewport.R#L37

**Comment by teunbrand** [comment] 2024-01-24 12:11
Thanks for the confirmation! As this is a gtable issue, I've put in a PR at gtable, see https://github.com/r-lib/gtable/pull/94. Should we close this issue here?

**Comment by yutannihilation** [comment] 2024-01-24 12:16
Thanks for the PR! As there's nothing we can do on ggplot2's side, I agree we can close this issue.

**Closed** 2024-01-24 12:54 UTC
Labels: bug
