### ISSUE TITLE
Could `geom_abline` and `geom_qq_line` always stop at the limits, regardless of other settings? 

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#6081] opened 2024-09-06 00:13 UTC
Could `geom_abline` and `geom_qq_line` always stop at the limits, regardless of other settings? 

So kind of act in the same way that `geom_hline`/`geom_vline` behave. 

``` r
library(tidyverse)
library(palmerpenguins)

penguins |> 
  ggplot() +
  coord_cartesian(clip = "off") +
  scale_x_continuous(limits = c(-2, 2), oob = scales::oob_keep, expand = c(0, 0)) +
  scale_y_continuous(limits = c(2000, 6500), oob = scales::oob_keep, expand = c(0, 0)) +
  geom_qq(aes(sample = body_mass_g)) +
  geom_vline(xintercept = 1.5) + #good 
  geom_hline(yintercept = 3000) + #good
  geom_abline(intercept = 3000, slope = 250, colour = "blue") +
  geom_abline(intercept = 3000, slope = 1000, colour = "green") +
  geom_qq_line(aes(sample = body_mass_g), colour = "red") +
  theme(plot.margin = margin(r = 100))
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq()`).
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq_line()`).
```

![](https://i.imgur.com/TjCPOYk.png)

<sup>Created on 2024-09-06 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by joranE** [comment] 2024-09-06 00:33
I think the behavior of `geom_qq_line` & `geom_qq` should be the same when `coord_cartesian(clip = "off")`, not different. And I think it would be confusing if `geom_qq` clipped points to the plotting area even when you've specified `coord_cartesian(clip = "off")`, so I think that's a bad idea.

I'm less certain what `geom_abline` should do.

**Comment by davidhodge931** [comment] 2024-09-06 04:45
My logic is that you always want ablines and qq_lines to fall within the plot, but you .want flexibility in how to apply the coord_cartesian clip for the other geoms. 

The clipping within coord_cartesian relates to _all_ layers. So it can be helpful if you have the freedom to clip layers without affecting qq_lines and ablines (and hlines/vlines).

For example, you might want a scatter plot with set limits and a point might land on the outer limit. If you use "clip = off", this is nice because it keeps these points on the limits whole.

But then if you add a abline/qq_line, you are forced to change something, because it will exceed the boundaries of the plot

**Comment by clauswilke** [comment] 2024-09-06 04:56
qq lines span the data. I think it's Ok that the lines extend beyond the plot panel if you force data to fall outside of it as well. (Btw., this seems like a very contrived example to me. Who would do this outside of a bug report? Can you provide an actual example where this is a problem?)

ablines should probably be clipped to the plot panel, just like hlines and vlines.

Btw., you can force qq lines to be clipped to the panel by setting `fullrange = TRUE`. I know it's counterintuitive but it makes sense if you think about how that option is implemented.

``` r
library(tidyverse)
library(palmerpenguins)

penguins |> 
  ggplot() +
  coord_cartesian(clip = "off") +
  scale_x_continuous(limits = c(-2, 2), oob = scales::oob_keep, expand = c(0, 0)) +
  scale_y_continuous(limits = c(2000, 6500), oob = scales::oob_keep, expand = c(0, 0)) +
  geom_qq(aes(sample = body_mass_g)) +
  geom_qq_line(aes(sample = body_mass_g), colour = "red", fullrange = TRUE) +
  theme(plot.margin = margin(r = 100))
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq()`).
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq_line()`).
```

![](https://i.imgur.com/UZv1aDW.png)

<sup>Created on 2024-09-05 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment] 2024-09-06 08:33
Interesting, re `fullrange = TRUE` - agree the naming seems a bit unintuitive. 

Maybe a better example/use-case.. A common thing to do is to set the limits of the plot to get rid of part of a qq_line (or abline). However, users will have to understand how the oob argument works for them to be able to actually achieve this. The oob concept and argument is not widely known/understood - and this could cause confusion. It'd be nicer if it worked in this case without having to know about this.

In essence, I feel qq_line and abline are just the same as vline/hline in that you always want it only in the panel.

``` r
library(tidyverse)
library(palmerpenguins)

penguins |> 
    ggplot(aes(sample = body_mass_g)) +
    geom_qq() +
    geom_qq_line(colour = "red") 
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq()`).
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq_line()`).
```

![](https://i.imgur.com/1GJlblv.png)

``` r
  
penguins |> 
  ggplot(aes(sample = body_mass_g)) +
  geom_qq() +
  geom_qq_line(colour = "red") +
  scale_y_continuous(limits = c(2000, 7000))
#> Warning: Removed 2 rows containing non-finite outside the scale range (`stat_qq()`).
#> Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq_line()`).
#> Warning: Removed 1 row containing missing values or values outside the scale range
#> (`geom_path()`).
#> `geom_path()`: Each group consists of only one observation.
#> ℹ Do you need to adjust the group aesthetic?
```

![](https://i.imgur.com/8qlzyGE.png)

``` r

penguins |> 
  ggplot(aes(sample = body_mass_g)) +
  geom_qq() +
  geom_qq_line(colour = "red") +
  scale_y_continuous(limits = c(2000, 7000), oob = scales::oob_keep)
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq()`).
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_qq_line()`).
```

![](https://i.imgur.com/846DUr2.png)

<sup>Created on 2024-09-06 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment] 2024-09-06 15:35
@teunbrand I think the point here is that `geom_abline()` clips on the right and the left but not on the top and the bottom.

@davidhodge931 I feel we're discussing two entirely different things here. Could you close this issue and open two new ones, one for `geom_abline()` and one for `geom_qq_line()`? In particular, `geom_qq_line()` is inherently linked to the data (hence arguments such as `fullrange`) whereas `geom_abline()` just draws a line.

**Comment by clauswilke** [comment] 2024-09-06 15:47
@davidhodge931 Looking over your last set of examples, do I understand that here the problem is the line disappears entirely? If that's the issue then I agree this is a problem and we should discuss strategies to avoid it. But again, as I said in my other comment, entirely different from the `geom_abline()` issue.

**Closed** 2024-09-06 18:58 UTC
