### ISSUE TITLE
legend gets misaligned when title is longer

### ISSUE THREAD

**Issue by ahcyip** [tidyverse/ggplot2#4587] opened 2021-08-17 19:57 UTC
Legend alignment/justification gets overridden when the legend title is longer than a certain amount.

``` r
knitr::opts_chunk$set(fig.width = 10, fig.height = 4, dpi = 400, warning = FALSE)

library(palmerpenguins)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
# library(patchwork)

p0 <- palmerpenguins::penguins %>%
  ggplot() +
  geom_point(aes(x = bill_depth_mm, y = bill_length_mm, col = body_mass_g)) +
  scale_color_viridis_c(option = "C", direction = -1) +
  theme(legend.position = "bottom", legend.justification = "center") +
  guides(color = guide_colourbar(title.position = "top", direction = "horizontal"))

(p1 <- p0 +
  labs(color = "Short title"))
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/MsQay3G.png)

``` r
(p2 <- p0 +
  labs(color = "Long title that causes legend to move to the left\neven though legend justification is center"))
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/VlAlS84.png)

``` r
(p3 <- p0 +
  labs(color = "Even longer title with title.hjust = 0.5 that causes legend to move to the left\neven though legend justification is center") +
  guides(color = guide_colourbar(title.position = "top", direction = "horizontal", title.hjust = 0.5)))
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/9gb0zYj.png)

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.4 (2021-02-15)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Denver              
#>  date     2021-08-17                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package        * version date       lib source           
#>  assertthat       0.2.1   2019-03-21 [1] CRAN (R 4.0.3)   
#>  backports        1.2.1   2020-12-09 [1] CRAN (R 4.0.3)   
#>  cli              2.3.0   2021-01-31 [1] CRAN (R 4.0.3)   
#>  colorspace       2.0-0   2020-11-11 [1] CRAN (R 4.0.3)   
#>  crayon           1.4.1   2021-02-08 [1] CRAN (R 4.0.4)   
#>  curl             4.3     2019-12-02 [1] CRAN (R 4.0.3)   
#>  DBI              1.1.1   2021-01-15 [1] CRAN (R 4.0.3)   
#>  digest           0.6.27  2020-10-24 [1] CRAN (R 4.0.3)   
#>  dplyr          * 1.0.5   2021-03-05 [1] standard (@1.0.5)
#>  ellipsis         0.3.1   2020-05-15 [1] CRAN (R 4.0.3)   
#>  evaluate         0.14    2019-05-28 [1] CRAN (R 4.0.3)   
#>  farver           2.0.3   2020-01-16 [1] CRAN (R 4.0.3)   
#>  fs               1.5.0   2020-07-31 [1] CRAN (R 4.0.3)   
#>  generics         0.1.0   2020-10-31 [1] CRAN (R 4.0.3)   
#>  ggplot2        * 3.3.3   2020-12-30 [1] CRAN (R 4.0.3)   
#>  glue             1.4.2   2020-08-27 [1] CRAN (R 4.0.3)   
#>  gtable           0.3.0   2019-03-25 [1] CRAN (R 4.0.3)   
#>  highr            0.8     2019-03-20 [1] CRAN (R 4.0.3)   
#>  htmltools        0.5.1.1 2021-01-22 [1] CRAN (R 4.0.3)   
#>  httr             1.4.2   2020-07-20 [1] CRAN (R 4.0.3)   
#>  knitr            1.31    2021-01-27 [1] CRAN (R 4.0.3)   
#>  labeling         0.4.2   2020-10-20 [1] CRAN (R 4.0.3)   
#>  lifecycle        1.0.0   2021-02-15 [1] CRAN (R 4.0.4)   
#>  magrittr         2.0.1   2020-11-17 [1] CRAN (R 4.0.3)   
#>  mime             0.9     2020-02-04 [1] CRAN (R 4.0.3)   
#>  munsell          0.5.0   2018-06-12 [1] CRAN (R 4.0.3)   
#>  palmerpenguins * 0.1.0   2020-07-23 [1] CRAN (R 4.0.3)   
#>  pillar           1.4.7   2020-11-20 [1] CRAN (R 4.0.3)   
#>  pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.0.3)   
#>  purrr            0.3.4   2020-04-17 [1] CRAN (R 4.0.3)   
#>  R.cache          0.15.0  2021-04-30 [1] CRAN (R 4.0.5)   
#>  R.methodsS3      1.8.1   2020-08-26 [1] CRAN (R 4.0.3)   
#>  R.oo             1.24.0  2020-08-26 [1] CRAN (R 4.0.3)   
#>  R.utils          2.10.1  2020-08-26 [1] CRAN (R 4.0.5)   
#>  R6               2.5.0   2020-10-28 [1] CRAN (R 4.0.3)   
#>  rematch2         2.1.2   2020-05-01 [1] CRAN (R 4.0.3)   
#>  reprex           1.0.0   2021-01-27 [1] CRAN (R 4.0.3)   
#>  rlang            0.4.10  2020-12-30 [1] CRAN (R 4.0.3)   
#>  rmarkdown        2.6     2020-12-14 [1] CRAN (R 4.0.3)   
#>  scales           1.1.1   2020-05-11 [1] CRAN (R 4.0.3)   
#>  sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 4.0.3)   
#>  stringi          1.5.3   2020-09-09 [1] CRAN (R 4.0.3)   
#>  stringr          1.4.0   2019-02-10 [1] CRAN (R 4.0.3)   
#>  styler           1.5.1   2021-07-13 [1] CRAN (R 4.0.5)   
#>  tibble           3.0.6   2021-01-29 [1] CRAN (R 4.0.3)   
#>  tidyselect       1.1.0   2020-05-11 [1] CRAN (R 4.0.3)   
#>  vctrs            0.3.6   2020-12-17 [1] CRAN (R 4.0.3)   
#>  viridisLite      0.3.0   2018-02-01 [1] CRAN (R 4.0.3)   
#>  withr            2.4.1   2021-01-26 [1] CRAN (R 4.0.3)   
#>  xfun             0.20    2021-01-06 [1] CRAN (R 4.0.3)   
#>  xml2             1.3.2   2020-04-23 [1] CRAN (R 4.0.3)   
#>  yaml             2.2.1   2020-02-01 [1] CRAN (R 4.0.3)   
#> 
#> [1] C:/Users/ayip/Documents/R/R-4.0.4/library
```

</details>

**Comment by karawoo** [comment] 2021-08-17 20:38
Closing as a duplicate of #1903

**Closed by karawoo** 2021-08-17 20:38 UTC
