### ISSUE TITLE
Unify the type required by geoms/layers when POSIXct values used

### ISSUE THREAD

**Issue by jwhendy** [tidyverse/ggplot2#2016] opened 2017-01-29 20:44 UTC
I stumbled into a possible bug, or at least what I thought was odd behavior. Here's a reproducible example:

```
## create the data
dat <- data.frame(date = paste0(2016, "-0", 1:9, "-01"),
                  val = 1:9)
dat$date <- as.POSIXct(dat$date)

## a simple base plot which I'll add to
p <- ggplot(dat, aes(x = date, y = val)) + geom_point()

## I tried to add a vertical line at a date and figured that I needed
## to match the class of the x variable used in the base plot,
## but it fails, complaining about being POSIXct
p + geom_vline(xintercept = as.POSIXct("2016-05-01"))

## I found a stackoverflow post[1] that suggested using as.numeric(), which works
p + geom_vline(xintercept = as.numeric(as.POSIXct("2016-05-01")))

## I happened to *also* want to add some text, and given the success
## of the above line, I assumed all additions needed as.numeric(as.POSIXct())
## so this seemed logical but it fails
p + annotate("text", x = as.numeric(as.POSIXct("2016-05-01")),
             y = 6, label = "test")

## instead, it appears that annotate() wants POSIXct after all
p + annotate("text", x = as.POSIXct("2016-05-01"), y = 6,
             label = "test")
```

Is this a bug? It would seem nice if layers expected a unified class for the coordinate specifications, or at least this is what I expected. I don't think it matters too much what it is, per se, as long as `ggplot2` is clear about what it should be. In other words:

- regardless of the `aes(x = blah)` in the base layer, all additional coordinate specifications need to be in their `numeric` form; or:
- the definition of `aes(x = blah)` fundamentally changes how all subsequent layers should be defined and the coordinates need to be the same class as `x`

Does that make sense? Thanks for considering or clarifying my thinking if I'm not understanding what's going on in this example!

---

[1] http://stackoverflow.com/questions/5388832/how-to-get-a-vertical-geom-vline-to-an-x-axis-of-class-date

**Comment by hadley** [comment] 2017-02-13 13:53
The behaviour you are seeing is consistent, although it's not particularly obvious. There are two rules:

* Mapped aesthetics should be supplied in the data space
* Set aesthetics should be supplied in the aesthetic space 

`annotate()` automatically creates a data frame for you so you can specify values in the data space.

I think this is a "feature" (because it's consistent with how colour and other aesthetics work), and I suspect if I did fix it it would break a lot of existing code.

(This is a duplicate of #1780)

**Closed by hadley** 2017-02-13 13:53 UTC
