### ISSUE TITLE
Release ggplot2 3.1.0

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2890] opened 2018-09-12 21:28 UTC
Issues to resolve before release:

* [x] #2895 (brushing in shiny doesn't work for `coord_trans()`)

PRs to complete before release:

* [x] #2792
* [x] #2849 (needs #2881 first)
* [x] #2854
* [x] #2806
* [x] #2807
* [x] #2808
* [x] #2881
* [x] #2821 (fixes #2895, has been rewritten to not introduce breaking changes)

Prepare for release:

* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] `pkgdown::build_site()`
* [x] Tag release
* [x] Merge RC back to master branch
* [x] Bump dev version
* [x] Write blog post
* [x] Tweet
* [x] Add link to blog post in pkgdown news menu

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by josesho** [comment] 2018-09-24 15:58
Is #2788 going to be part of ggplot 3.0.1? If not, can I request that it be included? (Working on fixing mission-critical function, and this breaks it in a massive way.)

**Comment by clauswilke** [comment] 2018-09-24 16:39
@josesho If your code works with the current github master then it should work with ggplot2 3.0.1. If it doesn't work with the current github master then please file an issue with reprex.

**Comment by josesho** [comment] 2018-09-25 02:19
Thanks for the heads-up, the current master does work and fixes the issue. Hopefully y'all can ggplot2 3.0.1 out soon! Looking forward 💪🏻

**Comment by clauswilke** [comment] 2018-09-25 16:27
Here are the build logs from my `check_for_cran()` run:
https://builder.r-hub.io/status/ggplot2_3.0.0.9000.tar.gz-e0789aadf85149dea1cdf0e69ef0b65d
https://builder.r-hub.io/status/ggplot2_3.0.0.9000.tar.gz-a1b23d0e97de472f96fbacfcd8a15538

**Comment by batpigandme** [comment] 2018-09-25 16:43
Per @jennybc's suggestion in the OG thread: https://github.com/r-lib/usethis/issues/338#issuecomment-422081132, I think it _does_ make sense to do the pkgdown build _after_ CRAN approval

**Comment by clauswilke** [comment] 2018-09-25 16:52
@batpigandme Thanks, I've moved it down.

**Comment by clauswilke** [comment] 2018-09-25 17:08
@hadley Still getting rhub errors even with `_R_CHECK_FORCE_SUGGESTS_=false`:

```
* checking package dependencies ... ERROR
Package required but not available: 'viridisLite'
```

**Comment by yutannihilation** [comment] 2018-09-25 23:30
It seems dependency installation fails. I see errors around [line 509(https://builder.r-hub.io/status/ggplot2_3.0.0.9000.tar.gz-e0789aadf85149dea1cdf0e69ef0b65d#L503), though it's not clear which package is wrong.

```
Error in desc[1L, "Type"] : subscript out of bounds
Calls: ... force -> i.p -> .install.winbinary -> unpackPkgZip -> %in%
In addition: Warning messages:
1: In unzip(zipname, exdir = dest) :
write error in extracting from zip file
2: In unzip(zipname, exdir = dest) :
write error in extracting from zip file
Execution halted
```

**Comment by topepo** [comment] 2018-09-26 09:13
Done. I'll put in a PR in a bit

## Broken (15)

|package                                                            |version |error     |warning  |note     |
|:------------------------------------------------------------------|:-------|:---------|:--------|:--------|
|[ActisoftR](problems.md#actisoftr)                                 |0.0.1   |__+1__    |1 __+1__ |         |
|[AneuFinder](problems.md#aneufinder)                               |1.8.0   |-1 __+1__ |1 __+2__ |1        |
|[BloodCancerMultiOmics2017](problems.md#bloodcancermultiomics2017) |1.0.2   |-1        |__+2__   |1        |
|[dartR](problems.md#dartr)                                         |1.0.5   |          |1 __+1__ |1        |
|[GenomicDataCommons](problems.md#genomicdatacommons)               |1.4.3   |-1        |2 __+1__ |1        |
|[ggridges](problems.md#ggridges)                                   |0.5.0   |__+1__    |1 __+1__ |1        |
|[GOexpress](problems.md#goexpress)                                 |1.14.0  |          |1        |4 __+1__ |
|[MCbiclust](problems.md#mcbiclust)                                 |1.4.0   |__+1__    |1        |1        |
|[mglR](problems.md#mglr)                                           |0.1.0   |-1        |__+1__   |         |
|[RITAN](problems.md#ritan)                                         |1.4.2   |-1        |1 __+1__ |3        |
|[scDD](problems.md#scdd)                                           |1.4.0   |__+1__    |2        |2        |
|[seqsetvis](problems.md#seqsetvis)                                 |1.0.2   |__+2__    |1 __+1__ |         |
|[shadowtext](problems.md#shadowtext)                               |0.0.2   |__+1__    |1 __+1__ |         |
|[tricolore](problems.md#tricolore)                                 |1.2.0   |__+1__    |1        |2        |
|[tsbox](problems.md#tsbox)                                         |0.0.3   |__+1__    |1        |         |

**Comment by topepo** [comment] 2018-09-26 13:52
revdep db [here](https://www.dropbox.com/s/llilyu97detb5xv/data.sqlite?dl=0)

**Comment by clauswilke** [comment] 2018-09-26 14:20
15 packages are broken in revdeps. That's not too bad. I suspect most of them will be due to the aesthetic name standardization that we introduced. That's what's causing the problems in my ggridges package. I used an aesthetic `point_color` and it is now internally converted to `point_colour` and thus some parts of the code can't find it. I'll fix ggridges and see if I can write recommendations for best practice.

@hadley @batpigandme @thomasp85 @karawoo @dpseidel @yutannihilation If you have time to look at any of the other broken packages to see what the issues are that would be great.

**Comment by yutannihilation** [comment] 2018-09-26 14:37
ggmap's installation error seems due to #2741. But, as `.all_aesthetics` is an internal object, I believe ggmap's approach is not quite right and it's ggmap's responsibility to fix this.

```
Error in get(".all_aesthetics", envir = asNamespace("ggplot2")) : 
  object '.all_aesthetics' not found
```

**Comment by batpigandme** [comment] 2018-09-26 14:37
Spreadsheet so we can keep track of what's been done (à la ggplot2 3.0.0 release) https://docs.google.com/spreadsheets/d/1T0t3dsF_6TPqa-dEztPiM51h-F9FhUWzVIsVeb3sl5A/edit#gid=0

**Comment by batpigandme** [comment] 2018-09-26 14:41
Shoot, if you don't have an rstudio email, shoot me an email from wherever to _my_ rstudio email, and I can add editing powers for you

**Comment by yutannihilation** [comment] 2018-09-26 15:15
Compared to @batpigandme's gist, @topepo's summary omits some packages. Here's the packages and reasons (seems ignorable except for ggtern):

* ggmap: installation error due to #2741 (and is already fixed)
* ggtern: installation error due to #2741 (needs to be informed to the maintener)
* derfinderPlot: `LaTeX errors when creating PDF version.`
* gifski: `LaTeX errors when creating PDF version.`
* RITAN: `R CMD check timed out`

@batpigandme 
Sorry, I couldn't find your email address... So, I just clicked "REQUEST EDIT ACCESS."

<details>

``` r
library(tidyverse)

res <- httr::GET("https://gist.githubusercontent.com/batpigandme/b59dca03bfb53b6e9a52332e306ff736/raw/bb05bfe98588d7a0194fd1fe59677d75efef3822/newlybroken_revdeps.md")

httr::content(res) %>% 
  stringr::str_split("\n") %>%
  unlist() %>%
  stringr::str_subset("^# ") %>%
  cat(sep = "\n")
#> # ActisoftR
#> # AneuFinder
#> # BloodCancerMultiOmics2017
#> # dartR
#> # derfinderPlot
#> # GenomicDataCommons
#> # ggmap
#> # ggridges
#> # ggtern
#> # gifski
#> # GOexpress
#> # MCbiclust
#> # mglR
#> # PTXQC
#> # RITAN
#> # scDD
#> # seqsetvis
#> # shadowtext
#> # tricolore
#> # tsbox
```

<sup>Created on 2018-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

</details>

**Comment by clauswilke** [comment] 2018-09-26 15:51
For ggtern, maybe the best way forward to maintain backwards compatibility with 3.0.0 is to reintroduce a variable called `.element_tree` and then assign the contents of that to `ggplot_global$element_tree`. In a later release, we can then remove `.element_tree`.

@nhamilton1980 Could you chime in?

**Comment by clauswilke** [comment] 2018-09-26 15:54
And maybe the same should be done with `.all_aesthetics`, though I really don't know why people access that.

**Comment by yutannihilation** [comment] 2018-09-26 16:05
For shadowtext, it's very strange... I'm sure the error occurs in this vignette: https://github.com/GuangchuangYu/shadowtext/blob/master/vignettes/shadowtext.Rmd and this acutally fails in and after `devtools::check()`,  but I cannot reproduce the error in the fresh session...

reprex here: https://gist.github.com/yutannihilation/4f33a397a4fbedb8bf00dca9c6a0d12a

**Comment by clauswilke** [comment] 2018-09-26 16:15
I suspect shadowtext is the same problem as ggridges. It uses an aesthetic called `bgcolor`.

**Comment by yutannihilation** [comment] 2018-09-26 16:27
Ah, you are right. The error is basically this (though I'm not sure what happens when `devtools::check()` yet...):

``` r
scales::alpha(NULL, c(NA, NA))
#> Error in col[, rep(1, length(alpha)), drop = FALSE]: subscript out of bounds
```

<sup>Created on 2018-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment] 2018-09-26 16:48
You are right. I got it; Since `GeomShadowText`'s `default_aes` is determined on built, if I install shadowtext via CRAN, `bg.color` stays as is. But, if it is built with ggplot2 v3.0.1, the `default_aes` no longer has `bg.color`.

**Comment by clauswilke** [comment] 2018-09-26 22:19
I've made a PR to fix ggtern: #2913 This should also fix BloodCancerMultiOmics2017 and tricolore.

I still need to investigate ggridges some more. Some things aren't working yet as expected. Once I've figured things out, I think it would be a good idea to write a blog post about best practices for non-standard aesthetics, so that we don't end up with a mess where everybody does something different. I'm glad that so far very few package developers seem to have tried to do this.

**Comment by clauswilke** [comment] 2018-09-27 04:45
I have fixed ggridges and it is on its way to CRAN. In the mean time, here are notes on porting non-standard aesthetics from 3.0.0 to 3.0.1  and best practices for using non-standard aesthetics going forward.

**Notes:** ggplot2 has always supported both British and American spelling for the word "colour". However, there was no systematic support for alternative types of spelling in the ggplot2 internals. With the release of ggplot2 3.0.1, ggplot2 always uses British spelling internally, and any aesthetics that contain the word "color" are automatically translated into strings containing "colour". (For example, `point_color` is converted to `point_colour`.) This may affect package developers who have invented non-standard aesthetics. This code may behave differently in version 3.0.1 versus earlier versions.

First, if you have written a geom that defines British and American versions of your aesthetic, you may get warnings about duplicated aesthetics in ggplot2 3.0.1. Going forward, you must only list the British spelling in `default_aes()`:
``` r
default_aes <- aes(point_colour = "red")
```
(If you list the American spelling, it is internally converted to British spelling.) For backwards compatibility with 3.0.0 or earlier, you can provide the American spelling as an optional aes:
``` r
optional_aes <- aes(point_color)
```

Second, in the drawing code of your geom, the data frame will now hold a column named using the British spelling. However, for backwards compatibility with 3.0.0, you can write something lilke:
``` r
grid.gpar(col = data$point_color %||% data$point_colour)
```
This will use the American spelling if provided and the British spelling otherwise. 
The operator `%||%` is defined in the rlang package. 

The same construct can be used to make your geom to use the standard `colour` aesthetic unless `point_colour` is provided:
``` r
grid.gpar(col = data$point_color %||% data$point_colour %||% data$colour)
```
For this to work, the default for `point_colour` needs to be `NULL`:
``` r
default_aes <- aes(point_colour = "NULL")
```

Finally, it is a good idea to define default scales for any new aesthetics you define. For ggplot2 3.0.1 or later, you only need to define a scale for `point_colour` with the setting `aesthetics = "point_colour"`, e.g.:
``` r
scale_point_colour_discrete <- function(...) scale_colour_hue(aesthetics = "point_colour", l = 40, ...)
```

For ggplot2 3.0.0 or earlier, you additionally need to define `scale_point_color_discrete` with `aesthetics = "point_color"`, e.g.:
``` r
scale_point_color_discrete <- function(...) scale_colour_hue(aesthetics = "point_color", l = 40, ...)
```

**Comment by yutannihilation** [comment] 2018-09-27 05:14
Thanks for the great note!

Minor fix. `aes(point_colour = "NULL")` should be `aes(point_colour = NULL)`, right?

**Comment by clauswilke** [comment] 2018-09-27 05:16
Yes, correct. I have corrected it.

**Comment by yutannihilation** [comment] 2018-09-27 05:18
Thanks.

**Comment by clauswilke** [comment] 2018-09-28 13:31
@topepo Could you run another revdep check? With my latest commit to master and updated ggridges on CRAN, maybe a third of the failures should be gone now.

@hadley Any thoughts about the 'argument "values" is missing, with no default' problem? Is that the package authors' issue to deal with?

**Comment by topepo** [comment] 2018-09-28 13:46
Sure. It'll probably take about 10-12h.

**Comment by hadley** [comment] 2018-09-28 13:54
I think we have to keep `scale_fill_manual()` backward compatible since its a minor release. I assume it's an easy fix (just providing a default value)

**Comment by clauswilke** [comment] 2018-09-28 14:07
@topepo Can you hold off on the run then? Let me make the fix @hadley suggests first.

**Comment by clauswilke** [comment] 2018-09-28 14:49
@hadley I made a PR for `scale_fill_manual()`.

One other topic: In hindsight, the internal handling of aesthetics names exceeds what one would want to do for a minor release. However, I'd very much rather not undo these changes, and the number of packages affected at this time is minute. Should we maybe call the release 3.1.0? Looking at NEWS.md, I see a fair number of new features, in particular around `geom_sf()`.

**Comment by hadley** [comment] 2018-09-28 15:34
Yeah, I think that's reasonable.

**Comment by clauswilke** [comment] 2018-09-28 17:09
@topepo We're ready for another revdep check. Thanks!

**Comment by GuangchuangYu** [comment] 2018-09-29 06:28
thanks @clauswilke for reminding the error of `shadowtext`. The issue will be removed on v = 0.0.3.

**Comment by clauswilke** [comment] 2018-09-29 15:19
Several of the new failures seem to involve ggmap. I have contacted the maintainer.

**Comment by clauswilke** [comment] 2018-09-29 16:50
Gist of the newly broken cases: https://gist.github.com/clauswilke/fb3ddad48f07e8fb02406657836fa8dd

@thomasp85 Any idea what's going on with lime?

**Comment by clauswilke** [comment] 2018-09-29 16:55
There's only a single package overlap (AneuFinder) between the previous failures and the new ones. All other previous failures have been fixed, but now we have 10 new ones. Does anybody have any ideas what the problems may be? It's not immediately obvious to me, other than what I said earlier, that some new problems seem to be ggmap related (FLightR, SensusR).

**Comment by hadley** [comment] 2018-09-29 20:35
I can't see any common source, although it looks like a few might be failures due to bad internet connections or bad random tests. It's worth checking carefully but it's not implausible that 11 failures  out of 2308 packages might be unrelated to ggplot2.  (IOTW I wouldn't let 10 failures block the release, as long as they get an email with a weeks notice)

**Comment by clauswilke** [comment] 2018-09-29 22:05
I looked some more into AneuFinder, since it's the one package that has stayed problematic between  the two revdep runs. I can confirm that it breaks with current master but not with 3.0.0, due to the changes in `scale_colour_manual()`. The guilty line is this one:
https://github.com/ataudt/aneufinder/blob/adb74437a5b4bf3dfc15490121e05d02fdb2ca08/R/plotting.R#L854
I'm wondering whether this code was implicitly depending on the broken behavior of the brittle closure.

I couldn't reproduce the error in lime, and for the ggmap related errors the problem seems to have to do with Google Maps API permissions. Not sure why it would be triggered by changes in the ggplot2 code base.

**Comment by yutannihilation** [comment] 2018-09-30 00:52
> for the ggmap related errors the problem seems to have to do with Google Maps API permissions. Not sure why it would be triggered by changes in the ggplot2 code base.

For the ggmap-related errors, I manually tried SensusR's example (`example("plot.LocationDatum")`) and got the same error both with the CRAN version and with the RC version of ggplot2. This error is because it uses the geocoding API, where the API key is now required since this June (c.f. https://github.com/dkahle/ggmap/issues/227), so I rather wonder why it worked in revdep check with the CRAN version, which seems impossible...

**Comment by yutannihilation** [comment] 2018-09-30 01:00
Actually, SensusR fails on CRAN with the same error, so I believe the error is ignorable.

https://cran.r-project.org/web/checks/check_results_SensusR.html

**Comment by yutannihilation** [comment] 2018-09-30 01:01
FLightR also fails on CRAN.

https://cran.r-project.org/web/checks/check_results_FLightR.html

**Comment by clauswilke** [comment] 2018-10-01 03:15
@hadley Once we're done with NEWS, I think I have to hand this over to you. Most of the next steps need to be taken by the maintainer. And it's also not clear to me what the right contents of `email.yml` would be.

**Comment by hadley** [comment] 2018-10-01 13:48
@clauswilke would you mind directly reporting to AneuFinder? Then I think we can skip the emails.

**Comment by clauswilke** [comment] 2018-10-01 14:06
Already sent an email to the maintainer yesterday, so that’s done.

**Comment by hadley** [comment] 2018-10-01 14:27
Ok, let's plan for a release on Oct 10?

**Comment by clauswilke** [comment] 2018-10-01 14:41
Works for me.

**Comment by hadley** [comment] 2018-10-01 22:05
`check_win_devel()` revealed one NOTE:

```
Non-standard file/directory found at top level:
  'GOVERNANCE.md'
```

Would someone mind putting together a PR that adds it to `.Rbuildignore`?

**Comment by hadley** [comment] 2018-10-23 21:13
Sorry for missing the release goal by two weeks. Before I re-kick off the process tonight/tomorrow, is there anything I should know?

**Comment by hadley** [comment] 2018-10-23 22:00
Thanks @clauswilke — I've merged those PRs and added a GITHUB_PAT so the travis failures should hopefully be fixed soon.

I notice one missing piece is that we don't have an updated `cran-comments.md`. Since I emailed all the maintainers on [Oct 1](https://github.com/tidyverse/ggplot2/pull/2923), I think I can just mention that, but in future we should probably be a bit more systematic. But just in case @topepo is going to re-run the revdeps, and I'll re-email everyone tomorrow.

**Comment by topepo** [comment] 2018-10-24 10:30
Can you add me to the project so I can start a new branch? 

I'll rerun today with a longer timeout (see below for prelim results and DB is at https://www.dropbox.com/s/llilyu97detb5xv/data.sqlite?dl=0). 

Spoiler alert:

We checked 2338 reverse dependencies (1971 from CRAN + 367 from BioConductor), comparing R CMD check results across CRAN and dev versions of this package.

 * We saw 3 new problems
 * We failed to check 53 packages

Issues with CRAN packages are summarised below.

### New problems
(This reports the first line of each new failure)

* FLightR
  checking examples ... ERROR

* lime
  checking tests ...

* postal
  checking tests ...

### Failed to check

* ALA4R                  (check timed out)
* av                     (failed to install)
* BACCT                  (failed to install)
* bamdit                 (failed to install)
* BayesRS                (failed to install)
* BMSC                   (failed to install)
* BNSP                   (failed to install)
* bsam                   (failed to install)
* BTSPAS                 (failed to install)
* choroplethr            (failed to install)
* classify               (failed to install)
* CoordinateCleaner      (failed to install)
* crmPack                (failed to install)
* DeLorean               (failed to install)
* dynr                   (failed to install)
* ewoc                   (failed to install)
* fdq                    (failed to install)
* Fgmutils               (failed to install)
* fieldRS                (failed to install)
* fingerPro              (failed to install)
* gastempt               (failed to install)
* GENEAsphere            (failed to install)
* geofacet               (failed to install)
* ggstatsplot            (check timed out)
* GmAMisc                (failed to install)
* HTSSIP                 (check timed out)
* ITGM                   (failed to install)
* jarbes                 (failed to install)
* JointAI                (failed to install)
* MetaStan               (failed to install)
* milr                   (check timed out)
* morse                  (failed to install)
* mwaved                 (failed to install)
* onemap                 (check timed out)
* pcaPA                  (failed to install)
* phase1RMD              (failed to install)
* phylosim               (check timed out)
* pmc                    (check timed out)
* ppcSpatial             (failed to install)
* RcmdrPlugin.FuzzyClust (check timed out)
* rpanel                 (failed to install)
* rstan                  (check timed out)
* rstanarm               (check timed out)
* rsvg                   (failed to install)
* seewave                (failed to install)
* SeqFeatR               (failed to install)
* sf                     (failed to install)
* simmr                  (failed to install)
* simulator              (check timed out)
* TeachingDemos          (check timed out)
* trialr                 (failed to install)
* walker                 (check timed out)
* zooaRchGUI             (failed to install)

**Comment by batpigandme** [comment] 2018-10-24 10:59
Added you, @topepo! ✔️

**Comment by hadley** [comment] 2018-10-24 12:40
@topepo don't worry about running with a longer time out — given that >2000 packages didn't have problems I think we can assume we didn't accidentally introduce any regressions.

@thomasp85 can you please look into the lime issue?

Would someone else mind looking into the postal and FLightR issues?

**Comment by clauswilke** [comment] 2018-10-24 14:48
@topepo Do we have the updated `problems.md` file?

@hadley The packages lime and FLightR had issues the last time and I looked into it then. For lime, it looked like a network error. The relevant code needs to download data to run, and it worked just fine on my machine with ggplot2 master. Not sure why it reliably breaks in revdepcheck, though. For FLightR, the problem was with the changes to the google map API, specifically the new authentication requirement they added. Again, not sure why it shows up as a new problem in revdepcheck, it should break for old ggplot2 also.

**Comment by topepo** [comment] 2018-10-24 14:56
> Do we have the updated `problems.md` file?

Just checked in.

**Comment by hadley** [comment] 2018-10-24 17:10
@clauswilke that's perfect - thanks!

**Comment by clauswilke** [comment] 2018-10-24 19:37
Ok, now that I have the new `problems.md` file, I looked more closely at lime and FLightR.

lime is the same version as in the previous revdepcheck, and the error looks similar as before (network error, fails to download a dataset it needs).

FLightR actually has released a new version that has addressed the ggmap issues. The problem there now also seems to be a network error (`Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : cannot open the connection`). The examples work fine for me.

**Comment by thomasp85** [comment] 2018-10-24 19:41
You can certainly ignore lime

**Comment by hadley** [comment] 2018-10-25 12:09
It was just accepted by the CRAN bot!  Thanks everyone for your hard work on this 🎉

**Comment by hadley** [comment] 2018-10-25 14:58
Any volunteers to work on the blog post? I'm currently attempting to get travis to build the docs automatically.

**Comment by clauswilke** [comment] 2018-10-25 15:37
Is there some convenient mechanism to work on it collaboratively? At a minimum I could provide some materials related to the parts I worked on.

**Comment by batpigandme** [comment] 2018-10-25 15:50
Oh, let me PR as far as I've gotten, and you can modify as you like

**Comment by clauswilke** [comment] 2018-12-10 17:34
I was just wondering whether we can close this issue and I noticed that we haven't done the last item of the check list: Add link to blog post in pkgdown news menu

@batpigandme Is this something you could do?

**Comment by batpigandme** [comment] 2018-12-10 17:44
@clauswilke Yup — not quite sure that's done, though, so I'm not gonna tick it off just yet https://github.com/tidyverse/ggplot2/pull/3033

**Closed** 2018-12-13 03:48 UTC
