### ISSUE TITLE
facet_grid problem: line plots not fully shown in faceted plots

### ISSUE THREAD

**Issue by ractingmatrix** [tidyverse/ggplot2#1988] opened 2017-01-05 16:29 UTC
i hope the two attached pictures are self-explanatory. I used the following code:

mt<-ggplot(data=SO2, aes(x=t, y=homeodds, group=HomeTeamName,col=HomeTeamName)) + geom_line()  +
ggtitle(SO2$LeagueName[1]) +
labs(x="Time", y="Odds")
mt+facet_grid(HomeTeamName~.,scale="free")

the first plot I got from mt is fine, with different lines on the same graph.  i want different lines on different graph. So i tried facet_grid using the code above and got the second plot. it however did not properly transform the first plot, as part of the lines were suppressed on the faceted plot.

![image](https://cloud.githubusercontent.com/assets/24869490/21688255/12970c0a-d3a7-11e6-94de-83ca5102f886.png)

![image](https://cloud.githubusercontent.com/assets/24869490/21688278/2837d490-d3a7-11e6-8ba4-45d68f4feb2b.png)

**Comment by hadley** [comment] 2017-01-24 23:54
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by hadley** [comment] 2017-01-25 15:32
Please provide a minimal reprex, or reproducible example. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me, help you! If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)".

**Comment by hadley** [comment] 2017-02-13 13:28
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-02-13 13:28 UTC
Labels: reprex
