### ISSUE TITLE
Using geom_tile() with scale_fill_gradientn() reverses the plot values

### ISSUE THREAD

**Issue by adam-erickson** [tidyverse/ggplot2#2903] opened 2018-09-19 19:49 UTC
As mentioned, using these two functions together to create a heat map over the year and DOY with repeated values per each cell reverses the values in fill. This is very unexpected behavior.

```r
library(ggplot2)
test = expand.grid(year=1990:2000, doy=1:366, hour=0:24)
test$nee = log(test$year) + sin(test$doy / 110) + test$hour
plot(nee ~ doy, test)
ggplot(test, aes(x=doy, y=year, fill=nee)) +
  geom_tile(color=NA, size=0.1) +
  scale_fill_gradientn(name="Legend", colors=jet(256), na.value="grey")
```

**Comment by batpigandme** [comment] 2018-09-19 19:53
Could you either turn this into a self-contained reproducible example with [reprex](reprex.tidyverse.org), or let me know what library `jet()` is in, so I can load and test? Thanks.

**Comment by adam-erickson** [comment] 2018-09-19 20:03
Sorry, jet() is this:

```r
jet = colorRampPalette(c("#00007F","blue","#007FFF","cyan","#7FFF7F","yellow","#FF7F00","red","#7F0000"))
```

**Comment by adam-erickson** [comment] 2018-09-19 20:05
Actually, I apologize but this example does not reproduce the error. Please ignore this for now.

**Comment by clauswilke** [comment] 2018-09-19 20:11
Also, be aware that you're plotting 25 surfaces on top of each other. Whatever unexpected result you've seen may have been caused by that.

``` r
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

jet = colorRampPalette(c("#00007F","blue","#007FFF","cyan","#7FFF7F","yellow","#FF7F00","red","#7F0000"))
test = expand.grid(year=1990:2000, doy=1:366, hour=0:24)
test$nee = log(test$year) + sin(test$doy / 110) + test$hour
ggplot(test, ggplot2::aes(x=doy, y=year, fill=nee)) +
  geom_tile(color=NA, size=0.1) +
  scale_fill_gradientn(name="Legend", colors=jet(256), na.value="grey") +
  facet_wrap(~hour)
```

![](https://i.imgur.com/Z6q01G2.png)

Created on 2018-09-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by adam-erickson** [comment] 2018-09-19 20:15
So, does is the final value for each cell then the sum of these 25 surfaces? I thought it was calculating the mean value, not the sum.

**Comment by clauswilke** [comment] 2018-09-19 20:29
You're just drawing them on top of each other, so the final result is simply the figure for `hour == 24`. If you want to average values across hours you have to do that outside of ggplot2, e.g. with dplyr.

I'm going to close this issue because I don't see any problems with `scale_fill_gradientn()`. It behaves as I would expect it to. If there is an actual problem, please open a new issue.

**Closed by clauswilke** 2018-09-19 20:29 UTC

**Comment by adam-erickson** [comment] 2018-09-19 20:37
Thank you for the explanation. There should probably be a way of calculating stat_summary() on the grid cells to prevent having to do more external data transformations. The aggregate() function is working fine for me for now.
