### ISSUE TITLE
Giving boundary might produce incorrect histogram

### ISSUE THREAD

**Issue by rmatev** [tidyverse/ggplot2#2482] opened 2018-03-14 13:02 UTC
In the following cases the plotted histogram has the first to bins incorrectly merged into one.
```R
qplot(c(1,1,1,2,2,3), binwidth=1, boundary=0)
qplot(c(1,1,1,2,2,3), binwidth=1, center=0.5)
```
The expected behaviour should be similar to the output of
```R
qplot(c(1,1,1,2,2,3), binwidth=1, boundary=1e-16)
```

Surprisingly, the following behaves correctly (only adding `xlim` w.r.t. the first example)
```R
qplot(c(1,1,1,2,2,3), binwidth=1, boundary=0) + xlim(0,3)
```
Note: I'm using master (39e4a3b) to test.

**Comment by batpigandme** [comment] 2018-03-14 13:09
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

**Comment by ptoche** [comment] 2018-03-15 01:25
@rmatev, and also please define "incorrectly" and "similar"!

**Comment by rmatev** [comment] 2018-03-16 10:32
@batpigandme I'm not sure being that pedantic helps in this particular case, but here it is.
@ptoche bins are incorrectly merged = bins should not be merged. In this particular example "similar" means "exactly the same" (since the binned values are integers). You can ignore that.


``` r
library(ggplot2)                                          
```

The following example wrongly merges the two lower bins

``` r
qplot(c(1,1,1,2,2,3), binwidth=1, boundary=0)             
```

![](https://i.imgur.com/FXVGzUG.png)

The following example produces the expected plot

``` r
qplot(c(1,1,1,2,2,3), binwidth=1, boundary=0) + xlim(0,3) 
```

![](https://i.imgur.com/GOuPVvl.png)

The following example produces the expected plot

``` r
qplot(c(1,1,1,2,2,3), binwidth=1, boundary=1e-16)         
```

![](https://i.imgur.com/IOIXrfn.png)

**Comment by rmatev** [comment] 2018-03-16 10:50
And just to be explicit, the post condition in this example is to

**Comment by batpigandme** [comment] 2018-03-16 12:20
> @batpigandme I'm not sure being that pedantic helps in this particular case, but here it is.

With several packages, and the issues that come with them, having the visuals in the same place as the discussion is incredibly useful. I wouldn't ask you to provide a reprex if the maintainers didn't find them helpful! 🙂

**Comment by ptoche** [comment] 2018-03-16 13:53
A little while ago I reported a similarly odd behaviour for ``geom_histogram()`` [here](https://github.com/tidyverse/ggplot2/issues/2323).

**Comment by hadley** [comment] 2018-04-27 13:51
@rmatev I currently have ~700 issues open across >100 repositories. You have been asked politely to provide a reprex created with the reprex package, which makes it easier for me to see the results at a glance and to rerun the code in my local R session. You have failed to do so, and so I am closing this issue. If you would like me to look at this problem, I'd recommend opening a new issue with a reprex, and explaining precisely what you think the problem is. (I suspect it's because the first bin, by convention, is closed on both sides)

**Closed by hadley** 2018-04-27 13:51 UTC

**Comment by rmatev** [comment] 2018-04-27 14:11
@hadley I'm sorry, I thought I had added one. I think you're right, I'll get back to this and submit a PR.
