### ISSUE TITLE
error message should be displaying ymin and ymax instead of ymin and ymin

### ISSUE THREAD

**Issue by sunroofgod** [tidyverse/ggplot2#5342] opened 2023-06-29 15:58 UTC
I found a problem with an error message that I received whilst plotting a custom Geom object with `position = "stack"`.

Unfortunately, i'm currently unable to replicate the code that I ran to obtain the error message but on line 259 of R/position-stack.R, it should be

```r
"Stacking requires either the {.field ymin} {.emph and} {.field ymax} or the {.field y} aesthetics",
```

as opposed to
```r
"Stacking requires either the {.field ymin} {.emph and} {.field ymin} or the {.field y} aesthetics",
```

hope this helps! :)

**Comment by teunbrand** [comment] 2023-06-29 16:09
This issue seems like a duplicate of #5339. Coincidentally, we just merged a PR for this typo today in #5340. So I'm going to mark this issue as completed too.

**Closed by teunbrand** 2023-06-29 16:09 UTC
