### ISSUE TITLE
label_parsed did not work

### ISSUE THREAD

**Issue by tungmilan** [tidyverse/ggplot2#2310] opened 2017-10-25 22:08 UTC
I followed the example from [ggplot ref](http://ggplot2.tidyverse.org/reference/labellers.html) but label_parsed didn't work 

```r
mtcars$cyl2 <- factor(mtcars$cyl, labels = c("alpha", "beta", "gamma"))
p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
p + facet_wrap(~vs + cyl2, labeller = label_parsed)
```
Result:  

![rplot_ggpl](https://user-images.githubusercontent.com/6590141/32025644-ed403604-b995-11e7-9ff2-09ebe097eb55.png)

Thanks!

**Comment by karawoo** [comment] 2017-10-26 15:55
This is a duplicate of #2279; I'm going to close this one but it's a known issue.

**Closed by karawoo** 2017-10-26 15:55 UTC

**Comment by ptoche** [comment] 2017-10-26 16:37
@tungmilan, please allow me to barge in for a second. If what you want is to have the greek letters alpha, beta, etc. may I recommend the alternative unicode approach, I use it all the time and works very well. See my answer here: https://stackoverflow.com/questions/27690729/greek-letters-symbols-and-line-breaks-inside-a-ggplot-legend-label
