### ISSUE TITLE
Unable to plot objects of type ITime

### ISSUE THREAD

**Issue by botanize** [tidyverse/ggplot2#2657] opened 2018-05-24 22:17 UTC
Data of class "ITime" cause ggplot error. Previously this worked fine, ggplot would default to a continuous scale and you could apply a label function to get reasonable axis labels. Now it warns and the errors with a missing aesthetic.

I dug around a little in the debugger and the data I pass in looks like this:

x| y
-|-
12:00:00|  3

But the data ggplot checks for aesthetics looks like this:

V1|  y
-|-
12:00:00|  3

Somehow the name of the "x" column is changed to "V1".

``` r
library(data.table)
library(ggplot2)

# Create a data.table with an ITime variable
dat <- data.table(x = as.ITime('12:00'), y = 3)
# convert to data.frame
setDF(dat)
# Plot 
ggplot(dat, aes(x, y)) + geom_point() # doesn't work
#> Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous.
#> Error: geom_point requires the following missing aesthetics: x
ggplot(dat, aes(as.POSIXct(x, origin = '1970-01-01'), as.POSIXct(y, origin = '1970-01-01'))) + geom_point() # works
```

![](https://i.imgur.com/Jg2R2NL.png)

``` r

# Strip ITime class and plot
dat2 <- dat
dat2$x <- unclass(dat2$x)
ggplot(dat2, aes(x, y)) + geom_point() # works
```

![](https://i.imgur.com/276lXwt.png)

``` r
ggplot(dat2, aes(x, y)) + geom_point() + scale_x_continuous(labels = function(x) structure(x, class = 'ITime')) # works
```

![](https://i.imgur.com/WMeUKoZ.png)
```

**Comment by clauswilke** [comment] 2018-05-25 05:29
I cannot reproduce your problem with the current development version. Which version of ggplot2 are you using?

``` r
library(data.table)
library(ggplot2)

# Create a data.table with an ITime variable
dat <- data.table(x = as.ITime('12:00'), y = 3)
# convert to data.frame
setDF(dat)

ggplot(dat, aes(x, y)) + 
  geom_point()
#> Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous.
```

![](https://i.imgur.com/63qbUlc.png)

``` r

ggplot(dat, aes(x, y)) + 
  geom_point() +
  scale_x_continuous(labels = function(x) structure(x, class = 'ITime'))
```

![](https://i.imgur.com/tQpcvcZ.png)

Created on 2018-05-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by botanize** [comment] 2018-05-25 16:28
ggplot2: 2.2.1
data.table: 1.11.2
R: 3.5.0

**Comment by clauswilke** [comment] 2018-05-25 17:08
Then this should be fixed once ggplot2 2.3.0 is released. Would you mind verifying that things work for you as expected with the development version of ggplot2?

**Comment by botanize** [comment] 2018-05-25 17:22
It works as expected in the development version. Any idea when 2.3.0 will be released?

**Comment by clauswilke** [comment] 2018-05-25 17:29
Current plan is end of June.

**Closed by clauswilke** 2018-05-25 17:29 UTC
