### ISSUE TITLE
Confusing warning in `geom_segment()` with length 1 aesthetics 

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/ggplot2#5762] opened 2024-03-07 20:24 UTC
Hi,

In the latest version, a warning is thrown if aesthetics are length 1 while the data is not, hinting to use `annotate()` instead of a geom.

Of note, I could have missed it but I couldn't find this change in NEWS.

While this warning should be legitimate in most cases, there are some where it does not make much sense and that `annotate()` is not usable, in my case when using `geom_segment()` with summary functions.

It is thrown in the documentation ([https://ggplot2.tidyverse.org/reference/aes_position.html](https://ggplot2.tidyverse.org/reference/aes_position.html#:~:text=%23%20Geom_segment%20examples)).

One could argue that the documentation example could indeed be replaced with `annotate()`, so here is an example that cannot:

``` r
library(ggplot2) 
ggplot(mtcars) +
  aes(x=mpg, y=disp) +
  geom_point() +
  geom_segment(aes(x=min(mpg), xend=max(mpg), y=min(disp), yend=max(disp)))
#> Warning in geom_segment(aes(x = min(mpg), xend = max(mpg), y = min(disp), : All aesthetics have length 1, but the data has 32 rows.
#> i Did you mean to use `annotate()`?
```

![](https://i.imgur.com/Pj2b6vW.png)

``` r

ggplot(mtcars) +
  aes(x=mpg, y=disp) +
  geom_point() +
  annotate("segment", x=min(mpg), xend=max(mpg), y=min(disp), yend=max(disp))
#> Error in FUN(X[[i]], ...): only defined on a data frame with all numeric-alike variables
```

<sup>Created on 2024-03-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by DanChaltiel** [comment] 2024-03-12 09:09
@teunbrand Using standard evaluation like in your example implies using the table name (`mtcars`), so we cannot pipe into `ggplot()`. This is a major issue in `annotate()`.

Thanks for the tip about warning suppressing :-) Feels a bit hacky but it works fine

**Comment by teunbrand** [comment] 2024-03-21 10:11
There are plenty of things that are not really pipeable for ggplot2, for example setting scale parameters, so preserving pipeability is only a minor concern. The proper way to go about this is implementing #3501 I guess, where you could arbitrarily summarise the data.

**Comment by clauswilke** [comment] 2024-03-24 19:19
I'm just seeing this for the first time, coming from #5797.

I feel it's important to highlight what exactly is going wrong here and in #5797. While the plot may look fine, it is not. The geom that triggers the warning is drawn over and over again, as many times as the data is duplicated. You can see this if you try to make the geom transparent. We used to get bug reports about problems with transparency all the time and it was always this issue.

I would strongly advise against suppressing the warning. Instead, fix the code so you actually draw only one line.

@teunbrand The actionable item here is maybe to improve the warning, instead of just saying "did you mean to use annotate()". Clearly people don't understand what the issue is.

``` r
library(ggplot2) 
ggplot(mtcars) +
  aes(x=mpg, y=disp) +
  geom_point() +
  geom_segment(
    aes(x=min(mpg), xend=max(mpg), y=min(disp), yend=max(disp)),
    alpha = 0.1, # should result in a transparent line
    linewidth = 5
  )
#> Warning in geom_segment(aes(x = min(mpg), xend = max(mpg), y = min(disp), : All aesthetics have length 1, but the data has 32 rows.
#> ℹ Did you mean to use `annotate()`?
```

![](https://i.imgur.com/ZS03jH9.png)

<sup>Created on 2024-03-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment] 2024-03-24 20:54
Yeah I agree with Claus that the warning is there for good reason.
Maybe something along the lines of:

> Drawing 32 duplicates of the layer, as aesthetics of length 1 are recycled to match the data.
> Did you mean to use `annotate()`?

The examples in the docs should be fixed, either by providing the data in the correct shape or using `annotate()`.

**Comment by clauswilke** [comment] 2024-03-24 21:25
I think the point is that people that run into this issue generally do not want to use `annotate()`. So maybe write something like "Please consider using `annotate()` or alternatively provide this layer with its own data set."

**Closed** 2024-04-02 07:56 UTC
Labels: messages
