### ISSUE TITLE
Mapping shape or size aesthetics is not propagated to legend in geom_sf

### ISSUE THREAD

**Issue by boshek** [tidyverse/ggplot2#2211] opened 2017-07-17 17:17 UTC
I looked around and wasn't able to find other documented instances of this. 

```r
library(sf)

devtools::install_github("tidyverse/ggplot2") ##most recent version of dev ggplot2
library(ggplot2)

nc <- st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)

## Create some point data to plot
points_sf <- data.frame(
  Latitude = c(35.7596, 35.7796), 
  Longitude = c(-79.0193, -78.6382),
  Site = c("X1","X2")
) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  st_transform(crs = 4267)

## Looks good on this plot; aesthetic not replicated in legend
ggplot(nc) +
  geom_sf() +
  geom_sf(data = points_sf, aes(shape = Site))

## Same here 
ggplot(nc) +
  geom_sf() +
  geom_sf(data = points_sf, aes(size = Site))
```
Even when some element is mapped to the legend like with `colour`, the empty box is unexpected:
```r
ggplot(nc) +
  geom_sf() +
  geom_sf(data = points_sf, aes(colour = Site))
```
Typically `ggplot2` would add appropriate points to the legend like this:
```r
ggplot(iris, aes(x = Petal.Width, y = Sepal.Width)) +
  geom_point(aes(colour = Species))
```
I am highlighting this because it seems like this is an instance where `geom_sf` doesn't function like a `ggplot2` user would expect it to do so.

**Comment by karawoo** [comment] 2017-07-18 17:20
I believe this is a duplicate of #2037

**Closed by karawoo** 2017-07-18 17:20 UTC
