### ISSUE TITLE
Unclear error message with geom_rect according to the docs

### ISSUE THREAD

**Issue by agila5** [tidyverse/ggplot2#5441] opened 2023-09-27 08:00 UTC
Dear all, I was working on some R code that deals with the representation of time series data and I faced a slightly weird error that can be summarised as follows: 

``` r
library(ggplot2)

td <- data.frame(
  x = 1:10, 
  y = rnorm(10) 
)
one_rect <- data.frame(
  xmin = 1, 
  xmax = 2
)

ggplot(td, aes(x = x, y = y)) + 
  geom_line() + 
  geom_rect(aes(xmin = xmin, xmax = xmax), data = one_rect, ymin = -1, ymax = 0)
#> Error in `geom_rect()`:
#> ! Problem while computing aesthetics.
#> ℹ Error occurred in the 2nd layer.
#> Caused by error:
#> ! object 'x' not found
#> Backtrace:
#>      ▆
#>   1. ├─base::tryCatch(...)
#>   2. │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>   3. │   ├─base (local) tryCatchOne(...)
#>   4. │   │ └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>   5. │   └─base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
#>   6. │     └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>   7. │       └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>   8. ├─base::withCallingHandlers(...)
#>   9. ├─base::saveRDS(...)
#>  10. ├─base::do.call(...)
#>  11. ├─base (local) `<fn>`(...)
#>  12. ├─global `<fn>`(input = base::quote("ash-crane_reprex.R"))
#>  13. │ └─rmarkdown::render(input, quiet = TRUE, envir = globalenv(), encoding = "UTF-8")
#>  14. │   └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
#>  15. │     └─knitr:::process_file(text, output)
#>  16. │       ├─base::withCallingHandlers(...)
#>  17. │       ├─base::withCallingHandlers(...)
#>  18. │       ├─knitr:::process_group(group)
#>  19. │       └─knitr:::process_group.block(group)
#>  20. │         └─knitr:::call_block(x)
#>  21. │           └─knitr:::block_exec(params)
#>  22. │             └─knitr:::eng_r(options)
#>  23. │               ├─knitr:::in_input_dir(...)
#>  24. │               │ └─knitr:::in_dir(input_dir(), expr)
#>  25. │               └─knitr (local) evaluate(...)
#>  26. │                 └─evaluate::evaluate(...)
#>  27. │                   └─evaluate:::evaluate_call(...)
#>  28. │                     ├─evaluate (local) handle(...)
#>  29. │                     │ └─base::try(f, silent = TRUE)
#>  30. │                     │   └─base::tryCatch(...)
#>  31. │                     │     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  32. │                     │       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  33. │                     │         └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  34. │                     ├─base::withCallingHandlers(...)
#>  35. │                     ├─base::withVisible(value_fun(ev$value, ev$visible))
#>  36. │                     └─knitr (local) value_fun(ev$value, ev$visible)
#>  37. │                       └─knitr (local) fun(x, options = options)
#>  38. │                         ├─base::withVisible(knit_print(x, ...))
#>  39. │                         ├─knitr::knit_print(x, ...)
#>  40. │                         └─knitr:::knit_print.default(x, ...)
#>  41. │                           └─evaluate (local) normal_print(x)
#>  42. │                             ├─base::print(x)
#>  43. │                             └─ggplot2:::print.ggplot(x)
#>  44. │                               ├─ggplot2::ggplot_build(x)
#>  45. │                               └─ggplot2:::ggplot_build.ggplot(x)
#>  46. │                                 └─ggplot2:::by_layer(...)
#>  47. │                                   ├─rlang::try_fetch(...)
#>  48. │                                   │ ├─base::tryCatch(...)
#>  49. │                                   │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  50. │                                   │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  51. │                                   │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  52. │                                   │ └─base::withCallingHandlers(...)
#>  53. │                                   └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])
#>  54. │                                     └─l$compute_aesthetics(d, plot)
#>  55. │                                       └─ggplot2 (local) compute_aesthetics(..., self = self)
#>  56. │                                         └─base::lapply(aesthetics, eval_tidy, data = data, env = env)
#>  57. │                                           └─rlang (local) FUN(X[[i]], ...)
#>  58. └─base::.handleSimpleError(`<fn>`, "object 'x' not found", base::quote(NULL))
#>  59.   └─rlang (local) h(simpleError(msg, call))
#>  60.     └─handlers[[1L]](cnd)
#>  61.       └─cli::cli_abort(...)
#>  62.         └─rlang::abort(...)
```

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I know I can easily fix this problem by just moving the specification of the aesthetic from the "general" ggplot2 call to the `geom_line()` call: 

``` r
ggplot(td) + 
  geom_line(aes(x = x, y = y)) + 
  geom_rect(aes(xmin = xmin, xmax = xmax), data = one_rect, ymin = -1, ymax = 0) 
```

Nevertheless, in my opinion, that error message is not clear since, according to the documentation, `geom_rect()` is parametrised according to four aesthetics which are `xmin, xmax, ymin, ymax` and `x` is not even mentioned there.

**Comment by teunbrand** [comment] 2023-09-27 08:09
I agree that this error message isn't very helpful, but it might be challenging to intercept as it is thrown by R itself.
The issue seems to be that the `geom_rect()` layer searches for `x` (and `y`) in its `data` argument, whereas these live in the global data.
An alternative to moving aesthetics is setting `geom_rect(..., inherit.aes = FALSE)`.

**Comment by teunbrand** [comment] 2023-11-29 09:14
This issue is a duplicate of #3364 and I think the same advice holds: explicitly set `inherit.aes = FALSE` when you don't want the global mapping to affect your layer's mapping.

**Closed by teunbrand** 2023-11-29 09:14 UTC
Labels: messages
