### ISSUE TITLE
[Suggestion/feature request] Introduce tick.color in scale_*_gradientn

### ISSUE THREAD

**Issue by andzandz11** [tidyverse/ggplot2#2359] opened 2017-12-06 10:48 UTC
Very often I have a colorbar from white to blue and in the whiter parts the ticks can not be seen, well because they are white also. It would help if could specify the color of the ticks, so I can set them to black for example. I think this would require minimal code change (2 lines probably) and would have a great benefit.

**Comment by andzandz11** [comment] 2017-12-06 10:53
Thie does not work for me:
+  guides(fill = guide_colourbar(barheight = unit(3, "in"),
   ticks=element_line(color='black'), border=element_line(color='black')))

Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'guide_black' of mode 'function' was not found

**Comment by batpigandme** [comment] 2017-12-06 13:11
Could you please build this out as a full minimal reproducible example (aka a [reprex](https://www.tidyverse.org/help/#reprex))? 

It will be much easier to troubleshoot if we can be sure we're on the same page.
Thanks

**Comment by andzandz11** [comment] 2017-12-06 14:52
I tried to remove as much as I could. The data is not so important, my questions are about the legend only.

I would like to be able to make the legend ticks black please.

Here are other things that came into my mind:
1) The color bar is too short. The 1.00 value is plotted above/below the colorbar in the legend.
1.1) The tick of the 1.00 value is plotted even there is no colorbar at the position.
2) There is no text collision awareness between legend title and legend text.
2.1) Legend text is allowed to be plotted outside of the legend frame.
3) The legend can not have the same alpha level as the data. (Or any alpha level, to start with.)


Thank you!


```
library(ggplot2)
set.seed(1) 


conf <- rnorm(1000, mean=0.65, sd=0.1) %>% abs %>% subset(.,.<1) %>% c(.,0,1)
fam <- sample(1:50,length(conf),replace=T) 

ident80 <- cbind.data.frame(fam=1:50,
                            ident80=sample(x=seq(0,1,0.1),size=unique(fam)%>%length,replace=T)  
)

dat <- cbind.data.frame(fam=fam,conf=conf)
dat <- merge(ident80,dat,by="fam")



ggplot(dat=dat,aes(x=fam,group=fam)
) + geom_jitter(
  aes(y=conf,color=conf),
  height = 0,
  width = 0.4
) + geom_point(
  aes(y=ident80,fill=ident80),
  alpha=0.05,
  shape=24,
  size=4
) + scale_color_gradientn (
  colors=colorRampPalette(c("white","cyan3"),alpha=F)(2),
  name="[&%$§)(%]"
) + scale_fill_gradientn(
  colors=
    colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan","#7FFF7F", "yellow", "#FF7F00", "red","#7F0000")
                     ,alpha=F)(9),
  name="serft[%]",
  trans="reverse"
) + theme(
  legend.position = c(1,0.005),
  legend.text= element_text(colour="black",size=12),
  legend.text.align = 0.5,
  legend.title= element_text(face="bold",size=16),
  legend.justification = c(1,0),
  legend.box="horizontal",
  legend.background = element_rect(colour="black",fill=alpha("grey90", .85)),
  legend.key=element_blank()
)

###this is causing an error:
+ guides(
  ticks=element_line(color='black'),
  border=element_line(color='black')
)


```

**Comment by batpigandme** [comment] 2017-12-06 15:09
I'm not sure you looked at the reprex guidelines, as this code isn't self-contained (ggplot2 itself doesn't export the `%>%` operator).

For issues, it's much easier (and more likely to be resolved) if you stick to just one thing– which, in this case, is supposed to be the legend ticks (if I'm understanding you correctly). So, if you could make a _minimal_ example that involves data and a gradient colourbar, it'll be a good start toward isolating the issue and/or feature request.

In addition to the reprex section of the tidyverse site (linked to above), there's a quick, helpful overview of the package and how to use it in [this video](https://vimeo.com/208749032). (The most relevant material starts ~10:40).

You can also see the slides from that video [here](https://speakerdeck.com/jennybc/reprex-help-me-help-you).

**Comment by andzandz11** [comment] 2017-12-06 15:21
Ok cool,

```

library(ggplot2)
set.seed(1)

conf <- c(0,1,abs(rnorm(1000, mean=0.65, sd=0.1)))
conf <- conf[conf<=1]
fam <- sample(1:50,length(conf),replace=T) 
dat <- cbind.data.frame(fam=fam,conf=conf)


ggplot(dat=dat,aes(x=fam,group=fam)
) + geom_jitter(
  aes(y=conf,color=conf)
) + scale_color_gradientn (
  colors=c(colorRampPalette(c("white","cyan3"),alpha=F)(10),"#000000"),
  name="[&%$§)(%]")
  
  
  
  
```

**Comment by batpigandme** [comment] 2017-12-06 15:38
reprex of code above

``` r
library(ggplot2)

conf <- c(0, 1, abs(rnorm(1000, mean = 0.65, sd = 0.1)))
conf <- conf[conf <= 1]
fam <- sample(1:50, length(conf), replace = T)
dat <- cbind.data.frame(fam = fam, conf = conf)


ggplot(dat = dat, aes(x = fam, group = fam)) + 
  geom_jitter(aes(y = conf, color = conf)) +
  scale_color_gradientn(colors = c(colorRampPalette(c("white", "grey90", "cyan3"), alpha = F)(10), "#000000"),
  name = "[&%$§)(%]")
```

![](https://i.imgur.com/y5m3TCr.png)

Created on 2017-12-06 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by batpigandme** [comment] 2017-12-06 17:35
Related (duplicate of?) #1994

**Closed** 2017-12-06 17:52 UTC
