### ISSUE TITLE
Calling ggplot2 through rJava on Ubuntu20

### ISSUE THREAD

**Issue by manjumc1975** [tidyverse/ggplot2#5580] opened 2023-12-13 06:18 UTC
We are facing a problem while running ggplot through rJava.

The problem occurs only if the geom_line() parameter is used with ggplot2.

The code runs properly and produces the graph for the first iteration, but it fails in the second iteration and the java application is terminated.

This problem is faced while using R version 4.3.1 on Ubuntu 20 and java version 17.

This problem does not occur and the code runs fine on Ubuntu 18

`import org.rosuda.JRI.REXP;`
`import org.rosuda.JRI.Rengine;`
`public class Sample {`
`public static void main(String[] args) throws InterruptedException {`
               `Rengine engine=new Rengine (new String [] {"--vanilla"}, false, null);`
                `for (int i = 0; i < 1; i ++) {`
                `System.gc();`
`engine.eval("x<-c(1:10)");`
` engine.eval("y<-c(1:10)");`
`engine.eval("xy<-data.frame(x,y)");`
`engine.eval("library(ggplot2)");`
`engine.eval("z<-ggplot(xy, aes(x, y))+geom_line()");`
`engine.eval("print(z)");`
`System.gc();`
`System.out.println("Done");`
`}`
`}`
`}`

**Comment by thomasp85** [comment] 2023-12-13 06:46
It is hard to give any guesses as to the cause without further info. `geom_line()` is not a particular "dangerous" function so perhaps the issue is more with either grid or the graphic device used?

**Comment by teunbrand** [comment] 2024-03-21 10:42
Unless the problem can be reproduced in R on Windows/MacOS/Linux without the intervention of java, I think we should close this. I for sure don't even know how to begin to reproduce this.

**Closed by teunbrand** 2024-03-21 10:42 UTC
