### ISSUE TITLE
geom_smooth() discrepancy between "auto" and "gam" methods

### ISSUE THREAD

**Issue by analca3** [tidyverse/ggplot2#1970] opened 2016-12-29 15:14 UTC
Hi! I'm not an expert with ggplot but I like it very much. I think I've found a bug.

ggplot version 2.2.0 from CRAN. R 3.3.2 from ArchLinux repos.

I've plotted `diamonds` dataset from ggplot and I don't understand this behaviour of geom_smooth.

```
ggplot(diamonds, aes(x, price)) + geom_point() + geom_smooth(method = "auto")
```
It returns this as a warning

```
`geom_smooth()` using method = 'gam'
```

![image](https://cloud.githubusercontent.com/assets/3939991/21546752/77dc6fc2-cde1-11e6-9042-4821ef80c787.png)

If I specify the 'gam' method, it returns this plot

```
ggplot(diamonds, aes(x, price)) + geom_point() + geom_smooth(method = "gam")
```

![image](https://cloud.githubusercontent.com/assets/3939991/21546767/972d00f8-cde1-11e6-9fd5-8f9df4b6f425.png)

Are there anything that I can't understand or is this a bug? It occurs with other datasets, too, but only if "auto" method returns "gam" method.

Thank you!

**Comment by hadley** [comment] 2017-01-02 23:41
Duplicate of #1951

**Closed by hadley** 2017-01-02 23:41 UTC
