### ISSUE TITLE
Confusing test failure for sf_transform_xy() "no arguments in initialization list"

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/ggplot2#5201] opened 2023-02-22 00:02 UTC
We are observing this test failure:

```
── Error ('test-coord_sf.R:290'): sf_transform_xy() works ──────────────────────
Error in `proj_from_crs(from)`: no arguments in initialization list: GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["unknown"],
        AREA["World"],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
Backtrace:
    ▆
 1. └─ggplot2::sf_transform_xy(data, 3347, 4326) at test-coord_sf.R:290:2
 2.   └─sf::sf_project(...)
 3.     └─sf (local) proj_from_crs(from)
```

Probably this is related to missing certain GDAL drivers. But I hope you agree the error message is not very helpful. I'm not sure if this is something on the ggplot2 or the sf side; I know sf offers some things we could use to escape here e.g. `sf_extSoftVersion()` or `is_driver_available()`:

https://github.com/r-spatial/sf/blob/b798413d4cd681cd173f9bdc110f2a014555ee09/tests/testthat/test_read.R#L176

https://github.com/r-spatial/sf/blob/b798413d4cd681cd173f9bdc110f2a014555ee09/tests/testthat/test_read.R#L121

Happy to offer more details as needed but I'm not sure what would help.

---

FWIW, the issue also causes some examples to fail:

https://github.com/tidyverse/ggplot2/blob/519bc83942d93bca4777b75ab3f9f79d3200b745/man/geom_map.Rd#L125-L162

https://github.com/tidyverse/ggplot2/blob/519bc83942d93bca4777b75ab3f9f79d3200b745/man/sf_transform_xy.Rd#L27-L43

**Comment by teunbrand** [comment] 2024-03-28 15:36
I'm relatively sure ggplot2 assumes that when {sf} is installed, the GDAL drivers work as intended.

I agree that the error message isn't helpful, but it is thrown from an {sf} function so there is little control that ggplot2 has over the message other than wrapping every piece of {sf} related code in `tryCatch()` blocks.

Other than putting the `geom_map()` examples that use `coord_sf()` in `if (require("sf"))` blocks, I'm not sure what ggplot2 can do about this issue.

**Comment by MichaelChirico** [comment] 2024-03-29 04:22
{sf} owns the error message, but {ggplot2} owns the map data & I would guess could be responsible for knowing where it comes from & thus what drivers are needed to process it?

@edzer WDYT? Is there anything reasonably straightforward {ggplot2} and/or {sf} could do to help with the error messaging here?

**Comment by edzer** [comment] 2024-03-29 09:40
@MichaelChirico I'm not sure; can you provide a reprex that triggers this, or point to where it happens? I've never seen the ` no arguments in initialization list` error, I believe.

**Comment by MichaelChirico** [comment] 2024-03-29 17:40
I can point to the line causing it:

https://github.com/tidyverse/ggplot2/blob/e0d54f6d2be6452bbab61a5018abc231a3172ca6/tests/testthat/test-coord_sf.R#L290

But it will be hard to offer a reprex I'm afraid, sorry :\

**Comment by edzer** [comment] 2024-03-29 18:52
I can only find the error message [here](https://github.com/OSGeo/PROJ/blob/master/src/apps/geod_set.cpp#L19), but that should not be callable (it's part of a standalone app, not the PROJ library we use). What does `sf::sf_extSoftVersion()` give on your system?

**Comment by MichaelChirico** [comment] 2024-03-29 18:56
I'll have to return to this when I'm off leave in May

**Comment by MichaelChirico** [comment] 2024-05-07 18:49
```
sf::sf_extSoftVersion()
#                  GEOS                  GDAL                proj.4        GDAL_with_GEOS            USE_PROJ_H                  PROJ 
#               "3.5.0" "3.6.0dev-7f16b09a89"               "7.0.0"                "true"               "false"               "7.0.0"
```

**Comment by edzer** [comment] 2024-05-07 21:22
That's a pretty old software stack; does the error persist with updated sys reqs?

**Comment by MichaelChirico** [comment] 2024-05-07 21:28
I'll report back when it's updated but that may take years :)

**Comment by teunbrand** [comment] 2024-11-15 12:58
I'm going to go ahead and close this issue as there isn't anything I can easily investigate. 
If you can find a reprex with a recentish software stack, I'd be happy to reopen this issue and find ways ggplot2/sf can improve upon the messaging here.

**Closed by teunbrand** 2024-11-15 12:58 UTC
Labels: internals :mag_right:, messages
