### ISSUE TITLE
`facet_grid()` facet labels cannot be rotated when switched from right to left

### ISSUE THREAD

**Issue by ntthung** [tidyverse/ggplot2#3971] opened 2020-04-29 05:48 UTC
## Updated

`strip.text.y.left` is not documented. This issue becomes a documentation one.

## Original issue raised:

When facet labels are on the right, they can be rotated:

```r
d2 <- diamonds[sample(seq_len(nrow(diamonds)), 1000), ]
ggplot(d2) +
  geom_point(aes(carat, price)) +
  facet_grid(vars(cut), vars(color)) +
  theme(strip.text.y = element_text(angle = 0))
```
![image](https://user-images.githubusercontent.com/22501446/80564085-6ddc6100-8a1f-11ea-9813-f2a4ba20e90c.png)

Now add `switch = 'y'` to `facet_grid()` and the facet labels are not rotated anymore.

```r
ggplot(d2) +
  geom_point(aes(carat, price)) +
  facet_grid(vars(cut), vars(color), switch = 'y') +
  theme(strip.text.y = element_text(angle = 0))
```
![image](https://user-images.githubusercontent.com/22501446/80564183-b267fc80-8a1f-11ea-98ef-0562bd8316ee.png)

If this is possible, then I can move the facet labels to the left and move the y-axis to the right. I want the facet labels to be horizontal so that they are easier to read.

**Comment by certara-smouksassi** [comment] 2020-04-29 06:07
you need to use :
theme(strip.text.y.left = element_text(angle = 0))

**Comment by smouksassi** [comment] 2020-04-29 06:38
duplicate of #3888

**Comment by ntthung** [comment] 2020-04-29 08:34
Thanks @certara-smouksassi . I didn't know `strip.text.y.left` exists; it's not in the documentation. Perhaps this issue becomes a documentation one.

**Closed** 2020-04-30 18:17 UTC
