### ISSUE TITLE
wrong detection of outlier with ggplot

### ISSUE THREAD

**Issue by BegoniaCampos** [tidyverse/ggplot2#6017] opened 2024-07-29 10:30 UTC
I found that using the same data, an outlier was detected when plotting a boxplot with "ggplot" but not with "boxplot" (base). Therefore, I performed the upper and lower inner fences calculations following Tukey (1977) and no observations in group A met the outlier criterion.
![boxplot-outlier](https://github.com/user-attachments/assets/7cda1830-f73c-4b3b-bfce-e3887cc4752f)
What am I missing?
Here is the code to reproduce the bug:

```r
Groups <- factor(c(rep("A",4),rep("B",4)))
yA <- c(1.186, 1.189, 1.191, 1.206)
yB <- c(1.182, 1.185, 1.193, 1.201)
y <- c(yA, yB)dd <- data.frame(Groups, y)
boxplot(y~Groups)
ggplot(data = dd, aes(x = factor(Groups), y = y)) + geom_boxplot()
boxplot.stats(subset(dd$y,Groups=="A"))$out
fivenum(subset(dd$y,Groups=="A"))  #Tukey 1977 
#
reprex::reprex()
```

**Comment by teunbrand** [comment] 2024-07-29 10:49
This is a duplicate of #281. TL;DR: yes it is different, but the difference is documented. See the 'summary statistics' section of `?geom_boxplot`.

**Closed by teunbrand** 2024-07-29 10:49 UTC
