### ISSUE TITLE
strange behavior with the margin of legend.text for R3.5

### ISSUE THREAD

**Issue by earthcli** [tidyverse/ggplot2#2943] opened 2018-10-16 03:49 UTC
I have updated my R to version 3.5. There is  too small margin for legend.text when using theme(legend.title=element_blank()), while it is normal without adding this line code.

``` r
require(ggplot2)
df <- reshape2::melt(outer(1:4, 1:4), varnames = c("X1", "X2"))
p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
p1+scale_fill_continuous(guide = guide_legend())
# there is normal spacing (margin) for legend.text

p1+scale_fill_continuous(guide = guide_legend())+
  theme(legend.title=element_blank())
# there is too small spacing (margin) for legend.text
```

**Comment by clauswilke** [comment] 2018-10-16 04:41
Here is a reprex. The problem is that the default `legend.spacing.x` is calculated based on the title font size, and when there is no title the font size is zero. Workaround is to set `legend.spacing.x` manually. A fix could be to look for the default font size before setting it to zero, or just setting it to 11pt instead of 0.

``` r
library(ggplot2)
df <- reshape2::melt(outer(1:4, 1:4), varnames = c("X1", "X2"))
p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
p1+scale_fill_continuous(guide = guide_legend())
```

![](https://i.imgur.com/8IYps3X.png)

``` r

p1+scale_fill_continuous(guide = guide_legend())+
  theme(legend.title=element_blank())
```

![](https://i.imgur.com/zWnak0F.png)

``` r

p1+scale_fill_continuous(guide = guide_legend())+
  theme(legend.title=element_blank(),
        legend.spacing.x = unit(5.5, "pt"))
```

![](https://i.imgur.com/oefksE1.png)

<sup>Created on 2018-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by earthcli** [comment] 2018-10-16 06:43
Thanks, this is exactly what I am looking for.
I have worked around by using theme(legend.title=element_text(color="transparent"))

**Comment by thomasp85** [comment] 2019-04-23 09:48
My feeling is that it would be better to make it dependent on the legend text size rather than the legend title... that would probably slightly change a lot of visualisations... @clauswilke what is your feeling about the best fix? I personally don't think we should be too afraid of slight visual changes for the greater good

**Comment by clauswilke** [comment] 2019-04-23 13:51
I wouldn't object to minor visual changes, however I think your proposed solution doesn't get to the heart of the problem, and similar issues could continue to pop up (e.g., if somebody sets the legend text to `element_blank()`).

The problem is that `element_blank()` doesn't define a font size and the legend drawing code doesn't realize that. A proper fix would address that issue. I'll take a look.

Note a broadly related issue we have forgotten but maybe should tackle at the same time: #2728

**Comment by thomasp85** [comment] 2019-04-23 13:55
I think setting legend text to element_blank would be a non-issue as the spacing would then be invisible (the reason for proposing that approach)

**Comment by clauswilke** [comment] 2019-04-23 16:12
No, it's a little more complicated here, because we need to guess the title font size to calculate the default legend spacing:
https://github.com/tidyverse/ggplot2/blob/f79712f0dd733cbcec63d609859eca1e6da46fe8/R/guide-legend.r#L330-L336

One simple option would be to replace the 0 at the end of this line with some positive value, e.g. the legend title font size in `theme_grey()`:
https://github.com/tidyverse/ggplot2/blob/f79712f0dd733cbcec63d609859eca1e6da46fe8/R/guide-legend.r#L330

**Comment by thomasp85** [comment] 2019-04-23 16:48
I may be getting tired, but I still don’t see the benefit of using the title size as opposed to the label size

**Comment by clauswilke** [comment] 2019-04-23 18:09
> I may be getting tired, but I still don’t see the benefit of using the title size as opposed to the label size

My point was that we're dealing with two separate issues. One is which theme element to draw the font size from. It's currently the legend title, but it could also be the legend text. I have no strong opinion about that. The other is what happens if that element is blank. We still need a default then either way. Currently the default is 0, and that was probably a bad choice when I made it.

**Comment by thomasp85** [comment] 2019-04-23 18:37
Ok, then my original point was that the default value is ok to be zero if we rely on the legend text, because any spacing will be invisible no matter what (as the text is not there to mark the other side of the spacing)

**Comment by clauswilke** [comment] 2019-04-23 18:57
Unfortunately the spacing variables are used in a couple of different contexts (this really needs to be disentangled at some point) and I don't think we can rely on this assumption. See also this comment:

https://github.com/tidyverse/ggplot2/blob/f79712f0dd733cbcec63d609859eca1e6da46fe8/R/guide-legend.r#L333-L334

I think using a non-zero hardcoded default value is likely going to be the safest option, regardless of where we take the fontsize from otherwise.

**Comment by thomasp85** [comment] 2019-04-23 18:58
ok, I trust you on this (and most other things tbf :-) )

**Closed** 2019-04-29 14:38 UTC
