### ISSUE TITLE
Error : Computation failed in `stat_bin()`: `binwidth` must be positive 

### ISSUE THREAD

**Issue by rajkstats** [tidyverse/ggplot2#3043] opened 2018-12-20 20:45 UTC
This might be related to a previous issue: 
https://github.com/tidyverse/ggplot2/issues/2312

I am using the function below to create multiple histograms in one plot. It seems that features with zero variance / one value are not getting plotted.  It was working with previous version of ggplot2. Please help me in fixing this. 

plot_hist_facet <- function(data, bins = 10, ncol = 5, 
                            fct_reorder = FALSE, fct_rev = FALSE,
                            fill = palette_light()[[3]],
                            color = "white", scale = "free") {
  
  data_factored <- data %>%
    mutate_if(is.character, as.factor) %>%
    mutate_if(is.factor, as.numeric) %>%
    gather(key = key, value = value, factor_key = TRUE)
  
  if(fct_reorder) {
    data_factored <- data_factored %>%
      mutate(key = as.character(key) %>% as.factor())
  }
  
  if(fct_rev){
    data_factored <- data_factored %>%
      mutate(key = fct_rev(key))
  }
  
  g <- data_factored %>%
    ggplot(aes(x = value, group = key )) +
    geom_histogram(bins = bins, fill = fill , color = color,
                   ) +
    facet_wrap(~ key, ncol = ncol, scale = scale) +
    theme_tq()

  
  return(g)
  
}

Getting Computation failed in `stat_bin()`: `binwidth` must be positive  error 
![snip20181221_20](https://user-images.githubusercontent.com/10900298/50309735-ec3d0080-04c5-11e9-82d6-bc160878d251.png)

**Comment by batpigandme** [comment] 2018-12-21 12:46
Transferring this issue to ggplot2 👍

**Comment by ptoche** [comment] 2018-12-21 19:47
This does not look like a "minimal example"... Can you identify which of these many plots is associated with an error? (retry plot by plot) From the error message, are you attempting to set too many bins (10) for too little data?

**Comment by rajkstats** [comment] 2018-12-24 21:08
Thanks @ptoche  for following up. Hope following is what you are looking to reproduce


``` r
library(readxl)
library(httr)
library(tidyverse)
library(tidyquant)
#> Loading required package: lubridate
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
#> Loading required package: PerformanceAnalytics
#> Loading required package: xts
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> 
#> Attaching package: 'xts'
#> The following objects are masked from 'package:dplyr':
#> 
#>     first, last
#> 
#> Attaching package: 'PerformanceAnalytics'
#> The following object is masked from 'package:graphics':
#> 
#>     legend
#> Loading required package: quantmod
#> Loading required package: TTR
#> Version 0.4-0 included new data defaults. See ?getSymbols.

url <- "https://community.watsonanalytics.com/wp-content/uploads/2016/06/HR-Employee-Attrition-data.xlsx"
GET(url, write_disk(tf <- tempfile(fileext = ".xlsx")))
#> Response [https://community.watsonanalytics.com/wp-content/uploads/2016/06/HR-Employee-Attrition-data.xlsx]
#>   Date: 2018-12-24 21:07
#>   Status: 200
#>   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
#>   Size: 266 kB
#> <ON DISK>  /var/folders/gl/wb7rqfgd3v708q5m0ydj3pkc0000gq/T//RtmpA1oFEE/file108fe1d346270.xlsx
data<- read_excel(tf)
data <- data %>%
  select('Over 18')

bins = 5
ncol = 1
fct_reorder = FALSE
fct_rev = FALSE
fill = palette_light()[[3]]
color = "white" 
scale = "free"

data_factored <- data %>%
  mutate_if(is.character, as.factor) %>%
  mutate_if(is.factor, as.numeric) %>%
  gather(key = key, value = value, factor_key = TRUE)

dput(head(data_factored,10))
#> structure(list(key = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
#> 1L, 1L, 1L), .Label = "Over 18", class = "factor"), value = c(1, 
#> 1, 1, 1, 1, 1, 1, 1, 1, 1)), row.names = c(NA, -10L), class = c("tbl_df", 
#> "tbl", "data.frame"))

data_factored %>%
  ggplot(aes(x = value, group = key )) +
  geom_histogram(bins = bins, fill = fill , color = color,
  ) +
  facet_wrap(~ key, ncol = ncol, scale = scale) +
  theme_tq()
#> Warning: Computation failed in `stat_bin()`:
#> `binwidth` must be positive
```

![](https://i.imgur.com/uVtsDlz.png)

<sup>Created on 2018-12-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment] 2018-12-25 04:43
You can use the result of `dput()` as the minimal data, so that we can shortcut to reproduce your code easily.

```r
data_factored <- structure(list(key = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L), .Label = "Over 18", class = "factor"), value = c(1, 
1, 1, 1, 1, 1, 1, 1, 1, 1)), row.names = c(NA, -10L), class = c("tbl_df", 
"tbl", "data.frame"))

data_factored %>%
  ggplot(aes(x = value, group = key )) +
  geom_histogram(bins = bins, fill = fill , color = color) +
  facet_wrap(~ key, ncol = ncol, scale = scale) +
  theme_tq()
```

I guess the code below is the minimal version of the problem; if there's only one value, `stat_bin()` cannot calculate the binwidth.

``` r
library(ggplot2)

d <- data.frame(x = rep(1, 100))
ggplot(d, aes(x = x)) +
  geom_histogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Computation failed in `stat_bin()`:
#> `binwidth` must be positive
```

![](https://i.imgur.com/mItBTsQ.png)

<sup>Created on 2018-12-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This is because `bin_breaks_bins()` fails if the upper and the lower of the range are the same. Maybe it should return a fixed value in such cases? At least, I want to make error message friendlier.

https://github.com/tidyverse/ggplot2/blob/7f13dfafccea19304ae140eb14a6cdfd5b5275ec/R/bin.R#L104

**Comment by ptoche** [comment] 2018-12-25 08:42
@yutannihilation : this is pretty much the problem we suspected from the start. I don't think the error message is that bad... Having said that, a possible improvement would be to set bins to 1 if there isn't enough data to compute a width, e.g. along the lines of ``if (length(unique(na.omit(data[, "x"]))) == 1) bins = 1``, so that a single bin would be used in such degenerate cases.

**Comment by yutannihilation** [comment] 2018-12-26 01:39
Thanks, but I think `geom_histogram(bins = 1)` still gives you error since `bin_breaks_bins()` cannot calculate the binwidth for a 0-width range. So, I think what we should provide specially is width in this case.

**Comment by ptoche** [comment] 2018-12-26 07:38
@yutannihilation, Indeed you're right, ``geom_histogram`` would produce an error in this case. But  I don't think that's the correct behaviour either. I think a histogram for a single category ought to be... a simple barchart. Basically ``geom_histogram()`` should default to ``geom_bar()``. 

From a basic definition of a histogram (wikipedia, I'm afraid): "To construct a histogram, divide the entire range of values into a series of intervals and then count how many values fall into each interval." In the case you have highlighted, ``data.frame(x = rep(1, 100))``, my instinct would be to draw a single bin of some arbitrary width.  What do you think?

What I mean is that I think the histogram should look like this:

    library(ggplot2)
    d <- data.frame(x = rep(1, 100))
    ggplot(d, aes(x = x)) +
        geom_bar()

**Comment by ptoche** [comment] 2018-12-26 07:43
Note a related discussion [here](https://github.com/plotly/plotly.js/issues/1229)

**Comment by yutannihilation** [comment] 2018-12-26 09:01
I basically agree with you in that this is a problem, I just disagreed with this part:

> a possible improvement would be to set bins to 1

**Closed** 2019-01-26 01:21 UTC
