### ISSUE TITLE
ggplot call changes locale LC_NUMERIC variable

### ISSUE THREAD

**Issue by SamuelAllain** [tidyverse/ggplot2#4504] opened 2021-06-08 13:10 UTC
Hello,
There is a weird behaviour with ggplot call changing LC_NUMERIC on a linux server. I have the exact same problem as [this 2018 post from PejoPhylo](https://stackoverflow.com/questions/53282219/ggplot-call-changes-locale-lc-numeric-variable) so I copy it here.

Thanks a lot for your work

---------

Starting a fresh R session and calling `sessionInfo()` gives

```
    R version 3.5.1 (2018-07-02) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Linux Mint 19

    Matrix products: default BLAS: /home/nicolai/anaconda3/lib/R/lib/libRblas.so LAPACK: /home/nicolai/anaconda3/lib/R/lib/libRlapack.so

    locale: [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C
    LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8
    LC_MONETARY=de_DE.UTF-8 [6] LC_MESSAGES=en_US.UTF-8
    LC_PAPER=de_DE.UTF-8 LC_NAME=C LC_ADDRESS=C
    LC_TELEPHONE=C [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C

    attached base packages: [1] stats graphics grDevices utils
    datasets methods base

    other attached packages: [1] RevoUtils_11.0.1 RevoUtilsMath_11.0.0

    loaded via a namespace (and not attached): [1] Rcpp_0.12.18
    assertthat_0.2.0 dplyr_0.7.6 crayon_1.3.4 R6_2.2.2
    grid_3.5.1 plyr_1.8.4 gtable_0.2.0 [9] magrittr_1.5
    scales_0.5.0 ggplot2_3.0.0 pillar_1.3.0 rlang_0.2.1
    lazyeval_0.2.1 rstudioapi_0.7 bindrcpp_0.2.2 [17] tools_3.5.1
    glue_1.3.0 purrr_0.2.5 munsell_0.5.0 yaml_2.2.0
    compiler_3.5.1 pkgconfig_2.0.1 colorspace_1.3-2 [25] tidyselect_0.2.4 bindr_0.1.1 tibble_1.4.2

```
Notice how LC_NUMERIC is set to C.

Typing 1.2 returns

```    1.2```

After calling the following two lines of code

```
library(ggplot2)
ggplot(data.frame(a=1:5, b=1:5), aes(a, b)) + geom_point()
```

My R-session mysteriously changes the decimal separator from a dot to a comma. Typing 1.2 returns

   ``` 1,2```

All plots I generate have the comma as the decimal separator. Calling sessionInfo() returns

```
    R version 3.5.1 (2018-07-02) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Linux Mint 19

    Matrix products: default BLAS: /home/nicolai/anaconda3/lib/R/lib/libRblas.so LAPACK: /home/nicolai/anaconda3/lib/R/lib/libRlapack.so

    locale: [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=de_DE.UTF-8
    LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 [5] LC_MONETARY=de_DE.UTF-8 LC_MESSAGES=en_US.UTF-8
    LC_PAPER=de_DE.UTF-8 LC_NAME=de_DE.UTF-8 [9] LC_ADDRESS=de_DE.UTF-8 LC_TELEPHONE=de_DE.UTF-8
    LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=de_DE.UTF-8

    attached base packages: [1] stats graphics grDevices utils
    datasets methods base

    other attached packages: [1] ggplot2_3.0.0 RevoUtils_11.0.1
    RevoUtilsMath_11.0.0

    loaded via a namespace (and not attached): [1] Rcpp_0.12.18
    rstudioapi_0.7 bindr_0.1.1 magrittr_1.5 tidyselect_0.2.4 munsell_0.5.0 colorspace_1.3-2 R6_2.2.2 [9] rlang_0.2.1
    plyr_1.8.4 dplyr_0.7.6 tools_3.5.1 grid_3.5.1
    gtable_0.2.0 withr_2.1.2 yaml_2.2.0 [17] lazyeval_0.2.1 assertthat_0.2.0 tibble_1.4.2 crayon_1.3.4 bindrcpp_0.2.2
    purrr_0.2.5 glue_1.3.0 labeling_0.3 [25] compiler_3.5.1 pillar_1.3.0 scales_0.5.0 pkgconfig_2.0.1
```

Notice how the LC_NUMERIC value has changed. I assume this causes the change in the decimal separator, but I have no idea how that makes sense.

This is something that happened after installing a fresh Mint version together with a fresh, up-to-date R version.

**Comment by yutannihilation** [comment] 2021-06-09 12:17
>     other attached packages: [1] RevoUtils_11.0.1 RevoUtilsMath_11.0.0

It seems it's not really fresh. Are you sure this is a problem that happens only when you use ggplot2? Do you see the same problem when you use base `plot()`?

**Comment by SamuelAllain** [comment] 2021-06-09 13:06
Thank you @yutannihilation for your message ! I checked and indeed this happens also with base `plot()`...

**Comment by yutannihilation** [comment] 2021-06-09 13:18
Oh, thanks for confirming. Then, let me close this issue as there doesn't seem to do on ggplot2's side. I'd recommend you to ask on [RStudio Community](https://community.rstudio.com) with a minimal reproducible example.

My guess is that some of your setup (either of `Reve*` packages, or Anaconda itself?) overwrites the original locale to "C" on startup, but, by some chance, it falls back to the original one. I'm thinking so because the author of the SO question you referred to commented that tweaking ".bashrc" fixed their problem. I think you need to do the similar thing (tweak ".bashrc", or ".Renviron"?)

**Closed by yutannihilation** 2021-06-09 13:18 UTC

**Comment by SamuelAllain** [comment] 2021-06-09 13:22
Ok thanks !
