### ISSUE TITLE
rlang_exec not found

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [tidyverse/ggplot2#3389] opened 2019-07-03 16:42 UTC
Getting some updates to `rlang` & `tidyverse`, I encountered this issue:
`gg` plots are no longer rendered. Instead, I get an error stating `rlang_exec` not found, and neither `rlang` (> 0.4.0) nor `ggplot2` export or define such function (or at least I failed to find one).
The source of the problem seems to reside in the [axis grob drawing function](https://github.com/tidyverse/ggplot2/blob/e2bdf85929603591387c2938625121b600f3e84d/R/guides-axis.r), lines 72-77.

---
Here is a reprex as executed on my system. The outputted plot is just an empty white page.

```r
library(ggplot2)
library(tidyverse)
plt <- mtcars %>% ggplot(aes(hp, mpg)) + geom_point()
plt
#> Error in exec(element_grob, line_element, `:=`(!!position_dim, unit(c(0, : object 'rlang_exec' not found
```

```
packageVersion("ggplot2")
#> [1] '3.2.0.9000'
packageVersion("rlang")
#> [1] '0.4.0.9000'
```

**Comment by yutannihilation** [comment] 2019-07-04 00:05
I cannot reproduce this. I think something is wrong with your rlang installation. Could you try re-installing rlang? (`rlang_exec` is C implementation inside `exec()`)

**Comment by Ilia-Kosenkov** [comment] 2019-07-04 21:50
I know it is something specific, I cannot reproduce it on another system either.
I will try to re-install `rlang` one more time.
I think it has something to do with the upgrade of `rlang` from pre `0.4.x` version to `0.4.x`.
Can it be caused by the fact I pulled all the packages from github rather than cran?

**Comment by Ilia-Kosenkov** [comment] 2019-07-04 22:07
Found the issue.
For some reason, while installing from github (`devtools::install_github("r-lib/rlang", force = TRUE)`), I missed this one line of the output:
```
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\rlang.dll to *my_path*\rlang.dll: Permission denied
```
Surprisingly, failure to copy the dll does not result in the installation error.
`ggplot` just happened to be the first package I used right after I finished the installation, hence the error.

I guess `rlang` is used at some point by `devtools`/`remotes` while installing, and therefore the library is in use.
I did a clean install from cran using `install.package` and everything works fine.

**Comment by yutannihilation** [comment] 2019-07-05 02:35
You can use `remotes::install_github()` on a fresh session. (c.f. https://yutani.rbind.io/post/a-survival-guide-to-install-rlang-from-github-on-windows/). Anyway I'm closing this as this doesn't seem a ggplot2's issue in any case. Thanks for confirming!

**Closed by yutannihilation** 2019-07-05 02:35 UTC
