### ISSUE TITLE
rstudio crashes directy on all ggplot calls

### ISSUE THREAD

**Issue by vanatteveldt** [tidyverse/ggplot2#4487] opened 2021-05-23 23:24 UTC
Since yesterday (presumably due to a system R version update), rstudio crashes whenever I used ggplot,
even without any data: 

```r
ggplot2::ggplot()  
```
It words fine in R in a terminal, but in RStudio this immediately causes the R session to crash.

<details>

I assumed it was a version issue so I tried the following:
- restarted R, reinstalled tidyverse and ggplot
- restarted computer, completely removed R (`apt-get remove --purge r-cran-* r-base-*`) and rstudio, deleted personal library folder, reinstalled R from rstudio PPA, reinstalled latest rstudio, reinstalled tidyverse
- tried to reinstall all ggplot dependencies:
```r
deps <- tools::package_dependencies("ggplot2", recursive = TRUE)$ggplot2
deps <- setdiff(deps, sessionInfo()$basePkgs)
for (dep in deps) try(install.packages(dep))
```
I tried running ggplot after each step, but keep getting the same crash.

I googled around for this problem and saw a number of (old) posts describing the same issue, but in each case reinstalling 

Sessioninfo and ubuntu version are below. The Rstudio log folder is empty. Please let me know if there is any other information I can provide:

```r
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(tidyverse)
── Attaching packages ──────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1
── Conflicts ─────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] forcats_0.5.1   stringr_1.4.0   dplyr_1.0.6     purrr_0.3.4    
[5] readr_1.4.0     tidyr_1.1.3     tibble_3.1.2    ggplot2_3.3.3  
[9] tidyverse_1.3.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       cellranger_1.1.0 pillar_1.6.1     compiler_4.1.0  
 [5] dbplyr_2.1.1     tools_4.1.0      jsonlite_1.7.2   lubridate_1.7.10
 [9] lifecycle_1.0.0  gtable_0.3.0     pkgconfig_2.0.3  rlang_0.4.11    
[13] reprex_2.0.0     cli_2.5.0        rstudioapi_0.13  DBI_1.1.1       
[17] haven_2.4.1      xml2_1.3.2       withr_2.4.2      httr_1.4.2      
[21] fs_1.5.0         generics_0.1.0   vctrs_0.3.8      hms_1.1.0       
[25] grid_4.1.0       tidyselect_1.1.1 glue_1.4.2       R6_2.5.0        
[29] fansi_0.4.2      readxl_1.3.1     modelr_0.1.8     magrittr_2.0.1  
[33] ps_1.6.0         backports_1.2.1  scales_1.1.1     ellipsis_0.3.2  
[37] rvest_1.0.0      assertthat_0.2.1 colorspace_2.0-1 utf8_1.2.1      
[41] stringi_1.6.2    munsell_0.5.0    broom_0.7.6      crayon_1.4.1    
> 
Save workspace image? [y/n/c]: n
nel@boi:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

</details>

**Comment by izu0421** [comment] 2021-05-23 23:27
Hi, I just installed R 4.1.0 and RStudio on a new ubuntu computer and I am having the same issue.

**Comment by yutannihilation** [comment] 2021-05-23 23:34
See this tweet. The issue is on RStudio's side and it's already fixed in the preview version.

https://twitter.com/kevin_ushey/status/1395054942088400905?s=20

I'll keep this issue open for a while, as the same issue is filed again and again...

**Comment by vanatteveldt** [comment] 2021-05-24 08:44
Thanks! I did search for the problem but didn't see anything recent, sorry for opening yet another issue!

**Comment by clauswilke** [comment] 2021-05-24 17:53
@vanatteveldt See #4485 #4486.

When searching for prior issues, make sure to also look at closed issues. GitHub by default only searches open issues, but that's usually not what you want when you're trying to see whether a particular topic has ever been brought up.

**Comment by fenguoerbian** [comment] 2021-05-26 02:15
If for any reason you can't downgrade R or install preview version of Rstudio, a possible temporary work around is to output the graph to another device, such as a .pdf file.

**Comment by yutannihilation** [comment] 2021-06-04 12:51
Just for information, the latest version of RStudio already contains the fix for this.

**Comment by vanatteveldt** [comment] 2021-06-04 12:53
Excellent, thanks all for the pointers. I have the preview version installed now and everything works like a charm. Thanks for the fantastic software! :)

**Comment by yutannihilation** [comment] 2021-06-26 10:09
Since it has been quiet here for weeks, I bet this is safe to close now.

**Closed by yutannihilation** 2021-06-26 10:09 UTC
