### ISSUE TITLE
world map with out axes

### ISSUE THREAD

**Issue by dominicroye** [tidyverse/ggplot2#3149] opened 2019-02-18 14:32 UTC
---
I'm trying to plot a world map with geom_sf, but the axes are not showing up. 

![rplot](https://user-images.githubusercontent.com/42300133/52957053-b82c7180-3388-11e9-85f1-4bdc7b653c6f.png)

```r
library(rnaturalearth)
library(sf)
library(ggplot2)
world <- ne_coastline(scale=10,returnclass = "sf")
ggplot(world)+geom_sf()+coord_sf()

```

Interesting is that with a country geom_sf does it well

![spain](https://user-images.githubusercontent.com/42300133/52957436-92ec3300-3389-11e9-9a5e-7535553fcf44.png)

```r
spain <- ne_countries(scale=10,country="Spain",returnclass = "sf")
ggplot(spain)+geom_sf()+coord_sf()
```

```
packages:
sf_0.7-3
ggplot2_3.1.0.9000

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo              
```

**Comment by yutannihilation** [comment] 2019-02-18 14:45
Thanks, this seems a duplicate of #2985. If you specify `expand = FALSE`, the axis labels should show up.

``` r
ggplot(world) + geom_sf() + coord_sf(expand = FALSE)
```

**Comment by dominicroye** [comment] 2019-02-18 14:51
Ok. I didn't saw this issue! Perfect with expand=FALSE it is solved.  Thanks

**Closed** 2019-02-18 14:51 UTC
