### ISSUE TITLE
[Request] Better breaks in log10 scale

### ISSUE THREAD

**Issue by gilleschapron** [tidyverse/ggplot2#2371] opened 2017-12-13 10:53 UTC
I know there is `annotation_logticks()` that can do the trick, but, for my plots in log10 scale, I think it's could look better to adjust major and minor breaks to this particular scale. Exemple.
![capture](https://user-images.githubusercontent.com/10176335/33935163-3dbb4d86-dffb-11e7-8501-d6f954487785.JPG)
So there is my proposal to do that (found a long time ago, don't remember where, and ajusted) :
```r
log10_major_breaks <- function(...) {
  function(x) {
    minx <- floor(min(log10(x), na.rm = T)) - 1
    maxx <- ceiling(max(log10(x), na.rm = T)) + 1
    n_major <- maxx - minx + 1
    major_breaks <- seq(minx, maxx, by = 1)
    return(10 ^ (major_breaks))
  }
}

log10_minor_breaks <- function(...) {
  function(x) {
    minx <- floor(min(log10(x), na.rm = T)) - 1
    maxx <- ceiling(max(log10(x), na.rm = T)) + 1
    n_major <- maxx - minx + 1
    major_breaks <- seq(minx, maxx, by = 1)
    minor_maj <- rep(log10(seq(1, 9, by = 1)), times = n_major) +
                 rep(major_breaks, each = 9)
    minor_breaks <- minor_maj[!(minor_maj %in% major_breaks)]
    return(10 ^ (minor_breaks))
  }
}
```
What do you think about add this to ggplot?

**Comment by ptoche** [comment] 2017-12-13 16:50
Could you add a fully reproducible example, with data and all, plus a verbal description of the purpose?

**Comment by hadley** [comment] 2017-12-13 17:34
Duplicate of https://github.com/hadley/scales/issues/100 — I think the problem is relatively obvious, the challenge is automating the solution so that it works with a variety of ranges.

**Closed by hadley** 2017-12-13 17:34 UTC
