### ISSUE TITLE
No legend with trans = log10 for certain fill/color values 

### ISSUE THREAD

**Issue by Henrik-P** [tidyverse/ggplot2#2295] opened 2017-10-14 15:26 UTC
When using `trans = "log10"`, the legend is not rendered for certain `fill` (`color`) values. In this example, no legend appears when using "z1" in `aes`, but it works fine with "z2".

``` r
d <- read.table(text = "x y   z1   z2
1 1 4 0.31 0.30
2 1 3 0.42 0.10
3 1 2 0.71 0.15
4 1 1 0.59 0.18
5 2 4 0.32 0.18
6 2 3 0.45 0.34
7 2 2 0.64 0.26", 
  header = TRUE)


library(ggplot2)


# fill = z1
p <- ggplot(d, aes(x = x, y = y, fill = z1)) + geom_point(pch = 21, size = 10)

# no legend generated
p + scale_fill_continuous(trans = "log10")
```

![](https://i.imgur.com/sIPTJUV.png)

``` r
# no legend generated
# p + scale_fill_gradientn(colours = terrain.colors(10), trans = 'log10')
# p + scale_fill_gradient2(trans = 'log10')
# p + scale_fill_distiller(trans = 'log10')
# p + scale_fill_gradient(trans = 'log10')


# similarly, for color = z1
p <- ggplot(d, aes(x = x, y = y, color = z1)) + geom_point(size = 10)

# no legend generated
# p + scale_color_continuous(trans = 'log10')
# p + scale_color_gradientn(colours = terrain.colors(10), trans = 'log10')
# p + scale_color_gradient2(trans = 'log10')
# p + scale_color_distiller(trans = 'log10')
# p + scale_color_gradient(trans = 'log10')
```

On the other hand, when using values from "z2" in `aes`, a legend is generated for all kinds of `scale_fill` and `scale_color`

``` r
# fill = z2
p <- ggplot(d, aes(x = x, y = y, fill = z2)) + geom_point(pch = 21, size = 10)

# legend generated
# p + scale_fill_continuous(trans = "log10")
# p + scale_fill_gradientn(colours = terrain.colors(10), trans = "log10")
# p + scale_fill_gradient2(trans = "log10")
# p + scale_fill_gradient(trans = "log")

# color = z2
# p <- ggplot(d, aes(x = x, y = y, color = z2)) +
#  geom_point(size = 10)

# p + scale_color_continuous(trans = "log10")
# p + scale_color_gradientn(colours = terrain.colors(10), trans = "log10")
# p + scale_color_gradient2(trans = "log10")
# p + scale_color_gradient(trans = "log")

```

--------

I first saw the issue in this SO post: [scale_fill_distiller ggplot legend missing for some data frames but not others](https://stackoverflow.com/questions/46744653/scale-fill-distiller-ggplot-legend-missing-for-some-data-frames-but-not-others)

**Comment by hadley** [comment] 2017-10-31 15:44
Basically a duplicate of #2269, which became https://github.com/hadley/scales/issues/100

**Closed by hadley** 2017-10-31 15:44 UTC
Labels: bug, scales
