### ISSUE TITLE
Ordering of label placement with `geom_text()` depends on whether or not a group aesthetic is set

### ISSUE THREAD

**Issue by TimTeaFan** [tidyverse/ggplot2#3612] opened 2019-11-04 21:45 UTC
When creating a stacked bar chart and the `fill` argument is not placed in the initial ggplot call, but in the `aes` of `geom_bar`, the label order of `geom_text` is displayed in reverse order. This behavior can be prevented, when adding `fill` to the `aes` of `geom_text`, however, this produces a warning saying ...

> Ignoring unknown aesthetics: fill

... which is not really correct, since this unknown aesthetics still has some effect on the final plot.

I posted this on [SO](https://stackoverflow.com/questions/58667035/reverse-label-ordering-when-passing-variable-in-geom-baraes-instead-of-ggplo/58674126#58674126) and Claus Wilke found out that the issue is related to grouping. Once the fill variable is added to `geom_text(... group = ...)` labels are displayed in correct order.

I see two possible issues here:

1. Is the reverse label order intended, when calling `fill` in the `aes` of `geom_bar` (and without adding the fill variable to `group` in `geom_text`)? Why is the default labeling in reverse order?
2. Might the warning when providing `fill` to `aes` in `geom_bar` be misleading, since it still has an effect on the plot?

 
A short example:
```r
library(dplyr)
library(ggplot2)

# some toy data
data <- tibble(Category = c("Baseball",
                            "Basketball",
                            "Football",
                            "Hockey"),
               n = c(45,10,25,20)) 

  # fill is provided to the initial ggplot call - labels are in correct order
  ggplot(data, aes (x="", y = n, fill = Category)) +
    geom_bar(width = 1, stat = "identity") +
    geom_text(aes(label = paste(n, "%")),
            position = position_stack(vjust = 0.5))

   # fill is provided to geom_bar - labels are in reverse order
  ggplot(data, aes (x="", y = n)) +
    geom_bar(aes(fill = Category), width = 1, stat = "identity") +
    geom_text(aes(label = paste(n, "%")),
              position = position_stack(vjust = 0.5))

  # fill is provided to aes in geom_text - yields warning, but labels are in correct order
  ggplot(data, aes (x="", y = n)) +
  geom_bar(aes(fill = Category), width = 1, stat = "identity") +
  geom_text(aes(fill = Category, label = paste(n, "%")),
          position = position_stack(vjust = 0.5))
  #> Warning: Ignoring unknown aesthetics: fill

  # fill variable is provided to group in geom_text - labels are in correct order
  ggplot(data, aes (x="", y = n)) +
    geom_bar(aes(fill = Category), width = 1, stat = "identity") +
    geom_text(aes(label = paste(n, "%"), group = Category),
              position = position_stack(vjust = 0.5))

```

**Comment by batpigandme** [comment] 2019-11-04 21:58
Rendered with reprex:

``` r
library(dplyr)
library(ggplot2)

# some toy data
data <- tibble(Category = c("Baseball",
                            "Basketball",
                            "Football",
                            "Hockey"),
               n = c(45,10,25,20)) 

# fill is provided to the initial ggplot call - labels are in correct order
ggplot(data, aes (x="", y = n, fill = Category)) +
  geom_bar(width = 1, stat = "identity") +
  geom_text(aes(label = paste(n, "%")),
            position = position_stack(vjust = 0.5))
```

![](https://i.imgur.com/Kgus1hI.png)

``` r

# fill is provided to geom_bar - labels are in reverse order
ggplot(data, aes (x="", y = n)) +
  geom_bar(aes(fill = Category), width = 1, stat = "identity") +
  geom_text(aes(label = paste(n, "%")),
            position = position_stack(vjust = 0.5))
```

![](https://i.imgur.com/Wj9HxYA.png)

``` r

# fill is provided to aes in geom_text - yields warning, but labels are in correct order
ggplot(data, aes (x="", y = n)) +
  geom_bar(aes(fill = Category), width = 1, stat = "identity") +
  geom_text(aes(fill = Category, label = paste(n, "%")),
            position = position_stack(vjust = 0.5))
#> Warning: Ignoring unknown aesthetics: fill
```

![](https://i.imgur.com/j4JS4FA.png)

``` r
#> Warning: Ignoring unknown aesthetics: fill

# fill variable is provided to group in geom_text - labels are in correct order
ggplot(data, aes (x="", y = n)) +
  geom_bar(aes(fill = Category), width = 1, stat = "identity") +
  geom_text(aes(label = paste(n, "%"), group = Category),
            position = position_stack(vjust = 0.5))
```

![](https://i.imgur.com/vhcZld4.png)

<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment] 2019-11-04 22:35
To be clear: The `fill` aesthetic is irrelevant here, it just happens to have a side effect on the `group` aesthetic. The question is: Why does the behavior of `geom_text()` depend on whether or not there's a group aesthetic set in this example, and is this behavior as intended or not?

**Comment by yutannihilation** [comment] 2019-11-04 22:56
I'm sure this is intended. If a data contains groups, ordering should be determined based on the group to ensure the all data is stacked in the same order at every X value.

**Comment by clauswilke** [comment] 2019-11-05 05:26
@yutannihilation Feel free to close this issue if you think it's all as expected.

**Comment by yutannihilation** [comment] 2019-11-05 07:01
Hmm, I'm just saying this should be intended. I agree this looks unexpected so it's nice if we can improve this. For reference, the ordering probably happens here:

https://github.com/tidyverse/ggplot2/blob/3870c12e51f2a57666045ce73c3dbc55f19137e7/R/position-collide.r#L39-L45

**Comment by yb2125** [comment] 2020-05-11 18:21
If you order data by category before plotting the chart, the error message will not appear.

**Comment by teunbrand** [comment] 2023-11-13 15:07
> Why does the behavior of geom_text() depend on whether or not there's a group aesthetic set in this example, and is this behavior as intended or not?

I don't think this is a `geom_text()` issue, setting a group in `geom_text()` might (not 100% sure) affect the drawing order, but not the position. The issue is with `position_stack()`. If we read the issue title as "Ordering of placement with `position_stack()` depends on whether or not a group aesthetic is set", then it reads as if the current behaviour is correct (which I think it is).

Unless we start sharing information between layers, which we don't on purpose, I don't think there is a lot to improve here. As such, I'll close this issue but we can always re-open if someone disagrees.

**Closed by teunbrand** 2023-11-13 15:08 UTC
Labels: positions :1st_place_medal:
