### ISSUE TITLE
`coord_polar` causes error with `ggtext::element_markdown`

### ISSUE THREAD

**Issue by mevers** [tidyverse/ggplot2#4080] opened 2020-06-22 00:07 UTC
Originally reported as a [`ggtext` issue here](https://github.com/wilkelab/ggtext/issues/42) I was advised by @clauswilke  to flag this here as well.

Using `coord_polar` with `ggtext::element_markdown` to theme x-axis labels causes an error 

> Error in grid.Call.graphics(C_setviewport, vp, TRUE) :
  non-finite location and/or size for viewport

with the plot still drawn correctly.

----

A minimal & reproducible example:

```r
df <- data.frame(name = sprintf("**%s**", LETTERS[1:4]), value = 1:4)

library(ggplot2)
library(ggtext)

ggplot(df, aes(name, value)) +
    geom_point() +
    coord_polar() +
    theme(axis.text.x = element_markdown())
```

Removing `coord_polar` gets rid of the error.

**Comment by clauswilke** [comment] 2020-06-22 00:30
With a quick glance at the relevant code, I suspect it's caused by this line here:
https://github.com/tidyverse/ggplot2/blob/73256c91e4d97e8c507206de9d3213bb64fa84af/R/coord-polar.r#L190
It is trying to draw an empty axis by supplying `NA` as break position. Maybe `element_markdown()` needs to be able to handle that, in which case this would be a ggtext bug, not a ggplot2 bug. Still thinking about it.

**Comment by thomasp85** [comment] 2020-08-31 11:15
`NA` should be supported so I'm closing this here

**Closed by thomasp85** 2020-08-31 11:15 UTC
