### ISSUE TITLE
geom_text puts "a" on labels

### ISSUE THREAD

**Issue by fostvedt** [tidyverse/ggplot2#3167] opened 2019-02-26 22:31 UTC
---

When i try to use geom_text() with color, the label/legend/key shows the letter "a" unless I add the option "show.legend=F".

I am using R 3.4.1 and ggplot2_3.0.0

```r
p <- ggplot(mtcars, aes(wt, mpg, label = rownames(mtcars)))
# mysterious letter "a" in the legend
p+  geom_text(aes(colour = factor(cyl)))
# no letter "a", but also no legend
p+  geom_text(aes(colour = factor(cyl)),show.legend=F)
```

**Comment by jemus42** [comment] 2019-02-26 22:58
As far as I know, this is intended behavior – or at least behavior that's been around for so long that I have to assume that someone would have changed it if it was not intentional. See also the examples on https://ggplot2.tidyverse.org/reference/geom_text.html#examples (you'll need to scroll down a bit to see examples with legends)

The letter "a" in the legend key just indicates that there is a text `geom`. There is currently a proposed change about making the legend key glyphs configurable (which would give you exact control over what is displayed instead of the "a") at https://github.com/tidyverse/ggplot2/issues/3145

For now though, I think your best bet is doing what you're already doing: Hide the legend for text `geom`s.

**Comment by clauswilke** [comment] 2019-02-26 23:07
Yes, I've never been a fan of the text legends, but that's how they currently are. I'm closing this since #3145 covers the same topic. You can also use the example code in #3145 to implement a version of `geom_text()` that uses a different legend glyph.

**Closed by clauswilke** 2019-02-26 23:07 UTC
