### ISSUE TITLE
geom_bar with ymin and ymax switches to horizontal

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#3966] opened 2020-04-26 14:12 UTC
When `ymin` and `ymax` aesthetics are provided to `geom_bar(stat="identity")`, the orientation switches from vertical to horizontal.  I would have expected it to ignore `ymin` and `ymax` and for the figures to be identical.

``` r
library(ggplot2)

d_plot <-
  data.frame(
    x=1:3,
    y=4:6,
    ymin=3:5,
    ymax=5:7
  )

ggplot(d_plot) +
  geom_bar(aes(x=x, y=y), stat="identity")
```

![](https://i.imgur.com/r48PKwi.png)

``` r

ggplot(d_plot) +
  geom_bar(aes(x=x, y=y, ymin=ymin, ymax=ymax), stat="identity")
#> Warning: Ignoring unknown aesthetics: ymin, ymax
```

![](https://i.imgur.com/PEpPQsW.png)

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment] 2020-04-27 00:31
Thanks, but this is duplicate of #3866 and is already fixed by #3882 on the current master.

**Closed by yutannihilation** 2020-04-27 00:31 UTC
