### ISSUE TITLE
geom_polygon accessing data$y

### ISSUE THREAD

**Issue by JTapper** [tidyverse/ggplot2#2133] opened 2017-05-15 14:08 UTC
When creating a new Geom that inherits GeomPolygon any attempt to access data$y returns NA.

This can be recreated by adding str(data) to the draw_panel function of the new Geom. 
any other aesthetic is visible, but data$y is always NA. If I rename the aesthetic to y1 the value is returned.

**Comment by karawoo** [comment] 2017-05-24 18:42
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by karawoo** [comment] 2017-06-27 21:43
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by karawoo** 2017-06-27 21:43 UTC
Labels: reprex
