### ISSUE TITLE
qplot() ylab behavior changed, now defaults to NULL

### ISSUE THREAD

**Issue by rafalab** [tidyverse/ggplot2#3467] opened 2019-08-02 18:18 UTC
---

With version 3.2.0 qplot, with histogram or density geometries, uses the character `NULL` as the y label. Previous versions showed nothing. 

Update: The difference in behavior seems to be due to the argument  `.ignore_empty="all"` in the call to `enquos`.

```r
set.seed(2009)
x <- rnorm(100)
qplot(x, geom="histogram")
```

![Rplot](https://user-images.githubusercontent.com/5330134/62390544-90912600-b530-11e9-99ba-7fc7f1f7c0d2.png)

**Comment by yutannihilation** [comment] 2019-08-05 00:31
Thanks, confirmed. As you say, it seems this used to work before #2936, sorry...

``` r
packageVersion("ggplot2")
#> [1] '3.1.1'

library(ggplot2)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang

set.seed(2009)
x <- rnorm(100)
qplot(x, geom="histogram")
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/fU4LTji.png)

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment] 2019-08-05 10:02
Now I feel both are wrong; shouldn't the label be `count`, the same as `ggplot() + geom_histogram()`...?

**Comment by rafalab** [comment] 2019-08-05 12:11
I agree. 

`qplot(x, geom="histogram")` should be the same as `ggplot(aes(x=x), data=data.frame(x=x))+geom_histogrram()`

`qplot(x, geom="density")` should be the same as `ggplot(aes(x=x),data=data.frame(x=x))+geom_density()`

`qplot(sample=x)` should be the same as `ggplot(aes(sample=x),data=data.frame(x=x))+stat_qq()`

an so on. 

But the previous behavior of showing nothing is preferable than writing out `NULL`.

**Comment by yutannihilation** [comment] 2019-08-06 09:28
@thomasp85 This is an unexpected change introduced in v3.2.0 (due to my carelessness, sorry...). Do you think reverting this needs to be included in v3.2.1? If so, it would be easy to revert the [related changes](https://github.com/tidyverse/ggplot2/pull/2936/files#diff-7c50e6483f96a34bf461315f0d5e818d), though it's not a true fix.

**Comment by thomasp85** [comment] 2019-08-06 09:29
I think we should include it... can you make a PR?

**Comment by yutannihilation** [comment] 2019-08-06 09:33
Sure, I will send PRs to master and to v3.2.1-rc.

**Comment by thomasp85** [comment] 2019-08-06 09:34
just to v3.2.1-rc... It will be merged into master once released

**Comment by yutannihilation** [comment] 2019-08-06 09:37
Ah, thanks. I got it.

**Closed** 2019-08-12 13:41 UTC
