### ISSUE TITLE
log10 transformation gives the wrong scales with geom_bar

### ISSUE THREAD

**Issue by nicolerg** [tidyverse/ggplot2#4751] opened 2022-03-04 18:17 UTC
Hello, 

When there is more than one entry per x value for geom_bar, `scale_y_continuous(trans="log10")` (or equivalently `scale_y_log10()`) labels the y-axis incorrectly. In this example, the max value should be 5e3, but the axis label goes up to 1e7. 

Expected behavior with simple data:
```r
df = data.frame(x=1:5, y=c(2, 20, 200, 400, 5000))

ggplot(df, aes(x=factor(x), y=y)) +
  geom_bar(stat="identity") +
  theme_classic() +
  scale_y_continuous(trans="log10") 
```
![simple](https://user-images.githubusercontent.com/32148717/156818829-e59a5a33-718b-441a-b21c-c9d75bf4d736.png)

Bug with more complex data: 
```r
df = data.frame(x=rep(1:5, 2),
                y=rep(c(1, 10, 100, 200, 2500),2), 
                group=rep(letters[1:5], each=2))

ggplot(df, aes(x=factor(x), y=y)) +
  geom_bar(stat="identity") +
  theme_classic() +
  scale_y_continuous(trans="log10") 
```
![log10](https://user-images.githubusercontent.com/32148717/156818397-89ea3c76-42db-491c-80b9-50b5aed5c914.png)

It is also a bit odd that the log10 transformation seems to be applied per entry, i.e. there is a total value of 2 for x==1, but it shows up as 0 because log10(1) + log10(1) = 0, whereas I would expect it to show log10(1+1). 

This is with `ggplot2_3.3.5`.

**Comment by yutannihilation** [comment] 2022-03-05 02:43
Thanks for reporting. I also confirmed with the dev version. It seems the labels gets squared for unknown reason...

``` r
library(ggplot2)

df <- data.frame(
  x = rep(1:5, 2),
  y = rep(c(1, 10, 100, 200, 2500), 2),
  group = rep(letters[1:5], each = 2)
)

b <-  10 ^ (1:7)

ggplot(df, aes(x = factor(x), y = y)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = b, colour = alpha("red", 0.5)) +
  theme_classic() +
  scale_y_continuous(trans = "log10", breaks = b, labels = scales::label_comma())
```

![](https://i.imgur.com/ihYkOIz.png)

``` r
label_tweak <- function(x) {
  x <- sqrt(x)
  scales::label_comma()(x)
}

ggplot(df, aes(x = factor(x), y = y)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = b, colour = alpha("red", 0.5)) +
  theme_classic() +
  scale_y_continuous(trans = "log10", breaks = b, labels = label_tweak)
```

![](https://i.imgur.com/MXn86db.png)

<sup>Created on 2022-03-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by teunbrand** [comment] 2022-03-05 07:27
I think what is going on is the same as in #4731, in that the stacking is applied after log-transforming the values, giving effective `log(a) + log(b) == log(a * b)` instead of `log(a + b)`.

``` r
library(ggplot2)

df <- data.frame(
  x = rep(1:5, 2),
  y = rep(c(1, 10, 100, 200, 2500), 2),
  group = rep(letters[1:5], each = 2)
)

b <-  10 ^ (1:7)

p <- 
ggplot(df, aes(x = factor(x), y = y, fill = factor(seq_along(x)))) +
  scale_y_continuous(trans = "log10")

p + geom_bar(stat = "identity", position = "stack")
```

![](https://i.imgur.com/gfz1UqL.png)

``` r
p + geom_bar(stat = "identity", position = "dodge")
```

![](https://i.imgur.com/sccEeGX.png)

<sup>Created on 2022-03-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment] 2022-03-05 09:59
Ah, thanks for the explanation. Sorry I didn't (and don't) have enough time to read and understand #4731. Closing this as this seems a duplicate of #4731.

**Closed by yutannihilation** 2022-03-05 09:59 UTC

**Comment by fwaegena** [comment] 2024-10-10 08:19
How to solve it if you want to have a stack barplot with an y scale log transformed?

**Comment by teunbrand** [comment] 2024-10-10 08:38
We discourage stacking a plot with non-linear transformation of the scale.
From `?position_stack`:

> Because stacking is performed after scale transformations, stacking with non-linear scales gives distortions that easily lead to misinterpretations of the data. It is therefore discouraged to use these position adjustments in combination with scale transformations, such as logarithmic or square root scales.

I recommend dodging instead.

**Comment by clauswilke** [comment] 2024-10-10 16:45
@fwaegena In most cases, bar plots with a y log scale are a bad idea anyways (even though they are widely used in microbiology), because the bar length can never accurately reflect the data values. The bars are infinitely long. This is discussed here: https://clauswilke.com/dataviz/proportional-ink.html#visualizations-along-logarithmic-axes
