### ISSUE TITLE
the colname of dataframe start with number, <text>:1:3: unexpected numeric constant

### ISSUE THREAD

**Issue by Asa12138** [tidyverse/ggplot2#5213] opened 2023-03-01 07:16 UTC
I like to use a loop to draw ggplot for each column, early, no matter what colnames I use, it runs well.
But recently, I found a `<text>:1:3: unexpected numeric constant `error.

A little test:
```
library(ggplot2)
test=data.frame("a"=runif(5),"1b"=runif(5),check.names = F)
ggplot(test,aes_string(x="a"))+geom_density()
ggplot(test,aes_string(x="1b"))+geom_density()
```
I am sure `ggplot(test,aes_string(x="1b"))+geom_density()` can work well previously.

Also in `ggpubr`
```
ggdensity(test,x="1b")
```

the full error is:
```
Error in `purrr::pmap()`:
ℹ In index: 1.
ℹ With name: density.
Caused by error in `purrr::map()`:
ℹ In index: 1.
ℹ With name: x.
Caused by error in `parse()`:
! <text>:1:2: unexpected symbol
1: 1b
     ^
Run `rlang::last_error()` to see where the error occurred.
```

Is this a version error? 
```
sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.0.1

 ggpubr_0.5.0       ggplot2_3.4.0   
```
I have try R4.1.0 but the error still here.

**Comment by yutannihilation** [comment] 2023-03-02 15:23
Confirmed, but I'm not sure if the previous behavior was correct because `1b` is not a valid variable name. This works:

``` r
ggplot(test, aes_string(x="`1b`"))+geom_density()
```

Anyway, as you see the warning, `aes_string()` is now deprecated. Please use `aes(.data[[col]])` instead.

ref: https://ggplot2.tidyverse.org/reference/aes_.html#life-cycle

**Comment by Asa12138** [comment] 2023-03-02 15:43
@yutannihilation Thank you for your reply!
I know that aes_string() is now deprecated. 
But sometimes I need to use a loop plot every column in a dataframe like:
```
library(ggplot2)
test=data.frame("a"=runif(5),"1b"=runif(5),"c"=runif(5),check.names = F)
plotls=list()
for (i in colnames(test)){
  plotls[[i]]=ggplot(test,aes_string(x=i))+geom_density()
}

```
I like this usage but now it can not work 😭, use '``' is not allowed in loop.
I wonder is any other way to achieve this and do not need to change the colnames or `facet`.

**Comment by yutannihilation** [comment] 2023-03-02 16:16
Ah, okay. Sorry, I was a bit confused. I thought you are arguing this used to work in some previous version. Unfortunately, `aes_string(x = "1b")` never works because what you provide is an expression, not a column name. To make it a valid expression, you need to wrap it with `` ` ``.

I think I would use `pivot_longer()` first, but you might get better result on [Posit Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests. I'm closing this as this is not a bug, thanks!

**Closed by yutannihilation** 2023-03-02 16:16 UTC
