### ISSUE TITLE
Bad colour doesn't make error

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#3762] opened 2020-01-27 19:33 UTC
e.g. 

```R
ggplot(bechdel) + 
    geom_point(mapping = aes(x = budget, y = domgross), color="blasdfsdafaue")
```

**Comment by thomasp85** [comment] 2020-01-27 22:16
Please provide a reproducible example😛

I’m afraid this will end up being needlessly expensive and also hard to implement due to the lack of a proper colour vector format. We basically don’t know which aesthetics are to be interpreted as a colour (because extensions might add new ones). This should be handled by the graphic engine though, I think

**Comment by hadley** [comment] 2020-01-28 03:54
This was just a quick note while teaching — the weird thing is that there’s no warning or message, you just get transparent points.

**Comment by yutannihilation** [comment] 2020-01-28 04:18
I see bad color does make error (probably raise by `farver::decode_colour()`?). Maybe they used some old version of scales?

``` r
library(ggplot2)

ggplot(mpg) + 
  geom_point(mapping = aes(x = cyl, y = cty), color = "blasdfsdafaue")
#> Error: Unknown colour name: blasdfsdafaue
```

**Comment by yutannihilation** [comment] 2020-01-28 06:17
> Maybe they used some old version of scales?

Sorry, not scales, but farver. It's only since a few weeks ago that the CRAN version of farver raise error for invalid colour names c.f. https://github.com/tidyverse/ggplot2/issues/3712 . Anyway I think we can close this issue now.

**Comment by hadley** [comment] 2020-01-28 13:57
Thanks for the investigation @yutannihilation!

**Closed** 2020-01-28 13:57 UTC

**Comment by yutannihilation** [comment] 2020-01-28 15:30
I just happened to remember I've seen a similar issue recently, but I'm glad to have helped you :)
