### ISSUE TITLE
geom_histogram + xlim causes first bar to disappear

### ISSUE THREAD

**Issue by jpritikin** [tidyverse/ggplot2#3332] opened 2019-05-16 15:40 UTC
ggplot2 3.1.1

```r
library(ggplot2)

set.seed(1)
v <- c(rep(0,10), sample.int(250, 100, replace=TRUE), rep(250,10))
qplot(v, geom="histogram", binwidth=4)  # good

# Here we lose the first bar
qplot(v, geom="histogram", binwidth=4) + xlim(0,250)
qplot(v, geom="histogram", binwidth=4) + xlim(-1,250)
```

![Good output](https://user-images.githubusercontent.com/2002771/57867523-4e790380-77cf-11e9-8f4a-588fafb4e7c3.png)

![Bad output](https://user-images.githubusercontent.com/2002771/57867484-3c976080-77cf-11e9-8f4b-5534a13d7905.png)

**Comment by clauswilke** [comment] 2019-05-16 15:58
Duplicate of #2887.

**Closed by clauswilke** 2019-05-16 15:58 UTC
