### ISSUE TITLE
scale_..._binned doubles width of lowest and highest bin when setting limits

### ISSUE THREAD

**Issue by tjebo** [tidyverse/ggplot2#4100] opened 2020-06-27 16:35 UTC
I hope the issue title makes this issue already clear?  When setting limits in scale_..._binned, the upper and lower bins double in size. See below example.
This behaviour changes when setting `even.steps = FALSE`, and this makes sense. But I guess this should even more so be the case when setting even.steps = TRUE... -  one should even more so get "fully even steps" ... ?
``` r
library(ggplot2)

mybreaks = c(0,50,100,200,400)

ggplot(mtcars, aes(mpg, disp, fill = hp)) +
  geom_point(shape = 21) +
  scale_fill_fermenter(limits = c(0, 400))
```

![](https://i.imgur.com/wyf459F.png)

``` r
ggplot(mtcars, aes(mpg, disp, fill = hp)) +
  geom_point(shape = 21) +
  scale_fill_fermenter(
    limits = c(0, 400),
    guide = guide_colorsteps(even.steps = FALSE)
  )
```

![](https://i.imgur.com/yTU42WN.png)

``` r
ggplot(mtcars, aes(mpg, disp, fill = hp)) +
  geom_point(shape = 21) +
  scale_fill_fermenter(limits = c(0, 400), breaks = mybreaks)
```

![](https://i.imgur.com/prJIp8g.png)

``` r
ggplot(mtcars, aes(mpg, disp, fill = hp)) +
  geom_point(shape = 21) +
  scale_fill_fermenter(
    limits = c(0,400), 
    breaks = mybreaks,
    guide = guide_colorsteps(even.steps = FALSE)
    )
```

![](https://i.imgur.com/oP5Nl6o.png)

<sup>Created on 2020-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment] 2020-06-28 05:36
Thanks, seems a duplicate of #4019. Currently you need to expand the limit for a little to get a pretty legend. I agree the behaviour is not desired.

``` r
library(ggplot2)

mybreaks = c(0,50,100,200,400)

ggplot(mtcars, aes(mpg, disp, fill = hp)) +
  geom_point(shape = 21) +
  scale_fill_fermenter(limits = c(-0.1, 400.1))
```

![](https://i.imgur.com/sMavm2Q.png)

<sup>Created on 2020-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed by yutannihilation** 2020-06-28 05:36 UTC
