### ISSUE TITLE
Error in UseMethod(“margin”): no applicable method for 'margin' applied to an object of class "c('double', 'numeric')"

### ISSUE THREAD

**Issue by aelwan** [tidyverse/ggplot2#2150] opened 2017-06-05 00:41 UTC
I have asked the [same question on SO](https://stackoverflow.com/questions/44353402/ggplot2-error-in-usemethodmargin?noredirect=1&lq=1). The only difference is the reproducible example. 

I have a problem with the margin
Following this [answer](https://stackoverflow.com/a/14487264/5420677), if I try 
```
ggplot(mpg, aes(cty, hwy)) + geom_point()+
  theme(axis.title.y=element_text(margin=margin(0,20,0,0)))
```
I got this error 

> Error in UseMethod("margin") : 
>   no applicable method for 'margin' applied to an object of class "c('double', 'numeric')"
 
I will appreciate any suggestions how to fix it.

**Comment by karawoo** [comment] 2017-06-13 17:43
The SO question you linked is now gone, and the code from the other answer works for me with ggplot2 version 2.2.1.9000. If you're still having a problem, can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!

If you need help creating a reprex, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by karawoo** [comment] 2017-06-27 21:44
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by karawoo** 2017-06-27 21:44 UTC
Labels: reprex

**Comment by pmarchand1** [comment] 2017-10-23 17:48
I had the exact same issue and realized it was due to the ggplot "margin" function being overridden by a synonymous function from randomForest. I realize this is an old issue but adding a note in case some people Google the error.

**Comment by Dilini-Sewwandi-Rajapaksha** [comment] 2018-02-24 01:31
Could you please tell me the way that you solve this problem

**Comment by jlab87** [comment] 2018-02-28 13:47
To avoid the interaction with the randomForest package, use specify that the margin function you want comes from the ggplot2 library. For example:

`axis.title.x = element_text(margin = ggplot2::margin(0,20,0,0))`

**Comment by Dilini-Sewwandi-Rajapaksha** [comment] 2018-02-28 21:11
It worked. Thank you soo much :) :) :) :D
