### ISSUE TITLE
segmentation fault with ggsave running in Rscript

### ISSUE THREAD

**Issue by FantacticMisterFox** [tidyverse/ggplot2#3667] opened 2019-12-13 12:05 UTC
When calling the following R-script I get a segmentation fault.
No problem from RStudio

---

```r
library(ggplot2)

p <- ggplot(mtcars, aes(wt, mpg))
p + geom_point()
ggsave("test.jpg", plot = last_plot(), device = "jpeg", path = "./")
```
```

 *** caught segfault ***
address 0xfffffffffffffff0, cause 'memory not mapped'

Traceback:
 1: .Call("plyr_split_indices", PACKAGE = "plyr", group, n)
 2: plyr::split_indices(scale_id, n)
 3: scale_apply(layer_data, x_vars, "train", SCALE_X, panel$x_scales)
 4: train_position(panel, data, scale_x(), scale_y())
 5: ggplot_build(x)
 6: print.ggplot(x)
 7: (function (x, ...) UseMethod("print"))(x)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
```
```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)
```

**Comment by yutannihilation** [comment] 2019-12-18 08:45
```
    Traceback:
     1: .Call("plyr_split_indices", PACKAGE = "plyr", group, n)
    ```

Though I'm not sure about the detail, this traceback indicates the cause can be related to the compilation code of plyr. If so, you won't see this error anymore if you use the dev version of ggplot2, which now works without plyr.

**Comment by yutannihilation** [comment] 2020-01-07 11:18
Though I still don't know about the cause, I believe this won't happen after the upcoming release. Closing now.

**Closed by yutannihilation** 2020-01-07 11:18 UTC

**Comment by yutannihilation** [comment] 2020-01-07 11:39
(Correction: plyr-dependencies should have been removed at version 3.2.0.)
