### ISSUE TITLE
Inconsistent geom_bar width with drop = FALSE

### ISSUE THREAD

**Issue by balling-dev** [tidyverse/ggplot2#5639] opened 2024-01-12 13:55 UTC
Thanks for ggplot2.

I am observing what I believe is a bug (unexpected behaviour) in the calculation of geom_bar width depending on what data is plotted when unused factor levels are not dropped.

Consider the following plot with unused factor levels. Plotting only the first two rows of data yields an unexpected bar width:

```R
library(ggplot2)
d <- structure(list(
  id = structure(c(2L, 5L, 6L), levels = c("A","B", "C", "D", "E", "F"), class = c("ordered", "factor")),
  v = c(1L, 2L, 3L)),
  row.names = c(NA, -3L), class = c("data.frame"))
ggplot(data = d[c(1,2), ], aes(y = v, x = id)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(drop = FALSE)
```
![image](https://github.com/tidyverse/ggplot2/assets/25952754/f07f639c-1b7b-4a05-8dac-9c2fe853c502)

Plotting all three rows of data yields a plot with different (and expected) bar width:

```R
library(ggplot2)
d <- structure(list(
  id = structure(c(2L, 5L, 6L), levels = c("A","B", "C", "D", "E", "F"), class = c("ordered", "factor")),
  v = c(1L, 2L, 3L)),
  row.names = c(NA, -3L), class = c("data.frame"))
ggplot(data = d, aes(y = v, x = id)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(drop = FALSE)
```
![image](https://github.com/tidyverse/ggplot2/assets/25952754/fcbdb060-e6d2-4408-bf32-f78df3777b4b)

I believe this issue was introduced with `ggplot2` `v3.4.0`, as `ggplot2` `v3.3.6` yields expected bar width for both plots.

A workaround for the issue is to manually specify `geom_bar` width:

```R
library(ggplot2)
d <- structure(list(
  id = structure(c(2L, 5L, 6L), levels = c("A","B", "C", "D", "E", "F"), class = c("ordered", "factor")),
  v = c(1L, 2L, 3L)),
  row.names = c(NA, -3L), class = c("data.frame"))
ggplot(data = d[c(1,2), ], aes(y = v, x = id)) +
  geom_bar(stat = "identity", width = 0.9) +
  scale_x_discrete(drop = FALSE)
```
![image](https://github.com/tidyverse/ggplot2/assets/25952754/d2e6df36-181e-4a0f-96be-e3f3518bd67e)

**Comment by teunbrand** [comment] 2024-01-12 14:27
Thank you for the report and preparing the examples, we're glad that people are so observant.
I believe this issue is a duplicate of #5211, which is fixed in the development version of ggplot2.
Rendering the first example under the prospective next version of ggplot2 gives the following:

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.5.0'

d <- structure(list(
  id = structure(c(2L, 5L, 6L), levels = c("A","B", "C", "D", "E", "F"), class = c("ordered", "factor")),
  v = c(1L, 2L, 3L)),
  row.names = c(NA, -3L), class = c("data.frame"))

ggplot(data = d[c(1,2), ], aes(y = v, x = id)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(drop = FALSE)
```

![](https://i.imgur.com/KxcnfB7.png)

<sup>Created on 2024-01-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

As I believe we've taken the necessary steps to fix the bug, I'll close this issue as completed.

**Closed by teunbrand** 2024-01-12 14:27 UTC
