### ISSUE TITLE
geom_sf() draws incorrect aesthetics for GEOMETRYCOLLECTION

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#4275] opened 2020-11-26 18:12 UTC
I have noticed this problem in the context of converting invalid to valid geometries using `sf::st_make_valid()`. The invalid geometry is drawn correctly, the valid geometry is not.

In the reprex, I'm using the isoband package to create an invalid geometry and then use `sf::st_make_valid()` to make it valid. The first plot is correct, the second is not.

    library(sf)
    library(dplyr)
    library(isoband)
    library(ggplot2)

    m <- matrix(
      c(1.5, 1.5, 1.5, 1.5, 0.6, 0,
        0.5, 1.5, 1.5,   0,   0, 0,
        0,   1,   0,   1,   1, 0,
        0,   1,   0, 0.7,   0, 0,
        0.9, 1.3, 1.8, 1.4, 0.4, 0
      ),
      nrow = 5, ncol = 6, byrow = TRUE
    )

    b <- isobands(x = 1:6, y = 5:1, z = m, levels_low = 0:1, levels_high = 1:2)
    bands <- iso_to_sfg(b)

    # contains invalid geometries
    iso <- st_sf(
      id = factor(1:length(bands)),
      geometry = st_sfc(bands)
    )

    # contains only valid geometries
    iso_valid <- st_make_valid(iso)

    # correct
    ggplot(iso, aes(fill = id)) +
      geom_sf() + theme(legend.position = "bottom")

![](https://i.imgur.com/vEFEPn8.png)

    # incorrect, id is ignored
    ggplot(iso_valid, aes(fill = id)) +
      geom_sf() + theme(legend.position = "bottom")

![](https://i.imgur.com/Du5BulB.png)

    # geometry type has changed from MULTIPOLYGON to GEOMETRYCOLLECTION
    iso
    #> Simple feature collection with 2 features and 1 field
    #> geometry type:  MULTIPOLYGON
    #> dimension:      XY
    #> bbox:           xmin: 1 ymin: 1 xmax: 6 ymax: 5
    #> CRS:            NA
    #>   id                       geometry
    #> 1  1 MULTIPOLYGON (((6 1, 5 1, 4...
    #> 2  2 MULTIPOLYGON (((4.4 1, 4 1,...
    iso_valid
    #> Simple feature collection with 2 features and 1 field
    #> geometry type:  GEOMETRYCOLLECTION
    #> dimension:      XY
    #> bbox:           xmin: 1 ymin: 1 xmax: 6 ymax: 5
    #> CRS:            NA
    #>   id                       geometry
    #> 1  1 GEOMETRYCOLLECTION (POLYGON...
    #> 2  2 GEOMETRYCOLLECTION (MULTIPO...

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment] 2020-12-06 07:47
Still don't know how to fix this, but probably we'll need to look into sf's side.

We use `sf::st_as_grob()` in `sf_grob()`, and `sf_as_grob.sfc()` is dispatched.

``` r
st_as_grob.sfc <- function(x, pch = 1, size = unit(1, "char"), arrow = NULL, gp = gpar(), ...) {
	x <- st_cast_sfc_default(x)
	if (class(x)[1] %in% c('sfc_MULTIPOINT', 'sfc_MULTILINESTRING', 'sfc_MULTIPOLYGON')) {
		return(st_as_grob(x, gp = gp, ...))
	}
	scalar_grobs(x, pch, size, arrow, gp, ...)
}
```
https://github.com/r-spatial/sf/blob/b211f354f6e4f968acebba2c6067c62f0c058993/R/grid.R#L214

First, `x` gets flattened by `st_cast_sfc_default()`, which possibly makes the length longer than the original (and this is the case on this issue):

``` r
	} else if (cls == "GEOMETRYCOLLECTION" && !any(st_is_empty(x))) { # FIXME: do sth better in case of empty?
		ids = get_lengths(x)
		x <- do.call(st_sfc, unlist(x, recursive = FALSE))
	}
```
https://github.com/r-spatial/sf/blob/18fe5733065eab465b63fa740af1b555efc06a76/R/cast_sfc.R#L123-L126

Then, passed to `scalar_grobs()`, which splits `gp` and iterates `st_as_grob()` over `x`.

``` r
scalar_grobs <- function(x, pch = 1, size = unit(1, "char"), arrow = NULL, gp = gpar(), ...) {
	gp <- split_gp(gp, length(x))
        # ...snip...
	do.call(gList, lapply(seq_along(x), function(i) {
		st_as_grob(x[[i]], pch = pch[i], size = size[i], arrow = arrow[i], gp = gp[[i]], ...)
	}))
}
```

The problem is, `split_gp()` doesn't know which `gp` should be applied to which `x`, and it just recycles `gp` over `x`. This might assign incorrect fill (or other attributes) to some of the elements. Here's what I found on `debug()`ing the second plot:

```
Browse[3]> x
Geometry set for 4 features 
geometry type:  GEOMETRY
dimension:      XY
bbox:           xmin: 0.04545455 ymin: 0.04545455 xmax: 0.9545455 ymax: 0.9545455
CRS:            NA
POLYGON ((0.2272727 0.2727273, 0.09090909 0.045...
MULTILINESTRING ((0.2272727 0.2727273, 0.227272...
MULTIPOLYGON (((0.5909091 0.1753247, 0.6636364 ...
MULTILINESTRING ((0.2272727 0.2727273, 0.227272...
Browse[3]> length(gp)
[1] 4
Browse[3]> vapply(gp, function(x) x$fill, character(1L))
[1] "#F8766D" "#00BFC4" "#F8766D" "#00BFC4"
```

**Comment by thomasp85** [comment] 2021-04-22 10:44
Fixed in https://github.com/r-spatial/sf/pull/1656

**Closed by thomasp85** 2021-04-22 10:44 UTC
Labels: bug, layers :chart_with_upwards_trend:

**Comment by clauswilke** [comment] 2021-04-22 16:06
This is fantastic, thanks!
