### ISSUE TITLE
Plots not showing until Quartz window is resized

### ISSUE THREAD

**Issue by benjaminmoon** [tidyverse/ggplot2#4288] opened 2020-12-07 18:07 UTC
I've recently done some work with ggplot2, having mostly used base-R plots for the last few months and have the following issue when plotting in Quartz using the command and and R.app:

* Plotting base-R plots works correctly and appears in the Quartz window, even doing multiple plotting commands
* Plotting with ggplot2 does not show the plot until I use my mouse to resize the Quartz window. The window will then refresh and the plot will show correctly.

Can you help me resolve why the Quartz window is not showing plots from ggplot?

An example of simple code I'm using in a fresh R session:

```r
plot(1:10) # will plot correctly in Quartz window

library(ggplot2)
data <- data.frame(x = rnorm(10), y = rexp(10))
ggplot(data, aes(x = x, y = y)) +
  geom_point()
# This second plot will not render until I resize the Quartz window

ggsave("test.pdf")
# The pdf file is created correctly, even if still not displayed in Quartz window

plot(10:1) # will display correctly in Quartz window 
```

I include a GIF to show this.

![r_ggplot_issue](https://user-images.githubusercontent.com/1419491/101387787-ddb8a100-38b6-11eb-83b1-0362c2581438.gif)

If, however, I run the above ggplot commands *only* as the first thing in a clean session I get the following error:

```r
Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"
```

And no plot is shown.

------

The output of my `sessionInfo()` is:

```r
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.2

loaded via a namespace (and not attached):
 [1] digest_0.6.27    withr_2.3.0      dplyr_1.0.2      crayon_1.3.4     grid_4.0.3      
 [6] R6_2.5.0         lifecycle_0.2.0  gtable_0.3.0     magrittr_2.0.1   scales_1.1.1    
[11] pillar_1.4.7     rlang_0.4.9      farver_2.0.3     generics_0.1.0   vctrs_0.3.5     
[16] ellipsis_0.3.1   labeling_0.4.2   tools_4.0.3      glue_1.4.2       purrr_0.3.4     
[21] munsell_0.5.0    compiler_4.0.3   pkgconfig_2.0.3  colorspace_2.0-0 tidyselect_1.1.0
[26] tibble_3.0.4   
```

I am running R version 4.0.3 on macOS Big Sur 11.0.1 (=10.16).

**Comment by kohta-ikegami** [comment] 2021-01-07 22:46
I have the exact same problem since upgrading to Big Sur. My `sessionInfo()` is below.
(I haven't attempted to replicate `Error in UseMethod("depth")` in a clean session though.) 

```r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggnewscale_0.4.3      lemon_0.4.5           ggrepel_0.8.2         forcats_0.5.0         stringr_1.4.0         dplyr_1.0.2          
 [7] purrr_0.3.4           readr_1.4.0           tidyr_1.1.2           tibble_3.0.4          ggplot2_3.3.2         tidyverse_1.3.0      
[13] data.table_1.13.2     preprocessCore_1.50.0 viridis_0.5.1         viridisLite_0.3.0     scales_1.1.1          gridExtra_2.3        
[19] RColorBrewer_1.1-2   

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0  xfun_0.19         haven_2.3.1       lattice_0.20-41   colorspace_2.0-0  vctrs_0.3.5       generics_0.1.0   
 [8] utf8_1.1.4        rlang_0.4.9       pillar_1.4.7      glue_1.4.2        withr_2.3.0       DBI_1.1.0         dbplyr_2.0.0     
[15] modelr_0.1.8      readxl_1.3.1      lifecycle_0.2.0   plyr_1.8.6        munsell_0.5.0     gtable_0.3.0      cellranger_1.1.0 
[22] rvest_0.3.6       labeling_0.4.2    knitr_1.30        ps_1.4.0          fansi_0.4.1       broom_0.7.2       Rcpp_1.0.5       
[29] backports_1.2.0   jsonlite_1.7.1    farver_2.0.3      fs_1.5.0          digest_0.6.27     hms_0.5.3         stringi_1.5.3    
[36] grid_4.0.2        cli_2.2.0         tools_4.0.2       magrittr_2.0.1    crayon_1.3.4      pkgconfig_2.0.3   ellipsis_0.3.1   
[43] xml2_1.3.2        reprex_0.3.0      lubridate_1.7.9.2 assertthat_0.2.1  httr_1.4.2        rstudioapi_0.13   R6_2.5.0         
[50] compiler_4.0.2  
```

**Comment by hafen** [comment] 2021-02-17 17:52
I have similar issues that cropped up with updating to Big Sur. I think it is more of a quartz device issue. Often my ggplot plots won't render in the quartz device window and I have to kick-start it by running a base R plot command (e.g. `plot(1:10)`) for subsequent ggplots to render. I don't experience any errors though.

**Comment by thomasp85** [comment] 2021-03-24 11:09
Yeah, this is not a ggplot2 issue. 

@pmur002 you may want to see this - I don't know if you are aware of any regressions in new Mac versions...

closing it here

**Closed by thomasp85** 2021-03-24 11:09 UTC

**Comment by jdunic** [comment] 2022-06-13 19:50
I just wanted to let anyone else know who stumbles on this that updating to R 4.2 seems to resolve the issue.

**Comment by mhofert** [comment] 2024-02-29 11:47
I'm on R 4.3.2 (macOS 14.3.1) and still have that problem when plotting side-by-side (via layout(t(1:2)))
