### ISSUE TITLE
geom_histogram() loses data in the presentation window without warning

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/ggplot2#2931] opened 2018-10-08 16:46 UTC
`geom_histogram()` loses data in the presentation window without warning.  It also generates additional spurious warnings in related rendering situations.

Platform macOS R version 3.5.0 (2018-04-23).

```r
library("ggplot2")
packageVersion("ggplot2")
# [1] ‘3.0.0’

d <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))

# produces 1 bar when we expect 3
ggplot(data = d, mapping = aes(x = x)) + 
  geom_histogram(bins = 30) + 
  xlim(c(0, 1))
# no warnings


# produces 2 bars when we expect 3
ggplot(data = d, mapping = aes(x = x)) + 
  geom_histogram(bins = 30) + 
  xlim(c(-1e-2, 1 + 1e-2))
# one warning
# Warning message:
#   Removed 1 rows containing missing values (geom_bar).


# produces 3 bars as expected
ggplot(data = d, mapping = aes(x = x)) + 
  geom_histogram(bins = 30) + 
  xlim(c(-1e-1, 1 + 1e-1))
# one warning
# Warning message:
#   Removed 1 rows containing missing values (geom_bar).


# produces 3 bars as expected
ggplot(data = d, mapping = aes(x = x)) + 
  geom_histogram(bins = 30)
# no warnings
```

**Comment by JohnMount** [comment] 2018-10-08 16:57
I tried to make a reprex version, but that seems to come out mangled.

``` r
"\nlibrary(\"ggplot2\")\npackageVersion(\"ggplot2\")\n\nd <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))\n\n# produces 1 bar when we expect 3\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(0, 1))\n# no warnings\n\n\n# produces 2 bars when we expect 3\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(-1e-2, 1 + 1e-2))\n# one warning\n# Warning message:\n#   Removed 1 rows containing missing values (geom_bar).\n\n\n# produces 3 bars as expected\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(-1e-1, 1 + 1e-1))\n# one warning\n# Warning message:\n#   Removed 1 rows containing missing values (geom_bar).\n\n\n# produces 3 bars as expected\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30)\n# no warnings\n"
#> [1] "\nlibrary(\"ggplot2\")\npackageVersion(\"ggplot2\")\n\nd <- data.frame(x = c(0, 0, 0.5, 0.5, 1, 1))\n\n# produces 1 bar when we expect 3\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(0, 1))\n# no warnings\n\n\n# produces 2 bars when we expect 3\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(-1e-2, 1 + 1e-2))\n# one warning\n# Warning message:\n#   Removed 1 rows containing missing values (geom_bar).\n\n\n# produces 3 bars as expected\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30) + \n  xlim(c(-1e-1, 1 + 1e-1))\n# one warning\n# Warning message:\n#   Removed 1 rows containing missing values (geom_bar).\n\n\n# produces 3 bars as expected\nggplot(data = d, mapping = aes(x = x)) + \n  geom_histogram(bins = 30)\n# no warnings\n"
```

<sup>Created on 2018-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment] 2018-10-08 17:04
Duplicate of #2887. At present, to not lose any bars, you have to set limits that include the entire width of the bars. It's unclear whether a fix is possible, and if so, when it will be available.

**Closed by clauswilke** 2018-10-08 17:04 UTC
