### ISSUE TITLE
Inconsistency in `scale_` functions for args `values` and `labels` for `NA` values

### ISSUE THREAD

**Issue by petres** [tidyverse/ggplot2#4713] opened 2022-01-10 20:14 UTC
First, best package ever! 
There are some inconsistencies using the args `values` and `labels` in the `scale_` functions. 
For example (try the different `values` arguments - commented below): 

```r
ggplot(
    data = data.frame(
        y = rnorm(30), 
        x = 1:10, 
        g = rep(c('A', 'B', NA), 10, each = T)
    ), 
    aes(x = x, y = y, group = g, fill = g)
) + 
geom_col() +
scale_fill_manual(
    "Fruit", 
    values = c('A' = "#97CC04", 'B' = "#EEB902", 'NA' = '#2D7DD2'), na.value = "#2D7DD2",
    #values = c('A' = "#97CC04", 'B' = "#EEB902"), na.value = "#2D7DD2",
    #values = c('A' = "#97CC04", 'B' = "#EEB902", 'NA' = 'red'),
    #values = c('A' = "#97CC04", 'B' = "#EEB902"), 
    labels = c('A' = "Apples", 'B' = "Bananas", 'NA' = 'Unknown')
) 
```

Maybe I am wrong, but the `labels` argument behaves quite differently from the `values` arg while doing exactly the same - providing a simple mapping. Introducing `na.label` would provide consistency, but that's maybe the wrong direction.

**Comment by smouksassi** [comment] 2022-01-10 20:35
``` r
library(ggplot2)
library(patchwork)
ggdata <-   data.frame(
  y = rnorm(30), 
  x = 1:10, 
  g = rep(c('A', 'B', NA), 10, each = T)
)

A <- ggplot(ggdata,
  aes(x = x, y = y, group = g, fill = g)
) + 
  geom_col() +
  scale_fill_manual("Fruit", 
                    values = c('A' = "#97CC04", 'B' = "#EEB902", 'NA' = '#2D7DD2'), na.value = "#2D7DD2",
                    labels = c('A' = "Apples", 'B' = "Bananas", 'NA' = 'Unknown')
  ) 

B <-  A +
  scale_fill_manual("Fruit", 
                    values = c('A' = "#97CC04", 'B' = "#EEB902"), na.value = "#2D7DD2",
                    labels = c('A' = "Apples", 'B' = "Bananas", 'NA' = 'Unknown')
  ) 
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
C <-  A +
  scale_fill_manual("Fruit", 
                    values = c('A' = "#97CC04", 'B' = "#EEB902", 'NA' = 'red'),
                    labels = c('A' = "Apples", 'B' = "Bananas", 'NA' = 'Unknown')
  )
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
D <-  A +
  scale_fill_manual("Fruit", 
                    values = c('A' = "#97CC04", 'B' = "#EEB902"), 
                    labels = c('A' = "Apples", 'B' = "Bananas", 'NA' = 'Unknown')
  )
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
E <-  A +
  scale_fill_manual("Fruit", 
                    values = c("#97CC04","#EEB902"),  na.value = "#2D7DD2"
  )
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
F <-  A +
  scale_fill_manual("Fruit", 
                    values = c("#97CC04","#EEB902"),  na.value = "#2D7DD2",
                    labels = c("Apples","Bananas",'Unknown')
  )
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
 A +B + C +D + E + F
```

![](https://i.imgur.com/tSYXFks.png)

<sup>Created on 2022-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by smouksassi** [comment] 2022-03-14 22:24
I think the original poster wanted to know the official supported way to give the NA values a different label in the legend for the fill scale (instead of the default NA.
The na.value control the color assigned to NA  but the is no na.label argument to tell ggplot2 what label I want for NA.
(sorry my reprex is not working at the moment)

'''r
  library(ggplot2)
  library(patchwork)
  
  ggdata <-   data.frame(
    y = rnorm(40), 
    x = 1:10, 
    g = rep(c('B', 'A', NA, 'C'), 10, each = T)
  )
  
  ggplotdefault <- ggplot(ggdata,
                          aes(x = x, y = y, group = g, fill = g)
  ) + 
    geom_col()+
    labs(fill="Fruit", title = "ggplot default")
  
  
  
  A <- ggplot(ggdata,
              aes(x = x, y = y, group = g, fill = g)) + 
    geom_col() +
    scale_fill_manual("Fruit", 
                      values = c('A' = "#97CC04", 'B' = "#EEB902",'C' = "red"), na.value = "gray",
                      labels = c('A' = "Apples", 'B' = "Bananas", 'C' = "Citrus")
    ) +
    labs(fill="Fruit", title = "how to make a custom label for NA ? where did the NA label go ?")
  
  B <-  A +
    scale_fill_manual("Fruit", 
                      values = c('A' = "#97CC04", 'B' = "#EEB902","blah"= "blue",'C' = "red"), na.value = "gray",
                      labels = c('A' = "Apples", 'B' = "Bananas",  'C' = "Citrus", "blah"= "blue")
    ) +
    labs(fill="Fruit", title = "need a fake named value with color = to na.value")
  
  C <-  B +
    scale_fill_manual("Fruit", 
                      values = c('A' = "#97CC04", 'B' = "#EEB902",'C' = "red","Missing"="gray"), na.value = "gray",
                      labels = c('A' = "Apples", 'B' = "Bananas",  'C' = "Citrus", "Missing"= "Missing")
    ) +
    labs(fill="Fruit", title = "need a fake named value at the end")
  
  
  
  ggplotdefault + A + B + C

'''

**Comment by hadley** [comment] 2022-03-15 14:05
Ok, in the case, I think the problem is more easily solved by using another tool upstream to change `NA` to some other value. That's considerably simpler than introducing a new argument to every ggplot2 scale.

**Closed by hadley** 2022-03-15 14:05 UTC
