### ISSUE TITLE
scale_*_date shows axis labels outside of limits

### ISSUE THREAD

**Issue by Prometheus77** [tidyverse/ggplot2#3661] opened 2019-12-10 00:08 UTC
When using scale_x_date or scale_y_date to bound a graph, the axis shows axis labels outside of the specified limits.

```r
library(ggplot2)
library(scales)
set.seed(100)
z <- seq.Date(as.Date("2008/12/1"), as.Date("2015/12/14"), "day")
l <- expand.grid(z, c("a", "b", "c"))
w <- data.frame(x= l[, 1], t = l[, 2])
w$val <- runif(nrow(w))

ggplot(w, aes(x, val)) + geom_point() +
  scale_x_date(date_breaks = '1 month', limits = c(as.Date('2008/12/1'), as.Date('2015/12/1'))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
I see four months of extra axis labels on either side of the plot, despite the fact that I'm specifying my limits at 2008/12/1 and 2015/12/1.

**Comment by smouksassi** [comment] 2019-12-10 08:59
if you want to control axis expansion use the argument for it.
limits will exclude data but not necessarily affect the axis breaks and labels.


``` r
library(ggplot2)
library(scales)
set.seed(100)
z <- seq.Date(as.Date("2008/12/1"), as.Date("2015/12/14"), "day")
l <- expand.grid(z, c("a", "b", "c"))
w <- data.frame(x= l[, 1], t = l[, 2])
w$val <- runif(nrow(w))
ggplot(w, aes(x, val)) + geom_point() +
  scale_x_date(date_breaks = '1 month',
               expand = c(0,0,0,0) ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
![](https://i.imgur.com/lXPJ1JL.png)
<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment] 2019-12-13 03:17
This seems a duplicate of #3592.

**Closed by yutannihilation** 2019-12-13 03:17 UTC
