### ISSUE TITLE
Example Code in Wiki Tutorial No Longer Works

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#2396] opened 2018-01-11 07:00 UTC
The example developed by @baptiste and titled "Align two plots on a page" no longer works with current versions of the R packages and R. The line `g <- rbind(g1, g2, size="first") # stack the two plots` now results in `Error in rbind_gtable(x, y, size = size) : ncol(x) == ncol(y) is not TRUE`. I have

```
other attached packages:
[1] gtable_0.2.0  ggplot2_2.2.1
```

and am running R Under development (unstable) (2018-01-07 r74096).

**Comment by batpigandme** [comment] 2018-01-11 16:23
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

**Comment by DarioS** [comment] 2018-01-12 00:00
The code is

``` r
library(ggplot2)
x <- seq(1992, 2002, by=2)

d1 <- data.frame(x=x, y=rnorm(length(x)))
xy <- expand.grid(x=x, y=x)
d2 <- data.frame(x=xy$x, y=xy$y, z= jitter(xy$x + xy$y))

p1 <-  ggplot(data = d1, mapping = aes(x = x, y = y)) + 
  geom_line(stat = "identity") 

p2 <-  ggplot(data = d2, mapping = aes(x=x, y=y, fill=z)) + 
  geom_tile()

## convert plots to gtable objects
library(gtable)
library(grid) # low-level grid functions are required
g1 <- ggplotGrob(p1)
g1 <- gtable_add_cols(g1, unit(0,"mm")) # add a column for missing legend
g2 <- ggplotGrob(p2)
g <- rbind(g1, g2, size="first") # stack the two plots
#> Error in rbind_gtable(x, y, size = size): ncol(x) == ncol(y) is not TRUE
```

and I obtained it from the URL https://github.com/tidyverse/ggplot2/wiki/Align-two-plots-on-a-page

**Comment by baptiste** [comment] 2018-01-12 00:12
Such wiki pages should probably be deleted since it's not an officially-supported medium for the package (and therefore not maintained when breaking changes are made to the package, which must be confusing for many visitors).

**Comment by batpigandme** [comment] 2018-01-12 14:19
I agree @baptiste, I actually didn't even know it existed. I'm not sure if/how it should be sunset… @hadley?

**Comment by baptiste** [comment] 2018-01-14 20:36
I suggested a few times a workflow for reproducible wiki pages based on Rmd, but the response was that bookdown-style websites provided the same functionality with more powerful features. From that perspective, it would seem that the way to not lose this existing content would be for someone to convert the wiki pages (at least those with useful content) to article-style pkgdown/bookdown format and include that directly in the package's repo. On the other hand, the wiki content is generally not as tidy as may be desirable for an official package doc, so a thorough curating would also be required. 

Personally I would still push for a reproducible wiki (Rmd source for each page, to be re-run at each new release). With a more loosely-organised structure than other types of documentation, it fills a useful niche complementing the likes of pkgdown, bookdown, etc. If edits are made online (on md intermediates), they could be manually merged to the Rmd sources (edits don't seem to happen very often anymore).

**Comment by DarioS** [comment] 2018-01-15 00:00
> Such wiki pages should probably be deleted ...

As long as I can find a working example of how plot edges can be aligned somewhere else . It'd be wonderful if there was a one-line function in ggplot2 for this to avoid the end-user dealing with low-level `gtable` objects..

**Comment by baptiste** [comment] 2018-01-15 00:04
https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html

**Comment by hadley** [comment] 2018-01-17 19:34
I've made it more clear that the wiki is now retired. 

@baptiste I think an Rmd wiki would be nice, but the problem is that wikis don't generally work without a fairly large critical mass of people keeping them up to date. Unfortunately that critical mass doesn't appear to exist for ggplot2.

**Closed by hadley** 2018-01-17 19:34 UTC
