### ISSUE TITLE
The cross effect in legend when use geom_hline and geom_vline in the same plot.

### ISSUE THREAD

**Issue by fmassicano** [tidyverse/ggplot2#2483] opened 2018-03-15 18:35 UTC
That problem was very discussed in issue [geom\_vline messes up geom\_line legend, if show\_guide = TRUE](https://github.com/tidyverse/ggplot2/issues/1267), but a similar problem still happen, as was mentioned by [rdcominer](https://github.com/rdcomineor) in this [comment](https://github.com/tidyverse/ggplot2/issues/1267#issuecomment-187116698), when both hline and vline are in the same plot. _**The legend of that plot, regarding hline and vline will be overlapping.**_

Here's are the examples:

``` r
library(ggplot2)                                                                                                                                                                               
df <- data.frame(x = c(1, 2), y = c(1, 2), z = c("a", "b"))                                                                                                                                    
threshold <- data.frame(x = c(1.2, 1.5), name = c("bar", "foo"))                                                                                                                               
```
Both legends are shown (vline and hline) which procude the cross effect

``` r
ggplot(df, aes(x, y, colour = z)) +                                                                                                                                                            
geom_point() +                                                                                                                                                                                 
geom_vline(aes(xintercept = 1.25, linetype = "dotted"), colour= 'red', data = threshold) +                                                                                                     
geom_hline(aes(yintercept = 1.75, linetype = "1F"), colour= 'blue', data = threshold) +                                                                                                        
scale_linetype_manual(name = "Thresholds",values = c(2,2))                                                                                                                                     
```
![unnamed-chunk-2-1](https://user-images.githubusercontent.com/1872321/37482519-5a458788-2852-11e8-8c1a-bfffb499fe13.png)

I tried to use show.legend = FALSE in one of them, to see what happens, but ggplot2 preserve the pattern of another one in both legends.

Then the next example, show us only geom\_vline legend which preserves the vline pattern in legends

``` r
ggplot(df, aes(x, y, colour = z)) +                                                                                                                                                            
geom_point() +                                                                                                                                                                                 
geom_vline(aes(xintercept = 1.25, linetype = "dotted"), colour= 'red', data = threshold) +                                                                                                     
geom_hline(aes(yintercept = 1.75, linetype = "1F"), colour= 'blue', 
                     data = threshold, show.legend = FALSE) +                                                                                   
scale_linetype_manual(name = "Thresholds",values = c(2,2))                                                                                                                                     
```
![unnamed-chunk-3-1](https://user-images.githubusercontent.com/1872321/37482542-65e7c8ee-2852-11e8-9f49-d577df8a907b.png)

The next one, the only geom\_hline legend is shown which preserve the hline pattern in legends

``` r
ggplot(df, aes(x, y, colour = z)) +                                                                                                                                                            
geom_point() +                                                                                                                                                                                 
geom_vline(aes(xintercept = 1.25, linetype = "dotted"), colour= 'red', 
                    data = threshold,show.legend = FALSE) +                                                                                 
geom_hline(aes(yintercept = 1.75, linetype = "1F"), colour= 'blue', data = threshold) +                                                                                                        
scale_linetype_manual(name = "Thresholds",values = c(2,2))                                                                                                                                     
```
![unnamed-chunk-4-1](https://user-images.githubusercontent.com/1872321/37482548-6d7bfae4-2852-11e8-932d-b2f6d00f445a.png)

-----

If is possible, would be nice to allow both hline and vline in the same plot, with a horizontal line in hline legend, and a vertical line in vline legend.

**Comment by hadley** [comment] 2018-04-27 13:46
Duplicate of #2492

**Closed by hadley** 2018-04-27 13:46 UTC
