### ISSUE TITLE
Show secondary axis lines without specifying secondary axes

### ISSUE THREAD

**Issue by willgearty** [tidyverse/ggplot2#3917] opened 2020-03-30 21:08 UTC
I'm trying to make a plot with a border around the entire panel and also with tick marks at the very ends of the axes. Unfortunately, regardless of theme this means the tick marks don't line up with the panel border. This is especially apparent when you have a larger `base_size`:

```r
ggplot(mpg, aes(displ, hwy)) +
    geom_point() +
    scale_y_continuous(limits = c(10,50), expand = c(0,0)) +
    theme_bw(base_size=24)
```
![image](https://user-images.githubusercontent.com/7232514/77961322-4880f980-729f-11ea-9d4f-11467e7d00c1.png)
(note the 10 and 50 y axis tick marks do not line up with the panel border)

Now, this makes sense, because the panel border is actually supposed to be within the axes, so let's just put some axes on:

```r
ggplot(mpg, aes(displ, hwy)) +
    geom_point() +
    scale_y_continuous(limits = c(10,50), expand = c(0,0)) +
    theme_bw(base_size=24) +
    theme(axis.line = element_line(lineend = "square"))
```
![image](https://user-images.githubusercontent.com/7232514/77961676-cf35d680-729f-11ea-99ec-628b4fb3a20b.png)

Well, that's not really what we want, because the panel border still doesn't line up with the axes. But how can I add right and top axes? The only way I know of is as follows:
```r
ggplot(mpg, aes(displ, hwy)) +
    geom_point() +
    scale_y_continuous(limits = c(10,50), expand = c(0,0), sec.axis = sec_axis(~.)) +
    theme_bw(base_size=24) +
    theme(axis.line = element_line(lineend = "square"), axis.text.y.right = element_blank(), axis.ticks.y.right = element_blank())
```
![image](https://user-images.githubusercontent.com/7232514/77962056-80d50780-72a0-11ea-984c-07c441f1b29f.png)

But that feels pretty hacky to me. So my questions is: is there a way to add such an axis line without specifying sec.axis and then removing everything I don't want? Ideally the defaults for the the secondary axis theme elements would be element_blank() when there is no sec.axis specified, then the user could just turn them on as desired, e.g.:
```r
ggplot(mpg, aes(displ, hwy)) +
    geom_point() +
    scale_y_continuous(limits = c(10,50), expand = c(0,0)) +
    theme_bw(base_size=24) +
    theme(axis.line = element_line(lineend = "square"), axis.line.y.right = element_line(lineend = "square"))
```

**Comment by clauswilke** [comment] 2020-03-30 21:38
The problem is caused by clipping and goes away if you turn it off.

``` r
library(ggplot2)

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  scale_y_continuous(limits = c(10,50), expand = c(0,0)) +
  theme_bw(base_size=24) + 
  coord_cartesian(clip = "off")
```

![](https://i.imgur.com/RoJoB70.png)

<sup>Created on 2020-03-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by willgearty** [comment] 2020-03-31 16:35
@clauswilke Oh, wow, I had no idea clipping was causing the panel border to be half width, I just assumed it was designed like that, but that makes total sense now! That solution well definitely work for my current situation, but I can imagine cases where you might not want to turn clipping off (e.g. maybe you have elements outside of the plot area). I still think it'd be ideal to be able to style the secondary axes without going through the hassle of defining them in the scales.

**Comment by thomasp85** [comment] 2020-04-30 18:52
it is unlikely that we will add this, and since your original issue was resolved I'm closing it

**Closed by thomasp85** 2020-04-30 18:52 UTC
