### ISSUE TITLE
in `stat_boxplot()`: 'rqbr' is not an exported object from 'namespace:quantreg'

### ISSUE THREAD

**Issue by mgacc0** [tidyverse/ggplot2#2180] opened 2017-06-25 10:18 UTC
```r
df1 <- data.frame(value=c(1,2,3), duration=c(10,10,20))
ggplot(df1, aes(x=factor(0), y=value, weight=duration)) +
  geom_boxplot()
# Warning: Computation failed in `stat_boxplot()`:
# "rqbr" not resolved from current namespace (quantreg)
```

**Comment by karawoo** [comment] 2017-06-28 16:00
I can't reproduce this; does it still create the plot despite the warning? It would be helpful if you could provide a minimal reprex (reproducible example). The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

For this it might help to see the output of `sessionInfo()` as well.

**Comment by mgacc0** [comment] 2017-06-28 20:01
I have updated `quantreg`
```
install.packages("quantreg", dependencies=TRUE)
```
and now I can obtain plots.


Anyway for some cases it generates a warning.
For example:
```
df1 <- data.frame(value=c(1,2,3), duration=c(10,10,20))
ggplot(df1, aes(x=factor(0), y=value, weight=duration)) +
  geom_boxplot()
# Warning messages:
# 1: In rq.fit.br(wx, wy, tau = tau, ...) : Solution may be nonunique
# 2: In rq.fit.br(wx, wy, tau = tau, ...) : Solution may be nonunique
```

But this is ok:
```
df1 <- data.frame(value=c(1,2,3,3), duration=c(10,10,20,10))
ggplot(df1, aes(x=factor(0), y=value, weight=duration)) +
  geom_boxplot()
```

**Comment by karawoo** [comment] 2017-07-11 16:24
Glad the plots are working now. The warning message is related to the regression quantile estimates, about which there's more info on the [quantreg FAQ](http://www.econ.uiuc.edu/~roger/research/rq/FAQ). I'm closing this issue as I think this warning is expected behavior, and you can see it if you call `rq()` directly on your data:

``` r
library("quantreg")
df1 <- data.frame(value=c(1,2,3), duration=c(10,10,20))
df2 <- data.frame(value=c(1,2,3,3), duration=c(10,10,20,10))

rq(value ~ 1, weights = duration, data = df1, tau = c(0, 0.25, 0.5, 0.75, 1))
#> Warning in rq.fit.br(wx, wy, tau = tau, ...): Solution may be nonunique

#> Warning in rq.fit.br(wx, wy, tau = tau, ...): Solution may be nonunique
#> Call:
#> rq(formula = value ~ 1, tau = c(0, 0.25, 0.5, 0.75, 1), data = df1, 
#>     weights = duration)
#> 
#> Coefficients:
#>             tau= 0.00 tau= 0.25 tau= 0.50 tau= 0.75 tau= 1.00
#> (Intercept)         1         1         2         3         3
#> 
#> Degrees of freedom: 3 total; 2 residual
rq(value ~ 1, weights = duration, data = df2, tau = c(0, 0.25, 0.5, 0.75, 1))
#> Call:
#> rq(formula = value ~ 1, tau = c(0, 0.25, 0.5, 0.75, 1), data = df2, 
#>     weights = duration)
#> 
#> Coefficients:
#>             tau= 0.00 tau= 0.25 tau= 0.50 tau= 0.75 tau= 1.00
#> (Intercept)         1         2         3         3         3
#> 
#> Degrees of freedom: 4 total; 3 residual
```

**Closed by karawoo** 2017-07-11 16:24 UTC
Labels: reprex
