### ISSUE TITLE
grid.call issue 

### ISSUE THREAD

**Issue by GG786** [tidyverse/ggplot2#2277] opened 2017-10-01 04:18 UTC
I am running this code 
library(ggplot2) 
library(gggenes) 
ggplot2::ggplot(example_genes, ggplot2::aes(xmin = start, y = molecule, fill = gene))+
geom_gene_arrow()+ 
ggplot2::facet_wrap(~ molecule, scales = "free", ncol = 1)+ 
ggplot2::scale_fill_brewer(palette = "Set3")
#but facing an error in r studio 
(Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : Viewport has zero dimension(s)) 
how i can fix it

**Comment by hadley** [comment] 2017-10-30 17:36
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-11-07 20:24
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-07 20:24 UTC
Labels: reprex
