### ISSUE TITLE
The "R-CMD-check / ubuntu-latest (devel) (pull_request)" action keeps failing

### ISSUE THREAD

**Issue by steveharoz** [tidyverse/ggplot2#5464] opened 2023-10-10 11:13 UTC
I'm sure the maintainers are aware, but `R-CMD-check / ubuntu-latest (devel) (pull_request)` runs for over half an hour and fails in every(?) PR.

The result is an email after every commit to a PR telling you that the run failed. Maybe consider disabling the action until the underlying issue is resolved?

**Comment by teunbrand** [comment] 2023-10-10 11:21
Yeah a change in upstream R devel requires a hotfix release (see #5437).
The fix is already there, but we need to finish that release before it gets merged into the main branch.
Until that is done, I suggest to push commits in batches so that you don't get an email for *every* commit.
In any case, this issue will be fixed by #5437 so in order to avoid discussing the same topic in multiple places, I'll close this issue.

**Closed by teunbrand** 2023-10-10 11:21 UTC

**Comment by teunbrand** [comment] 2023-10-13 11:05
Should now work as intended
