### ISSUE TITLE
Zero point not included in scale_*_sqrt()

### ISSUE THREAD

**Issue by frederikziebell** [tidyverse/ggplot2#4478] opened 2021-05-14 09:33 UTC
The zero point on the x-axis is not shown if `scale_*_sqrt()` is used, even when it is set in the `breaks` argument. Running
```r
tibble(x=(0:5)^2,y=0:5) %>% 
  ggplot(aes(x,y)) +
    geom_point() +
    scale_x_sqrt(breaks=(0:5)^2)
```
results in 
<img width="827" alt="grafik" src="https://user-images.githubusercontent.com/28304028/118251729-37e21180-b4a8-11eb-85f0-030ea9d33963.png">

**Comment by teunbrand** [comment] 2021-05-14 10:42
This is a possible duplicate of #980

**Closed** 2021-05-14 12:32 UTC
