### ISSUE TITLE
`axis.line` works, but not `axis.line.x` and `axis.line.y`

### ISSUE THREAD

**Issue by thjwong** [tidyverse/ggplot2#2138] opened 2017-05-22 21:35 UTC
`axis.line` works, but not `axis.line.x` and `axis.line.y`, in 3.3.3/3.4.0.

---

Exactly opposite of bug #1567 

For example,

This works:

```r
    theme(axis.line = element_line(color = 'black')) +
```

But this doesn't":

```r
theme(axis.line.x = element_line(color="black", size = .5),
    axis.line.y = element_line(color="black", size = .5)) +
```

**Comment by hadley** [comment] 2017-05-24 18:30
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by karawoo** [comment] 2017-07-11 16:03
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by karawoo** 2017-07-11 16:03 UTC
Labels: reprex
