### ISSUE TITLE
no tick mark at y=0 with scale_y_sqrt()

### ISSUE THREAD

**Issue by DaveCooper** [tidyverse/ggplot2#1962] opened 2016-12-20 18:21 UTC
I cannot get a tick mark at y=0 when using scale_y_sqrt, even if I explicitly ask for a break at y=0.  Here's a simple example:

require(ggplot2)

d = data.frame(x=0:5, y=0:5)

ggplot(d, aes(x, y)) +
  geom_point() +
  scale_y_sqrt(breaks=0:5)

thanks,

Dave

my sessionInfo, in case it's useful:

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.1.0

loaded via a namespace (and not attached):
[1] labeling_0.3     colorspace_1.2-6 scales_0.4.0     plyr_1.8.4       tools_3.3.1     
[6] gtable_0.2.0     Rcpp_0.12.7      grid_3.3.1       munsell_0.4.3

**Comment by hadley** [comment] 2017-01-02 23:46
Duplicate of #980

**Closed by hadley** 2017-01-02 23:46 UTC

**Comment by DaveCooper** [comment] 2017-01-03 03:09
Thanks, Hadley.  Much more complicated than I had imagined!

Happy New Year!

Dave
