### ISSUE TITLE
Computation failed in `stat_ellipse()`

### ISSUE THREAD

**Issue by Gee-Lau** [tidyverse/ggplot2#4805] opened 2022-04-20 10:42 UTC
Hi I am currently using the stat_ellipse function from the ggplot, however, the warning meassage

Computation failed in `stat_ellipse()`:
missing value where TRUE/FALSE needed 

kept poped up. So I tried to create a test data frame via:
a <- data.frame(a = rnorm(100,4,2),
          b = rnorm(100,4,2),
         group = c(rep("a",50),rep("b",50)))
and it worked very weired.

First of all, if I print with

ggplot(a,aes(x = a, y = b, col = group)) +
    geom_point() +
    stat_ellipse()

The function worked perfectly without any warnnings/errors
![image](https://user-images.githubusercontent.com/48349699/164212148-5c9deb90-8fd6-45c5-82c6-07a9822524cf.png)

But when I tried without using colors to indicate different groups,

ggplot(a,aes(x = a, y = b)) +
    geom_point() +
    stat_ellipse()

![image](https://user-images.githubusercontent.com/48349699/164212513-4318cf56-8b41-4f90-9520-f93442b90beb.png)

the `missing value where TRUE/FALSE needed ` warning poped up again,  and the most strange thing is, when I draw with the selected data frame (excluded the group column), the function worked but seemed inccorect:

ggplot(a[,-3],aes(x = a, y = b)) +
    geom_point() +
    stat_ellipse()

with a warning of `In MASS::cov.trob(data[, vars]) : Probable convergence failure`
![image](https://user-images.githubusercontent.com/48349699/164212660-8347c11a-9645-4689-8858-e93dc24ea18c.png)

I have updated R and R studio weeks ago, this function worked before I update, I'm not sure if there are any conflicts between the updated R/Rstudio and my system.

Below are the sessionInfo() for your information:

R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_HK.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_HK.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_HK.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_HK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
 [1] reprex_2.0.1                vegan_2.5-7                
 [3] lattice_0.20-45             permute_0.9-7              
 [5] readxl_1.3.1                dplyr_1.0.8                
 [7] ggplot2_3.3.5               patchwork_1.1.1            
 [9] lmerTest_3.1-3              lme4_1.1-28                
[11] Matrix_1.4-1                MicrobiotaProcess_1.7.8.992
[13] phyloseq_1.38.0            

loaded via a namespace (and not attached):
  [1] TH.data_1.1-0               ggnewscale_0.4.7           
  [3] minqa_1.2.4                 colorspace_2.0-3           
  [5] ggtree_3.2.1                ggsignif_0.6.3             
  [7] ellipsis_0.3.2              modeltools_0.2-23          
  [9] XVector_0.34.0              fs_1.5.2                   
 [11] GenomicRanges_1.46.1        aplot_0.1.2                
 [13] rstudioapi_0.13             farver_2.1.0               
 [15] ggpubr_0.4.0                ggrepel_0.9.1              
 [17] fansi_1.0.3                 mvtnorm_1.1-3              
 [19] coin_1.4-2                  codetools_0.2-18           
 [21] splines_4.1.3               libcoin_1.0-9              
 [23] ade4_1.7-18                 jsonlite_1.8.0             
 [25] nloptr_2.0.0                broom_0.7.12               
 [27] cluster_2.1.3               compiler_4.1.3             
 [29] backports_1.4.1             assertthat_0.2.1           
 [31] lazyeval_0.2.2              cli_3.2.0                  
 [33] tools_4.1.3                 igraph_1.2.11              
 [35] gtable_0.3.0                glue_1.6.2                 
 [37] GenomeInfoDbData_1.2.7      reshape2_1.4.4             
 [39] Rcpp_1.0.8.3                carData_3.0-5              
 [41] Biobase_2.54.0              cellranger_1.1.0           
 [43] vctrs_0.3.8                 Biostrings_2.62.0          
 [45] rhdf5filters_1.6.0          writexl_1.4.0              
 [47] multtest_2.50.0             ape_5.6-2                  
 [49] nlme_3.1-157                iterators_1.0.14           
 [51] stringr_1.4.0               lifecycle_1.0.1            
 [53] rstatix_0.7.0               zlibbioc_1.40.0            
 [55] MASS_7.3-56                 zoo_1.8-9                  
 [57] scales_1.1.1                MatrixGenerics_1.6.0       
 [59] parallel_4.1.3              SummarizedExperiment_1.24.0
 [61] biomformat_1.22.0           sandwich_3.0-1             
 [63] rhdf5_2.38.1                gridExtra_2.3              
 [65] ggfun_0.0.5                 yulab.utils_0.0.4          
 [67] stringi_1.7.6               S4Vectors_0.32.4           
 [69] foreach_1.5.2               tidytree_0.3.9             
 [71] ggstar_1.0.3                BiocGenerics_0.40.0        
 [73] boot_1.3-28                 GenomeInfoDb_1.30.1        
 [75] rlang_1.0.2                 pkgconfig_2.0.3            
 [77] matrixStats_0.61.0          bitops_1.0-7               
 [79] purrr_0.3.4                 Rhdf5lib_1.16.0            
 [81] labeling_0.4.2              treeio_1.18.1              
 [83] cowplot_1.1.1               tidyselect_1.1.2           
 [85] plyr_1.8.7                  magrittr_2.0.2             
 [87] R6_2.5.1                    IRanges_2.28.0             
 [89] generics_0.1.2              multcomp_1.4-18            
 [91] DelayedArray_0.20.0         DBI_1.1.2                  
 [93] withr_2.5.0                 pillar_1.7.0               
 [95] mgcv_1.8-39                 survival_3.3-1             
 [97] abind_1.4-5                 RCurl_1.98-1.6             
 [99] tibble_3.1.6                crayon_1.5.1               
[101] car_3.0-12                  utf8_1.2.2                 
[103] data.table_1.14.2           ggtreeExtra_1.4.2          
[105] digest_0.6.29               tidyr_1.2.0                
[107] numDeriv_2016.8-1.1         gridGraphics_0.5-1         
[109] stats4_4.1.3                munsell_0.5.0              
[111] ggplotify_0.1.0            

Many thanks for your time and looking forward to your reply.

Best regards,
G

**Comment by yutannihilation** [comment] 2022-04-23 09:37
I cannot reproduce your issue on Windows. I suspected it depends on the seed, but I couldn't get any error by running this tens of times without `set.seed()`. Is this a problem with the MASS package on Ubuntu? Then I think there's nothing we can do on ggplot2's side, unfortunately.

``` r
library(ggplot2)

set.seed(10)
a <- data.frame(
  a = rnorm(100, 4, 2),
  b = rnorm(100, 4, 2),
  group = c(rep("a", 50), rep("b", 50))
)

ggplot(a, aes(x = a, y = b)) +
  geom_point() +
  stat_ellipse()
```

![](https://i.imgur.com/6dFehCX.png)

<sup>Created on 2022-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thomasp85** [comment] 2022-05-12 07:21
I agree - I would ask you to file a bug in MASS, potentially isolating your issue to a reprex outside of ggplot2. Closing for now but feel free to come back if it turns out ggplot2 really is the culprit somehow

**Closed by thomasp85** 2022-05-12 07:21 UTC
