### ISSUE TITLE
Default width inconsistent between geom_boxplot and others

### ISSUE THREAD

**Issue by idemockle** [tidyverse/ggplot2#2404] opened 2018-01-15 18:22 UTC
The default width of geom_boxplot seems to be 0.75*(resolution), whereas for stat_identity it is 0.9*(resolution). This causes unexpected behavior when using stat = "identity" in geom_boxplot, because the default width is changed. The default width of boxplots seems to be undocumented, or at least I could not find it anywhere.

This took me an annoyingly long time to figure out, and I think it'd be great if these values could be made consistent to aid in user-friendliness. Barring that, documenting the width calculation in the doc for geom_boxplot would also be very helpful.

```r
library(tidyverse)

# Example data
ncat1 <- 2
ncat2 <- 3
a <- data.frame(cat1 = factor(rep(1:ncat1, each = ncat2*100)), 
                cat2 = factor(rep(rep(1:ncat2, each = 100), ncat1)), 
                val = rnorm(ncat1*ncat2*100))
abox <- a %>% 
  group_by(cat1, cat2) %>% 
  summarise(ymin = min(val),
            lower = quantile(val, .25),
            middle = median(val),
            upper = quantile(val, .75),
            ymax = max(val),
            mean = mean(val))

# Plot boxplots and means with default boxplot stat and dodge width = 0.75
a %>% 
  ggplot(aes(cat1, val)) + 
    geom_boxplot(aes(fill = cat2)) + 
    geom_point(data = abox, aes(group = cat2, y = mean), 
               position = position_dodge(width = .75),
               color = 'blue', 
             size = 3)

# Plot boxplots and means with identity stat, having whiskers cover entire range of data, 
# and with dodge width = 0.75 (points misaligned)
abox %>% 
  ggplot(aes(cat1)) + 
    geom_boxplot(aes(fill = cat2, 
                     ymin = ymin, 
                     lower = lower,
                     middle = middle,
                     upper = upper,
                     ymax = ymax),
                 stat = 'identity') + 
    geom_point(aes(group = cat2, y = mean), 
               position = position_dodge(width = .75),
               color = 'blue', 
               size = 3)
```

**Comment by batpigandme** [comment] 2018-01-15 18:30
@karawoo, is this related to the changes in https://github.com/tidyverse/ggplot2/pull/2196? Per https://github.com/tidyverse/ggplot2/pull/2196/commits/8398e7e9b87ed62b16a2a317207c4bfdd118077b, box plots use `position_dodge2` by default, but I'm not totally clear on the dodging for geom_point. Thanks, Kara.

**Comment by batpigandme** [comment] 2018-01-15 18:34
(possibly related to #2331)

For future reference, @idemockle, it's helpful if you can render your code with [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample, as is done below), since it automatically includes figures.


``` r
suppressPackageStartupMessages(library(tidyverse))

# Example data
ncat1 <- 2
ncat2 <- 3
a <- data.frame(cat1 = factor(rep(1:ncat1, each = ncat2*100)), 
                cat2 = factor(rep(rep(1:ncat2, each = 100), ncat1)), 
                val = rnorm(ncat1*ncat2*100))
abox <- a %>% 
  group_by(cat1, cat2) %>% 
  summarise(ymin = min(val),
            lower = quantile(val, .25),
            middle = median(val),
            upper = quantile(val, .75),
            ymax = max(val),
            mean = mean(val))

# Plot boxplots and means with default boxplot stat and dodge width = 0.75
a %>% 
  ggplot(aes(cat1, val)) + 
  geom_boxplot(aes(fill = cat2)) + 
  geom_point(data = abox, aes(group = cat2, y = mean), 
             position = position_dodge(width = .75),
             color = 'blue', 
             size = 3)
```

![](https://i.imgur.com/z7UEirK.png)

``` r

# Plot boxplots and means with identity stat, having whiskers cover entire range of data, 
# and with dodge width = 0.75 (points misaligned)
abox %>% 
  ggplot(aes(cat1)) + 
  geom_boxplot(aes(fill = cat2, 
                   ymin = ymin, 
                   lower = lower,
                   middle = middle,
                   upper = upper,
                   ymax = ymax),
               stat = 'identity') + 
  geom_point(aes(group = cat2, y = mean), 
             position = position_dodge(width = .75),
             color = 'blue', 
             size = 3)
```

![](https://i.imgur.com/TkTUnLM.png)

Created on 2018-01-15 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by batpigandme** [comment] 2018-01-15 18:35
Whoops, sorry @karawoo, looks like you put a fix for this in https://github.com/tidyverse/ggplot2/pull/2386!

**Comment by karawoo** [comment] 2018-01-15 19:08
Box plots indeed use `position_dodge2()`. @idemockle is using `position_dodge()` for the points, though I don't think the mismatch is the source of the problem. This seems somewhat related to #2251, but off the top of my head I'm not sure why the behavior is different between the two examples @idemockle provided. #2386 is unrelated to this, though.

**Comment by batpigandme** [comment] 2018-01-15 19:15
Thanks, @karawoo.

**Comment by idemockle** [comment] 2018-01-15 20:14
Thanks for the heads up @batpigandme, I used reprex to produce the output below.  I'm not sure why, but my dodged boxplots are touching while yours aren't. I am on ggplot2 release version 2.2.1, which doesn't seem to have position_dodge2().

``` r
library(tidyverse)
#> -- Attaching packages ------------------------------------------------------- tidyverse 1.2.1 --
#> v ggplot2 2.2.1     v purrr   0.2.4
#> v tibble  1.3.4     v dplyr   0.7.4
#> v tidyr   0.7.2     v stringr 1.2.0
#> v readr   1.1.1     v forcats 0.2.0
#> -- Conflicts ---------------------------------------------------------- tidyverse_conflicts() --
#> x dplyr::filter() masks stats::filter()
#> x dplyr::lag()    masks stats::lag()

# Example data
ncat1 <- 2
ncat2 <- 3
a <- data.frame(cat1 = factor(rep(1:ncat1, each = ncat2*100)), 
                cat2 = factor(rep(rep(1:ncat2, each = 100), ncat1)), 
                val = rnorm(ncat1*ncat2*100))
abox <- a %>% 
  group_by(cat1, cat2) %>% 
  summarise(ymin = min(val),
            lower = quantile(val, .25),
            middle = median(val),
            upper = quantile(val, .75),
            ymax = max(val),
            mean = mean(val))

# Plot boxplots and means with default boxplot stat and dodge width = 0.75
a %>% 
  ggplot(aes(cat1, val)) + 
  geom_boxplot(aes(fill = cat2)) + 
  geom_point(data = abox, aes(group = cat2, y = mean), 
             position = position_dodge(width = .75),
             color = 'blue', 
             size = 3)
```

![](https://i.imgur.com/w4LEbsL.png)

``` r

# Plot boxplots and means with identity stat, having whiskers cover entire range of data, 
# and with dodge width = 0.75 (points misaligned)
abox %>% 
  ggplot(aes(cat1)) + 
  geom_boxplot(aes(fill = cat2, 
                   ymin = ymin, 
                   lower = lower,
                   middle = middle,
                   upper = upper,
                   ymax = ymax),
               stat = 'identity') + 
  geom_point(aes(group = cat2, y = mean), 
             position = position_dodge(width = .75),
             color = 'blue', 
             size = 3)
```

![](https://i.imgur.com/oAYaOpC.png)

**Comment by karawoo** [comment] 2018-01-15 21:52
`position_dodge2()` is a recent addition and is currently only available in the development version of ggplot2, which you can install with `devtools::install_github("tidyverse/ggplot2")` (though as @batpigandme showed, the width issue is broken there too).

**Comment by karawoo** [comment] 2018-02-06 20:48
They should be available in the development version. Can you run `packageVersion("ggplot2")` and see what it displays? If you're on the development version it should be 2.2.1.9000.

**Comment by roxannebeauclair** [comment] 2018-02-07 09:19
When I run `packageVersion("ggplot2")` it says the version i'm using is 2.2.1. So something is off here. 

This is the code I use:

```
# Load devtools
library(devtools)

# Move to development mode
# This installed scales and ggplot2 in the "~/R-dev" directory, 
# so CRAN version of ggplot2 is not removed.
dev_mode(TRUE)

# Install scales
install_github("hadley/scales")

# Main branch of development
install_github("hadley/ggplot2", "hadley/develop")

# load development version of ggplot2
library(dplyr)
library(ggplot2)
```
I found that code in an answer to a question on [StackOverflow](https://stackoverflow.com/questions/47746372/how-can-i-maintain-consistent-box-width-in-a-boxplot-where-factorgroup-combinat). So perhaps, that code is no longer current, or correct?

**Comment by karawoo** [comment] 2018-02-07 17:16
@roxannebeauclair try replacing `install_github("hadley/ggplot2", "hadley/develop")` with `install_github("tidyverse/ggplot2")` and see if that works.

**Comment by roxannebeauclair** [comment] 2018-02-08 08:09
@karawoo Unfortunately, that isn't working either. Still showing that '2.2.1' as my package version.

**Comment by karawoo** [comment] 2018-02-08 17:58
Ok, as this is now a separate issue from the original one posted here I'd recommend writing up a reproducible example with the [reprex](https://github.com/tidyverse/reprex) package and posting to https://community.rstudio.com/

**Comment by hadley** [comment] 2018-04-26 14:27
Unfortunately there's no way to adjust the default size of a boxplot without changing a huge number of existing plots which will make many people unhappy.

**Closed by hadley** 2018-04-26 14:27 UTC
Labels: bug
