### ISSUE TITLE
ggsave + theme_minimal background issues

### ISSUE THREAD

**Issue by cmartin** [tidyverse/ggplot2#4919] opened 2022-07-25 13:28 UTC
For some reason, using ggsave on a theme_minimal plot messes up with the background of my plots, which I need to manually specify to white to get the expected behaviour.

I'm using R 4.1.1 on Windows 10, with ggplot2 version 3.3.6.

```r
library(ggplot2)
ggplot(msleep, aes(sleep_rem, sleep_total)) + geom_point()
ggsave("white.jpg")
ggplot(msleep, aes(sleep_rem, sleep_total)) + geom_point() + theme_minimal()
ggsave("black.jpg")
ggplot(msleep, aes(sleep_rem, sleep_total)) + geom_point() + theme_minimal()
ggsave("white2.jpg", bg = "white")

```

As of last week, I never had to specify the bg color in ggsave to have the white one.

**Comment by yutannihilation** [comment] 2022-07-25 14:09
Thanks, confirmed. Strange, this seems the same issue as https://github.com/tidyverse/ggplot2/issues/4604 and I thought this was fixed on ragg's side...?

``` r
library(ggplot2)
jpg <- tempfile(fileext = ".jpg")
png <- tempfile(fileext = ".png")

p <- ggplot(msleep, aes(sleep_rem, sleep_total)) + geom_point() + theme_minimal()

print(p)
#> Warning: Removed 22 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/E6Xkre5.png)

``` r

ggsave(jpg)
#> Saving 7 x 5 in image
#> Warning: Removed 22 rows containing missing values (`geom_point()`).
knitr::include_graphics(jpg)
```

![](https://i.imgur.com/bbJVxQf.jpg)

``` r

ggsave(png)
#> Saving 7 x 5 in image
#> Warning: Removed 22 rows containing missing values (`geom_point()`).
knitr::include_graphics(png)
```

![](https://i.imgur.com/Dz9juf7.png)

<sup>Created on 2022-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment] 2022-07-25 14:26
Yes, looks like the same issue as #4604.

@cmartin As a general rule, though, if you need a specific background color you should specify it. `theme_minimal()` has a transparent background, so technically the background color is undefined. (I've seen all sorts of background colors on images with transparent background. Try looking at an image with transparent background on Twitter.) And, when working with transparency, never save as jpg, which doesn't support transparency. Otherwise, again, the background color is technically undefined.

**Comment by cmartin** [comment] 2022-07-25 14:37
Oh, thanks for the heads-up @clauswilke . 

theme_minimal has been my "go to" theme for years and I had no idea the background color was undefined.

I'll see if I can open another ticket to better document that behavior. As of now, the background is solid white in the documentation renders : https://ggplot2.tidyverse.org/reference/ggtheme.html. (i.e. the gray background from the web page is not visible through the plot).

**Comment by thomasp85** [comment] 2022-08-02 08:02
I have just pushed another fix to ragg to fix this issue once and for all.

**Closed by thomasp85** 2022-08-02 08:02 UTC

**Comment by yutannihilation** [comment] 2022-08-02 08:35
Thanks for fixing!
