### ISSUE TITLE
Theme option to align the legend to the plot instead of the panel

### ISSUE THREAD

**Issue by sambtalcott** [tidyverse/ggplot2#5959] opened 2024-06-27 17:15 UTC
I often use the `plot.title.position = "plot"` argument to `theme()` to get my plot's title to align to the plot rather than the panel. This is especially helpful when the y-axis labels are long.

I sometimes want to add a horizontal legend to the top of charts like this. However, there is no current way to align the legend to the plot in the same way as the title. You can either left-align to the panel, which leaves a gap that looks weird compared to the nicely aligned title/subtitle:

```r
diamonds |> 
  dplyr::count(cut, color) |> 
  ggplot(aes(n, cut, fill = color)) + 
  geom_col(position = "fill") + 
  labs(title = "Diamonds by Color and Cut",
       subtitle = "An example chart",
       fill = NULL, y = NULL, x = NULL) + 
  guides(fill = guide_legend(reverse = TRUE, nrow = 1)) + 
  ggthemes::theme_hc() + 
  theme(plot.title.position = "plot",
        legend.direction = "horizontal",
        legend.position = "top",
        legend.justification = "left")
```
![image](https://github.com/tidyverse/ggplot2/assets/57906601/0056304b-a7b8-4ce6-b8aa-17e0a930d34e)

Or you can create manual space in the subtitle and tweak the position of the legend just right to get it into place:

```r
diamonds |> 
  dplyr::count(cut, color) |> 
  ggplot(aes(n, cut, fill = color)) + 
  geom_col(position = "fill") + 
  labs(title = "Diamonds by Color and Cut",
       subtitle = "An example chart\n\n",
       fill = NULL, y = NULL, x = NULL) + 
  guides(fill = guide_legend(reverse = TRUE, nrow = 1)) + 
  ggthemes::theme_hc() + 
  theme(plot.title.position = "plot",
        legend.direction = "horizontal",
        legend.position = c(-0.18, 1.1),
        legend.justification = "left")
```
![image](https://github.com/tidyverse/ggplot2/assets/57906601/87e51449-675b-4fd4-9b42-a4a923cd9cd6)

The second option achieves the look I want, but it requires trial-and-error to get the right numbers for `legend.position`, and any change to the size of the output messes up the alignment.

I would like to be able to specify a `plot.legend.position` similar to `plot.title.position` that would align the legend to the plot instead of the panel:

```r
theme(plot.title.position = "plot",
      plot.legend.position = "plot",
      legend.direction = "horizontal",
      legend.position = "top",
      legend.justification = "left")
```

**Comment by teunbrand** [comment] 2024-06-27 17:26
I'm closing this as a duplicate of #4020.
This was introduced in 3.5.0 as `legend.location = "plot"`.
You might like to combine this with `legend.margin = margin(l = 0)`

``` r
library(tidyverse)

diamonds |> 
  dplyr::count(cut, color) |> 
  ggplot(aes(n, cut, fill = color)) + 
  geom_col(position = "fill") + 
  labs(title = "Diamonds by Color and Cut",
       subtitle = "An example chart",
       fill = NULL, y = NULL, x = NULL) + 
  guides(fill = guide_legend(reverse = TRUE, nrow = 1)) + 
  ggthemes::theme_hc() + 
  theme(plot.title.position = "plot",
        legend.direction = "horizontal",
        legend.position = "top",
        legend.justification = "left", 
        legend.location = "plot")
```

![](https://i.imgur.com/UlvDzWF.png)

<sup>Created on 2024-06-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Closed by teunbrand** 2024-06-27 17:26 UTC

**Comment by sambtalcott** [comment] 2024-07-01 12:20
Thank you! Didn't realize this had already been implemented.
