### ISSUE TITLE
NA drops out of the legend where a named pal is added to `scale_colour_manual`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5214] opened 2023-03-02 20:55 UTC
``` r
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot() +
  geom_point(aes(
    x = bill_depth_mm, 
    y = body_mass_g, 
    col = sex
  )) +
  scale_color_manual(values = c("red", "blue"))
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/65nEey4.png)

``` r

penguins |>
  ggplot() +
  geom_point(aes(
    x = bill_depth_mm, 
    y = body_mass_g, 
    col = sex
  )) +
  scale_color_manual(values = c("male" = "red", "female" = "blue"))
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/ZAyP0El.png)

<sup>Created on 2023-03-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by linzi-sg** [comment] 2023-04-02 13:40
I thought this is expected behaviour. Since no explicit breaks are specified in either case, scale limits are used to infer default breaks, and ```ggplot2:::manual_scale`, which is called by `scale_colour_manual` underneath the hood, defines limits differently when values are named:

```
> ggplot2:::manual_scale
function (aesthetic, values = NULL, breaks = waiver(), ..., limits = NULL) 
{
   # omitted for brevity
    if (is.null(limits) && !is.null(names(values))) {
        limits <- function(x) intersect(x, names(values)) %||%     
            character()
    }
   # omitted for brevity
    discrete_scale(aesthetic, "manual", pal, breaks = breaks, 
        limits = limits, ...)
}
```

If the values vector wasn't named, limits (& hence breaks) will be inferred from the full range of mapped values, in this case `c("female", "male", "NA")`. When the vector is named, only the names found in the vector will be retained, i.e. `c("female", "male")`.

**Comment by teunbrand** [comment] 2023-04-05 17:26
Indeed, named values imply populating the `limits` argument when it hasn't been set to something. So I think everything is working as intended.

**Closed** 2023-05-22 18:13 UTC
Labels: scales :snake:

**Comment by jeraldnoble** [comment] 2024-07-25 19:09
> I thought this is expected behaviour. Since no explicit breaks are specified in either case, scale limits are used to infer default breaks, and ```ggplot2:::manual_scale`, which is called by `scale_colour_manual` underneath the hood, defines limits differently when values are named:
> 
> ```
> > ggplot2:::manual_scale
> function (aesthetic, values = NULL, breaks = waiver(), ..., limits = NULL) 
> {
>    # omitted for brevity
>     if (is.null(limits) && !is.null(names(values))) {
>         limits <- function(x) intersect(x, names(values)) %||%     
>             character()
>     }
>    # omitted for brevity
>     discrete_scale(aesthetic, "manual", pal, breaks = breaks, 
>         limits = limits, ...)
> }
> ```
> 
> If the values vector wasn't named, limits (& hence breaks) will be inferred from the full range of mapped values, in this case `c("female", "male", "NA")`. When the vector is named, only the names found in the vector will be retained, i.e. `c("female", "male")`.

This behavior seems to have changed in ggplot2 3.5.1

    if (is.null(limits) && !is.null(names(values))) {
        force(aesthetic)
        limits <- function(x) {
            x <- intersect(x, c(names(values), NA)) %||% character()
            if (length(x) < 1) {
                cli::cli_warn(paste0("No shared levels found between {.code names(values)} of the manual ",
                  "scale and the data's {.field {aesthetic}} values."))
            }
            x
        }
    }

I now get NA in my legend for points that are uncolored in my plot. I need these points in my plot.

**Comment by teunbrand** [comment] 2024-07-25 20:35
@jeraldnoble if you think that is a bug, could you open a new issue with an example/reprex?
