### ISSUE TITLE
Warning message with `stat_function()` when using `purrr::map2`

### ISSUE THREAD

**Issue by yuw444** [tidyverse/ggplot2#5498] opened 2023-10-26 20:50 UTC
I found a problem with `stat_function()`, it produces some warning messages although the result is as expected. 

Here is the code to reproduce the bug:

```r
library(ggplot2)
library(purrr)
data(mtcars)
temp <- function(y) {
    function(x) y / x
}

fun_list <- map(1:3 * 10^4, ~ temp(.x))

p <- ggplot(
    mtcars,
    aes(disp, hp, fill = wt)
) +
    geom_point(shape = 21, size = 3, aes(fill= factor(vs))) +
    purrr::map2(
        fun_list,
        c("4", "6", "8"),
        ~ stat_function(
            fun = .x,
            aes(color = .y)
        )
    )

p
```

Below is the warning message
```
Warning messages:
1: The following aesthetics were dropped during statistical transformation: fill
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor? 
2: The following aesthetics were dropped during statistical transformation: fill
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor? 
3: The following aesthetics were dropped during statistical transformation: fill
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor?
```

**Comment by teunbrand** [comment] 2023-10-26 21:15
More minimal reprex to reproduce warning:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.3.1

ggplot(mtcars, aes(disp, hp, fill = wt)) +
  geom_point() +
  stat_function(fun = ~ .x)
#> Warning: The following aesthetics were dropped during statistical transformation: fill
#> ℹ This can happen when ggplot fails to infer the correct grouping structure in
#>   the data.
#> ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
#>   variable into a factor?
```

![](https://i.imgur.com/TW0nRMG.png)

<sup>Created on 2023-10-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In any case, I think the warnings are appropriate, as you've specified `fill =wt` at the top-level `ggplot()` call, which will result in non-constant columns within a group that the stat applies to.

**Comment by clauswilke** [comment] 2023-10-27 19:39
I tend to agree that the warning is appropriate even if it is a bit confusing here. The code is asking `stat_function()` to do something that it cannot do (vary the fill color along the data points), and so this triggers a warning. It's difficult to write these warnings in such a way that they correctly describe the true underlying issue in all cases.

**Comment by teunbrand** [comment] 2023-10-27 21:24
Yeah agreed. Because it is working as intended, I'll close this as 'not a bug'.

**Closed by teunbrand** 2023-10-27 21:24 UTC

**Comment by yuw444** [comment] 2023-10-27 22:47
Thanks for the insight. Seems like I should put fill=wt inside of geom_point().
