### ISSUE TITLE
facet_wrap() doesn't play well with expressions in facets. 

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#2123] opened 2017-05-05 18:41 UTC
`facet_wrap()` doesn't get along with faceting by function. It works sometimes, but not always and also the error messages are not informative. For example, it breaks if I add annotations. This is a minimal example of what I'm talking about:
``` r
library(ggplot2)
library(lubridate)
library(stringi)

dates <- as.Date(c("2015-01-01", "2016-03-01"))
df <- expand.grid(x = 1:10, date = dates)
df$y <- rnorm(nrow(df))
df$yearnum <- year(df$date)

g1 <- ggplot(df, aes(x, y)) +
    geom_line()
g2 <- g1 + annotate(geom = "text", x = 5, y = 0, label = "test") 


g1 + facet_wrap(~year(date))    # works
```

![](http://i.imgur.com/lHebUhX.png)

``` r
g2 + facet_wrap(~year(date))    # error
#> Error in as.POSIXlt.default(x, tz = tz(x)): do not know how to convert 'x' to class "POSIXlt"
g2 + facet_wrap(~yearnum)    # works fine
```

![](http://i.imgur.com/fnf2yWU.png)

Is not only a problem with date

``` r
g1 + facet_wrap(~sqrt(yearnum))    # works
```

![](http://i.imgur.com/2q5jYwQ.png)

``` r
g2 + facet_wrap(~sqrt(yearnum))    # error
#> Error in eval(var, envir = data, enclos = env): object 'yearnum' not found
```

You get the same behaviour if you use geoms

``` r
df2 <- data.frame(x = 1:10, y = rnorm(10))
g1 + geom_point(data = df2) + facet_wrap(~yearnum)    # works
```

![](http://i.imgur.com/Zb8N7U9.png)

``` r
g1 + geom_point(data = df2) + facet_wrap(~year(date))    # error
#> Error in as.POSIXlt.default(x, tz = tz(x)): do not know how to convert 'x' to class "POSIXlt"
```

**Comment by hadley** [comment] 2017-10-30 20:02
Duplicate of #2091

**Closed by hadley** 2017-10-30 20:02 UTC
Labels: bug, facets
