### ISSUE TITLE
strip.clip = "on" only works to the left?

### ISSUE THREAD

**Issue by CGlemser** [tidyverse/ggplot2#5238] opened 2023-03-20 16:53 UTC
Hi everyone,

I found a problem with the strip.clip option in theme.

What I am trying to do is only showing every second facet label on the strip to make the plot look cleaner in case there are a lot of facets. I thus set every second label to "" and provided this labeller to the plot and set strip.clip to "off" to allow for clipping of the labels.

I created some toy dates and used their years as facets. The plot is left empty since what I am struggling with is the strip. It looks like the clipping only works the left and at the borders, but not throughout the strip? I would have expected to be able to see all labels completely in the following image:

**strip.clip = "on":**
![image](https://user-images.githubusercontent.com/20644718/226410700-f31d5c3a-6203-4317-b523-ac13d4c7a4f5.png)

**strip.clip = "off":**
![image](https://user-images.githubusercontent.com/20644718/226411454-d41060bf-4a6d-492a-809a-9f01e8575438.png)

```r
library(data.table)
library(lubridate)

example <- data.table::data.table(
  dateIncurred = c(
    as.Date("2020-01-01"), 
    as.Date("2020-02-01"),
    as.Date("2020-03-01"), 
    as.Date("2020-04-01"), 
    as.Date("2020-05-01"), 
    as.Date("2020-06-01"), 
    as.Date("2020-07-01"), 
    as.Date("2020-08-01"), 
    as.Date("2020-09-01"), 
    as.Date("2020-10-01"), 
    as.Date("2020-11-01"), 
    as.Date("2020-12-01"),
    as.Date("2020-04-03"),
    as.Date("2020-05-03"),
    as.Date("2020-06-03"),
    as.Date("2020-07-03"),
    as.Date("2020-08-03"),
    as.Date("2020-09-03"),
    as.Date("2020-10-03"), 
    as.Date("2020-11-03"), 
    as.Date("2020-12-03"),
    as.Date("2020-07-15"),
    as.Date("2020-08-15"), 
    as.Date("2020-09-15"),
    as.Date("2020-10-15"), 
    as.Date("2020-11-15"),
    as.Date("2020-12-15"),
    as.Date("2020-10-20"),
    as.Date("2020-11-20"), 
    as.Date("2020-12-20")
  )
)

example <- data.table::data.table(dateIncurred = dates)

example[, year := lubridate::year(dateIncurred)]

yearsLbls <- example[, unique(year)]
yearsLbls[seq(2, length(yearsLbls), 2)] <- ""
names(yearsLbls) <- example[, unique(year)]

ggplot2::ggplot(data = example) +
  ggplot2::facet_grid(. ~ year, switch = "x", labeller = ggplot2::labeller(year = yearsLbls)) +
  ggplot2::theme_bw() +
  ggplot2::theme(strip.placement = "outside",
                 strip.clip = "off",  # years shouldn't be clipped by strip dimensions
                 strip.background = ggplot2::element_rect(colour = NA),
                 panel.spacing.x = ggplot2::unit(0, "lines"))

```

**Comment by teunbrand** [comment] 2023-03-20 17:37
The strip background is overlapping parts of your labels, thereby implicitly clipping the labels. The `strip.clip` setting affects the clipping mask applied to the text, but doesn't preclude overlaps.

I couldn't reproduce your example, so here is a facsimile:

``` r
library(ggplot2)

df <- economics
df$year <- lubridate::year(df$date)
df <- subset(df, year >= 1970 & year <= 1990)

years <- setNames(unique(df$year), unique(df$year))
years[seq(2, length(years), 2)] <- ""

p <- ggplot(df) +
  facet_grid(~ year, labeller = labeller(year = years)) +
  theme(strip.text = element_text(size = 12),
        panel.spacing.x = unit(0, "lines"))
```

Just showing that with `strip.clip = "on"`, we see clipping.

``` r
p + theme(strip.clip = "on")
```

![](https://i.imgur.com/dbtlMvK.png)

Confirming the issue that labels appear to be clipped with `strip.clip = "off"`.

``` r
p + theme(strip.clip = "off")
```

![](https://i.imgur.com/9IbSkmW.png)

Showing that clipping doesn't occur when strip backgrounds are turned off.

``` r
p + theme(strip.clip = "off", strip.background = element_blank())
```

![](https://i.imgur.com/ejko2ga.png)

<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment] 2023-04-05 17:23
I think everything works as intended here, so I'll close this issue.

**Closed by teunbrand** 2023-04-05 17:23 UTC
