### ISSUE TITLE
Scaling of plot depends on letter shapes in titles

### ISSUE THREAD

**Issue by joergtrojan** [tidyverse/ggplot2#2476] opened 2018-03-08 13:32 UTC
When trying to create two different graphs with identical dimensions, I stumbled across this problem.

# Expected behaviour
Scaling of a graph should not depend on which letters are used in main or axis titles.

# Actual behaviour
Using g, j, p, q, or y in a title leads to different vertical scaling of the graph.

# Suspected cause
The space calculation is probably not based on the font baseline but rather on the absolute letter size. I guess this is a general issue with element_text().

```r
# y-scaling should look exactly the same, but doesn't.
ggplot(mtcars, aes(mpg, wt)) + geom_point() + ggtitle("Title with an h")
ggplot(mtcars, aes(mpg, wt)) + geom_point() + ggtitle("Title with a g")
```

**Comment by thomasp85** [comment] 2018-03-08 14:11
This is related to the #2471 PR

**Comment by hadley** [comment] 2018-04-27 13:55
Duplicate of #2288

**Closed by hadley** 2018-04-27 13:55 UTC
