### ISSUE TITLE
Bug: Changing the legend.text margin t or b changes legend.key.height

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5682] opened 2024-02-07 02:23 UTC
This occurs with 3.4.4 as well as the DEV version I'm using

``` r
library(tidyverse)
library(palmerpenguins)

p <- penguins |> 
  ggplot() +
  geom_histogram(
    aes(x = flipper_length_mm, fill = sex)
  )

p
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_bin()`).
```

![](https://i.imgur.com/9pbAfQS.png)

``` r

p +
  theme(
    legend.text = ggplot2::element_text(margin = ggplot2::margin(t = 20, b = 20)),
  )
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_bin()`).
```

![](https://i.imgur.com/so52BSa.png)

<sup>Created on 2024-02-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment] 2024-02-07 13:04
Hi David, this seems to be a duplicate of #3669, so I'm closing this issue in favour of that one to keep discussion in one place.

**Comment by davidhodge931** [comment] 2024-02-07 18:32
Oh whoops, thanks

**Closed** 2024-02-07 18:32 UTC
