### ISSUE TITLE
Swedish characters incorrectly shown in ggplot title

### ISSUE THREAD

**Issue by pgmj** [tidyverse/ggplot2#5839] opened 2024-04-12 10:38 UTC
Swedish characters åäö are not displayed correctly when shown in `labs(title)` using ggplot 3.5.0. The dots/circle above the characters seem to be shifted to the right, half way to the next character. This is also reproducible for `facet_wrap()` labels. The characters work as expected in the legend box and on the x axis.

<img width="733" alt="Screenshot 2024-04-12 at 12 34 02" src="https://github.com/tidyverse/ggplot2/assets/31865392/bf39ebfb-7bdd-432a-9c56-2d41c1a929c1">

``` r
library(tidyverse)
df_plot <- data.frame(
  stringsAsFactors = FALSE,
  itemnr = c("who5_1", "who5_1", "who5_1", "who5_1", "who5_1"),
  category = c("Ibland",
               "Mindre än halva tiden","Mer än halva tiden","Mestadels","Hela tiden"),
  n = c(4L, 4L, 15L, 42L, 12L),
  Procent = c(5.19, 5.19, 19.48, 54.55, 15.58),
  item = c("Jag har känt mig glad och på gott humör",
           "Jag har känt mig glad och på gott humör","Jag har känt mig glad och på gott humör",
           "Jag har känt mig glad och på gott humör",
           "Jag har känt mig glad och på gott humör")
)

header <- df_plot %>% 
  filter(itemnr == "who5_1") %>% 
  slice(1) %>% 
  pull(item)

df_plot %>% 
  filter(itemnr == "who5_1") %>% 
  ggplot(aes(x = category, y = Procent, fill = category)) +
  scale_y_continuous(limits = c(0,NA)) +
  scale_x_discrete() + 
  geom_col() +
  geom_text(aes(label = n), color = "darkgrey",
            size = 2.2,
            position = position_dodge(width = 0.9),
            vjust = -0.24) +
  scale_fill_viridis_d(labels = ~ str_wrap(.x, width = 9)) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  labs(title = header)
```

**Comment by teunbrand** [comment] 2024-04-12 12:09
The rendering of text is controlled by the graphics device.
You can choose a graphics device in `ggsave()` or in RStudio in the Tools > Global Options > General > Graphics tab.
As an example, the CairoPNG device renders text horribly as in your example.

``` r
library(tidyverse)
df_plot <- data.frame(
  stringsAsFactors = FALSE,
  itemnr = c("who5_1", "who5_1", "who5_1", "who5_1", "who5_1"),
  category = c("Ibland",
               "Mindre än halva tiden","Mer än halva tiden","Mestadels","Hela tiden"),
  n = c(4L, 4L, 15L, 42L, 12L),
  Procent = c(5.19, 5.19, 19.48, 54.55, 15.58),
  item = c("Jag har känt mig glad och på gott humör",
           "Jag har känt mig glad och på gott humör","Jag har känt mig glad och på gott humör",
           "Jag har känt mig glad och på gott humör",
           "Jag har känt mig glad och på gott humör")
)

header <- df_plot %>% 
  filter(itemnr == "who5_1") %>% 
  slice(1) %>% 
  pull(item)

plot <- df_plot %>% 
  filter(itemnr == "who5_1") %>% 
  ggplot(aes(x = category, y = Procent, fill = category)) +
  scale_y_continuous(limits = c(0,NA)) +
  scale_x_discrete() + 
  geom_col() +
  geom_text(aes(label = n), color = "darkgrey",
            size = 2.2,
            position = position_dodge(width = 0.9),
            vjust = -0.24) +
  scale_fill_viridis_d(labels = ~ str_wrap(.x, width = 9)) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  labs(title = header)

tmp <- tempfile(fileext = ".png")
ggsave(tmp, plot, device = Cairo::CairoPNG, width = 700, height = 500, limitsize = FALSE, dpi = 100)
knitr::include_graphics(tmp)
```

<img src="https://i.imgur.com/WuOf3QZ.png" width="700" />

While the agg_png device renders the text as intended (I believe, I'm not familiar with Swedish to judge competently).

``` r
tmp <- tempfile(fileext = ".png")
ggsave(tmp, plot, device = ragg::agg_png)
#> Saving 7 x 5 in image
knitr::include_graphics(tmp)
```

<img src="https://i.imgur.com/aAHAoAK.png" width="2100" />

<sup>Created on 2024-04-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

In any case, this is a device issue that ggplot2 cannot solve. The instructions for a plot are sent to {grid} and {grid} interacts with graphics devices, so it is 2 layers of the graphics stack removed from ggplot2's control. For that reason, I'll close this issue.

**Closed by teunbrand** 2024-04-12 12:09 UTC

**Comment by pgmj** [comment] 2024-04-12 12:52
Ok, thanks, that second one looks good. I render with Quarto, which has worked well previously. But I suppose I need to file this report with them instead. Appreciate the quick and helpful response! I changed the default setting in Rstudio so at least the manually generated figures look good now :)

**Comment by pgmj** [comment] 2024-04-15 07:13
Thank you again! That solution works for my Quarto output.
