### ISSUE TITLE
duplicate axis tickmark alignment precision problem in ggplot2 by using dup_axis()?

### ISSUE THREAD

**Issue by dbo-usbr** [tidyverse/ggplot2#2283] opened 2017-10-05 20:39 UTC
In using dup_axis(), it seems the precision of the tick mark and label alignment can be slightly off (compare the horizontal position of the "0" in the upper, duplicate axis with the lower)

```r
scale_x_continuous(expand = c(0.01, 0.01), limits = c(-550, 1000), 
  breaks = c(-550,-500,-400,-300,-200,-100,-50,-25, 0,25,50, 100, 200, 300, 400, 500, 750, 1000),
  labels = c("", "500", "400", "300", "200","100","50","25", "0","25","50", "100", "200", "300", "400", "500", "750", "1 maf"), 
                     sec.axis = dup_axis()) 
```
![dupaxis](https://user-images.githubusercontent.com/13547204/31251319-661f656e-a9d2-11e7-8301-f27584678f3f.png)
https://stackoverflow.com/questions/46591926/duplicate-axis-tickmark-alignment-precision-in-ggplot2-by-using-dup-axis

**Comment by hadley** [comment] 2017-10-30 17:31
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-11-06 19:52
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-06 19:52 UTC
Labels: bug, reprex, scales
