### ISSUE TITLE
faceting by a character variable with drop = F produces error where there are NA values

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5401] opened 2023-08-28 23:20 UTC
<img width="500" alt="image" src="https://github.com/tidyverse/ggplot2/assets/55065152/eea7a2fb-0a82-4eaa-9f77-29da24adc0f8">

**Comment by yutannihilation** [comment] 2023-09-03 04:03
Closing as I cannot reproduce the error (both with 3.4.3 and with the latest GitHub version).

``` r
library(palmerpenguins)
library(tidyverse)

penguins |>
  add_row(flipper_length_mm = 220, body_mass_g = 6000) |>
  ggplot() +
  geom_point(aes(x = flipper_length_mm, y = body_mass_g)) +
  facet_wrap(~sex, drop = FALSE)
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/koI5RwJ.png)

<sup>Created on 2023-09-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed by yutannihilation** 2023-09-03 04:03 UTC

**Comment by davidhodge931** [comment] 2023-09-03 21:31
Whoops, must have been something wrong at my end - sorry!
