### ISSUE TITLE
Consider making `add_ggplot` as an S3 generic

### ISSUE THREAD

**Issue by emitanaka** [tidyverse/ggplot2#4743] opened 2022-02-27 05:02 UTC
Would it be possible to make `add_ggplot` as an S3 generic? 
Currently we have to resort to overwriting `"+.gg"`  if we want to adopt a different method based on the class of `e1`, e.g. [`GGally`](https://github.com/ggobi/ggally/blob/master/R/ggpairs_add.R#L46:L69) is a prime example of this. This allows developers to fix issues like #4304 .

The fix, as below, will be relatively simple, but the downside is that you do have to export another function.

```r
#' @export
add_ggplot <- function(p, object, objectname) {
  UseMethod("add_ggplot")
}

#' @export
add_ggplot.ggplot <- function(p, object, objectname) {
  if (is.null(object)) return(p)
  
  p <- plot_clone(p)
  p <- ggplot_add(object, p, objectname)
  set_last_plot(p)
  p
}
```

**Comment by yutannihilation** [comment] 2022-02-27 16:45
Just a quick note. We had some discussions on this topic, but couldn't reach a consensus, if I remember correctly.

* #3815
* #3818
* #3986

I still believe this should be solved double dispatch (probably with vctrs integration), but, considering I (or we) have failed to implement it for this 2 years, we might need to rethink.

**Comment by hadley** [comment] 2022-03-14 15:48
I think @emitanaka's proposal is a reasonable fix. [R7](http://github.com/RConsortium/OOP-WG) should eventually get to the point where the double dispatch will just work but that's at least a few years away, and using vctrs would be a bit of a hack since ggplot2 objects aren't vectors. @schloerke's PR looks good to be, so I'll going to close this issue as a duplicate of #3986.

**Closed by hadley** 2022-03-14 15:48 UTC
