### ISSUE TITLE
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  :    Viewport has zero dimension(s)

### ISSUE THREAD

**Issue by greymatter003** [tidyverse/ggplot2#5097] opened 2022-12-08 20:39 UTC
Creating a plot of LBJ career stats. When I run last bit of code, p <- p + labs, it returns the error:
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
I am new to R and programming, please try to keep explanations simple. Appreciate it!

##Get columns and pivot wider
p <- df_stats %>%
  ggplot(aes(x = paste0(Season," ",Team,"\n ",GP, "GP"),
            y = Stat_val,
            label=Stat_cat)) +
 ## Add points
  geom_point(aes(fill = Stat_cat),
             size = 3,
             color = 'black',
             shape = 21)

### Add lines
p  <- p + geom_line(aes(group = Stat_cat), linewidth=0.05)

### Add Labels
p <- p + geom_text_repel(data = filter(df_stats, Season == last(Season)),
                         aes(label = Stat_cat),
                         size          = 2.5,
                         box.padding   = 0.2,
                         point.padding = 0.2,
                         force         = 50,
                         segment.size  = 0.2,
                         colour        = "black",
                         segment.color = "grey50")

p <- p + scale_y_continuous(breaks = seq(0, ceiling(max(df_stats$Stat_val,na.rm = TRUE)), 5))

p <- p + labs(title = paste0(player," Career Stats"),
              subtitle = paste0(min(df_stats$Season)," to ",max(df_stats$Season)),
              x = "",
              y = "",
              caption = c("Ryan via Sweep Sports Analytics"))

---

**Comment by yutannihilation** [comment] 2022-12-11 02:39
Since you use ggrepel, this might be related: https://github.com/slowkow/ggrepel/issues/113. I'm not fully sure if this isn't the problem that needs to be fixed on ggplot2's side, but this sort of question is a better fit for [RStudio Community](https://community.rstudio.com), especially if you are new to R. Please ask there with a minimal reproducible example (I mean, `df_stats` is not reproducible) first. We use this issue tracker for bug reports and feature requests.

**Closed by yutannihilation** 2022-12-11 02:39 UTC
