### ISSUE TITLE
Release ggplot2 3.2.1

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#3470] opened 2019-08-05 07:05 UTC
Prepare for release: 
 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [ ] `revdepcheck::revdep_check(num_workers = 4)` 
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) 
* [x] Polish pkgdown reference index 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('patch')` 
* [x] Update `cran-comments.md` 
* [ ] `devtools::submit_cran()` 
* [ ] Approve email 
 
Wait for CRAN... 
 
* [ ] Accepted :tada: 
* [ ] `usethis::use_github_release()` 
* [ ] `usethis::use_dev_version()` 
* [ ] Tweet

**Comment by thomasp85** [comment] 2019-08-05 07:09
@Hadley @clauswilke @karawoo @yutannihilation @paleolimbot 

This is an issue tracking the 3.2.1 hotfix release. The release will be forked from the current 3.2.0 release as the development version contains too much experimental code. Please tag any regression issues serious new ones into the appropriate milestone. We will begin the release process in a week hopefully

**Comment by Sergioleon85** [comment] 2019-08-06 10:35
@thomasp85 
First post from my side on this platform.
We are having troubles to get ggplot2 installed

Tried also "install.packages("tidyverse")"
Getting the next response:

 There are binary versions available but the source versions are later:
            binary source needs_compilation
fansi        0.2.2  0.4.0              TRUE
pillar       1.2.1  1.4.2             FALSE
glue         1.2.0  1.3.1              TRUE
tibble       1.4.2  2.1.3              TRUE
tidyselect   0.2.4  0.2.5              TRUE
dplyr        0.7.4  0.8.3              TRUE
purrr        0.2.4  0.3.2              TRUE
rlang        0.2.0  0.4.0              TRUE
Rcpp       0.12.16  1.0.2              TRUE
progress     1.1.2  1.2.2             FALSE
broom        0.4.4  0.5.2             FALSE
dbplyr       1.2.1  1.4.2             FALSE
forcats      0.3.0  0.4.0             FALSE
ggplot2      2.2.1  3.2.0             FALSE
haven        1.1.1  2.1.1              TRUE
modelr       0.1.1  0.1.4             FALSE
readxl       1.1.0  1.3.1              TRUE
reprex       0.1.2  0.3.0             FALSE
rvest        0.3.2  0.3.4             FALSE

Any idea?
Thank you in advance!

**Comment by batpigandme** [comment] 2019-08-06 10:39
Hi @Sergioleon85 ,
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by Sergioleon85** [comment] 2019-08-06 16:49
> Hi @Sergioleon85 ,
> This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

@batpigandme 
Sure thing, no problem.
Not sure where I was supposed to ask about it.
Thanks for the links.

**Comment by yutannihilation** [comment] 2019-08-13 02:38
I'm closing this since this seems a duplicate of #3479. Thanks Thomas for handling the process!

(One thing left is to build the pkgdown site for this release, I'll do it later in the same way as https://github.com/tidyverse/ggplot2/issues/3191#issuecomment-473974456.)

**Closed by yutannihilation** 2019-08-13 02:38 UTC
