### ISSUE TITLE
"scale_id must not be NA" for facet_grid in CentOS, not in Windows

### ISSUE THREAD

**Issue by lynn242** [tidyverse/ggplot2#4901] opened 2022-07-07 13:00 UTC
Hello!

We have a weird issue with ggplot2, stating a "scale_id must not be NA" error when running the code from CentOS, which we could not reproduce when running it in Windows (same R-version etc, see screenshots). We have our pipelines running in CentOS, so would need to get it working there. **Any fix or potential workaround would be greatly appreciated!**

I provide here a code snippet + data to reproduce this (it does not happen with all data frames, but with this one I consistently had the error):

`library(ggplot2)`
`lt <- read.table("lt.tsv", header = TRUE, sep = '\t')`
`r <- ggplot(lt, aes(x=xvalue, y=yvalue)) + theme(axis.title.x=element_blank(), axis.title.y=element_blank()) + facet_grid(ylab~xlab, scales = "free") + theme(aspect.ratio=1)`
`r`

[lt.txt](https://github.com/tidyverse/ggplot2/files/9063741/lt.txt)

CentOS:
![image](https://user-images.githubusercontent.com/81355666/177777020-d127fac7-a46c-4f09-84f1-d4b6cece8d0d.png)

Windows (RStudio):
![image](https://user-images.githubusercontent.com/81355666/177777080-d8a81903-3ab1-4229-b4f0-65280e5522af.png)

Cheers!

**Comment by smouksassi** [comment] 2022-07-07 13:09
https://stackoverflow.com/questions/66361247/error-with-ggplot-facet-wrap-error-scale-id-must-not-be-na
please provide a reproducible example
it is not clear where is the error and you have variable names that are the same name as function names e.g. ylab and xlab try to rename to something else to avoid confusion and clashes

**Comment by yutannihilation** [comment] 2022-07-07 13:55
Yeah, I wish the example is a bit more minimal, i.e. which doesn't require us to download your data, but it's definitely reproducible. Thanks for your effort.

While we don't know the cause, as it succeeds on other OSes than CentOS, I guess this isn't ggplot2's fault so there's not much we can do, sorry. In general, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.

Please feel free to file a new issue when it turns out it's something needs to be fixed on ggplot2's side!

``` r
library(ggplot2)

lt <- read.table("~/../Downloads/lt.txt", header = TRUE, sep = "\t")
ggplot(lt, aes(x = xvalue, y = yvalue)) +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank()) +
  facet_grid(ylab ~ xlab, scales = "free") +
  theme(aspect.ratio = 1)
```

![](https://i.imgur.com/NMC6vgz.png)

<sup>Created on 2022-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Closed by yutannihilation** 2022-07-07 13:55 UTC
