### ISSUE TITLE
geom_histogram() throwing warning with use of 'weight' aesthetic

### ISSUE THREAD

**Issue by kaybenleroll** [tidyverse/ggplot2#2204] opened 2017-07-13 07:46 UTC
ggplot2 version: 2.2.1

While it appears to be creating the correct plot, using the `weight` aesthetic with `geom_histogram()` causes the throwing of a warning message

`Warning: Ignoring unknown aesthetics: weight
`

A reproducible example can be found from using the `midwest` data in the ggplot2 (2e) book:

```r
ggplot(midwest, aes(percbelowpoverty)) +
    geom_histogram(aes(weight = poptotal), binwidth = 1) +
    ylab("Population (1000s)")
```

**Comment by karawoo** [comment] 2017-07-13 21:29
I can't reproduce this unfortunately. Could you please use the [reprex](https://github.com/tidyverse/reprex) package to create your reproducible example and include a call to `sessionInfo()`? That will help me diagnose the problem.

**Comment by karawoo** [comment] 2017-07-20 20:24
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by karawoo** 2017-07-20 20:24 UTC
Labels: reprex

**Comment by aschersleben** [comment] 2017-08-28 07:50
Hello, I'd like to re-open this issue, because I get the same warning message as described above by @kaybenleroll when using the ```weight``` aesthetic with ```geom_histogram()```. Below, you can find a reprex directly taken from the help page ```?geom_histogram()```. The second histogram obviously uses the ```weight``` aesthetic, so this is just about the warning message...


``` r
library(ggplot2)
library(ggplot2movies)
m <- ggplot(movies, aes(rating))
m + geom_histogram(binwidth = 0.1) + ylab("votes")
```

![](http://i.imgur.com/0WC4bNF.png)

``` r
m + geom_histogram(aes(weight = votes), binwidth = 0.1) + ylab("votes")
#> Warning: Ignoring unknown aesthetics: weight
```

![](http://i.imgur.com/m0XePWS.png)

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.1 (2017-06-30)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2017-08-28
#> Packages -----------------------------------------------------------------
#>  package       * version  date       source        
#>  backports       1.1.0    2017-05-22 CRAN (R 3.4.0)
#>  base          * 3.4.1    2017-06-30 local         
#>  bitops          1.0-6    2013-08-17 CRAN (R 3.4.0)
#>  colorspace      1.3-2    2016-12-14 CRAN (R 3.4.1)
#>  compiler        3.4.1    2017-06-30 local         
#>  datasets      * 3.4.1    2017-06-30 local         
#>  devtools        1.13.3   2017-08-02 CRAN (R 3.4.1)
#>  digest          0.6.12   2017-01-27 CRAN (R 3.4.1)
#>  evaluate        0.10.1   2017-06-24 CRAN (R 3.4.1)
#>  ggplot2       * 2.2.1    2016-12-30 CRAN (R 3.4.1)
#>  ggplot2movies * 0.0.1    2015-08-25 CRAN (R 3.4.1)
#>  graphics      * 3.4.1    2017-06-30 local         
#>  grDevices     * 3.4.1    2017-06-30 local         
#>  grid            3.4.1    2017-06-30 local         
#>  gtable          0.2.0    2016-02-26 CRAN (R 3.4.1)
#>  htmltools       0.3.6    2017-04-28 CRAN (R 3.4.1)
#>  knitr           1.17     2017-08-10 CRAN (R 3.4.1)
#>  labeling        0.3      2014-08-23 CRAN (R 3.4.0)
#>  lazyeval        0.2.0    2016-06-12 CRAN (R 3.4.1)
#>  magrittr        1.5      2014-11-22 CRAN (R 3.4.1)
#>  memoise         1.1.0    2017-04-21 CRAN (R 3.4.1)
#>  methods       * 3.4.1    2017-06-30 local         
#>  munsell         0.4.3    2016-02-13 CRAN (R 3.4.1)
#>  plyr            1.8.4    2016-06-08 CRAN (R 3.4.1)
#>  Rcpp            0.12.12  2017-07-15 CRAN (R 3.4.1)
#>  RCurl           1.95-4.8 2016-03-01 CRAN (R 3.4.0)
#>  rlang           0.1.2    2017-08-09 CRAN (R 3.4.1)
#>  rmarkdown       1.6      2017-06-15 CRAN (R 3.4.1)
#>  rprojroot       1.2      2017-01-16 CRAN (R 3.4.1)
#>  scales          0.4.1    2016-11-09 CRAN (R 3.4.1)
#>  stats         * 3.4.1    2017-06-30 local         
#>  stringi         1.1.5    2017-04-07 CRAN (R 3.4.0)
#>  stringr         1.2.0    2017-02-18 CRAN (R 3.4.1)
#>  tibble          1.3.4    2017-08-22 CRAN (R 3.4.1)
#>  tools           3.4.1    2017-06-30 local         
#>  utils         * 3.4.1    2017-06-30 local         
#>  withr           2.0.0    2017-07-28 CRAN (R 3.4.1)
#>  XML             3.98-1.9 2017-06-19 CRAN (R 3.4.0)
#>  yaml            2.1.14   2016-11-12 CRAN (R 3.4.1)
```

</details>
