### ISSUE TITLE
`coord_cartesian()`  removes confidence intervals from the trend line

### ISSUE THREAD

**Issue by delferts** [tidyverse/ggplot2#4632] opened 2021-09-30 13:40 UTC
When `coord_cartesian()` is used to set the limits for the plot with the trend line (`geom_smooth()`), the confidence intervals band is not displayed anymore. 

The problem has been observed on two different computers with` Windows 10 x64`, `R 4.1.1`. and `ggplot2` version 3.3.5.

```r
ggplot(mtcars, aes(disp, wt)) +
     geom_point() +
     geom_smooth() +
    coord_cartesian(xlim = c(325, 500))
```
![smooth](https://user-images.githubusercontent.com/2959904/135465979-e7e3cad7-7705-4c51-ac6c-9f19806ff9c0.png)

**Comment by karawoo** [comment] 2021-09-30 15:59
I can't reproduce, maybe it's a graphics device issue?

``` r
library("ggplot2")

ggplot(mtcars, aes(disp, wt)) +
  geom_point() +
  geom_smooth() +
  coord_cartesian(xlim = c(325, 500))
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/pzryblM.png)

<sup>Created on 2021-09-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ptoche** [comment] 2021-09-30 22:52
cannot reproduce either, experimented with different values of `xlim`. 

Same version of `R` and `ggplot2`, but I'm on MacOS.

**Comment by clauswilke** [comment] 2021-09-30 23:48
We have received many similar reports. The problem is usually the broken Windows graphics device. Switching to ragg should fix this.

**Comment by yutannihilation** [comment] 2021-10-06 23:29
Closing in favor of #4498

**Closed by yutannihilation** 2021-10-06 23:29 UTC
