### ISSUE TITLE
`aes` doesn't support splicing

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/ggplot2#3176] opened 2019-03-06 10:28 UTC
This works  : 

```
ggplot(iris,aes(x = Sepal.Length, y = Sepal.Width)) + geom_point()
```

This doesn't : 

```
ggplot(iris, aes(!!!alist(x = Sepal.Length, y = Sepal.Width))) + geom_point()
# Error: Can't use `!!!` at top level
# Call `rlang::last_error()` to see a backtrace
```

**Comment by yutannihilation** [comment] 2019-03-06 10:40
Thanks, this is a duplicate of #2675.

**Closed by yutannihilation** 2019-03-06 10:40 UTC

**Comment by yutannihilation** [comment] 2019-03-06 10:43
As described in #2675, leaving `x` and `y` empty is a workaround:

``` r
library(ggplot2)

aes(,,!!!alist(x = Sepal.Length, y = Sepal.Width))
#> Aesthetic mapping: 
#> * `x` -> `Sepal.Length`
#> * `y` -> `Sepal.Width`
```

<sup>Created on 2019-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
