### ISSUE TITLE
gap between fill and border in legend key

### ISSUE THREAD

**Issue by steveharoz** [tidyverse/ggplot2#2844] opened 2018-08-21 18:30 UTC
There is a small white line (gap?) on the right and bottom of each legend key item. It's between the colored fill and the black outline. It happens when displayed in R studio or when using `ggsave()`

```r
ggplot(mtcars) +
  aes(fill=factor(cyl), x=cyl) +
  geom_bar() +
  theme(legend.key = element_rect(color="black"))
```
Here's a zoomed in image:
![image](https://user-images.githubusercontent.com/2257540/44421287-642f0480-a580-11e8-88ef-a29225da5736.png)

If the border color is specified in `geom_bar`, there is no gap.

```r
ggplot(mtcars) +
  aes(fill=factor(cyl), x=cyl) +
  geom_bar(color="black")
```
![image](https://user-images.githubusercontent.com/2257540/44425662-cd1c7980-a58c-11e8-8bc0-e50cb73e58db.png)

ggplot version: tried with both CRAN and latest github version
R version: 3.5.1  
OS: windows 10

**Comment by ptoche** [comment] 2018-08-21 18:57
on your screenshot it looks like the bars are not centered on their value, but slightly shifted to the left, by about the same amount as the same line you see in the legend?

**Comment by steveharoz** [comment] 2018-08-21 19:57
I added another example showing that when the border specified in the geom, there is no gap.

**Comment by steveharoz** [comment] 2018-08-21 20:48
Thanks @clauswilke! If I understand your explanation correctly, that little spacer is what separates the keys when you specify the border color in the geom, like in my second image.

![image](https://user-images.githubusercontent.com/2257540/44428135-c0e7ea80-a593-11e8-9495-5a0030b512d6.png)

I'd definitely appreciate if key spacing were easier to control. Because my current graphs have the legend on top, I've been able to work around the issue by adjusting the legend text margin.

**Comment by steveharoz** [comment] 2018-08-21 20:58
Oh wait, now there's a new problem. Part of the border rectangle isn't drawn:

```r
ggplot(mtcars) +
  aes(fill=factor(cyl), x=cyl) +
  geom_bar() +
  theme(legend.key = element_rect(color="black"))
```

![image](https://user-images.githubusercontent.com/2257540/44428665-68195180-a595-11e8-9061-9348ecab5210.png)

**Comment by clauswilke** [comment] 2018-08-21 22:29
I can't reproduce that. Could you try something like `theme(legend.key = element_rect(color="black", size = 3))` to see if the rectangle comes back? Also, if you're on windows using the windows graphics device, it is known to introduce drawing artifacts. Try to generate a pdf and see if the rectangle is present there.

**Comment by clauswilke** [comment] 2018-08-22 04:27
Actually, thinking some more about this, you're likely going to get drawing artifacts when you're combining an `element_rect()` in the theme with a legend key that is a filled square, because the two items are drawn separately and on top of each other. If you need a black outline around the filled areas but not around the bars, using the `override.aes` method may be better:
``` r
library(ggplot2)
ggplot(mtcars) +
  aes(fill = factor(cyl), x = cyl) +
  geom_bar() +
  guides(fill = guide_legend(
      override.aes = list(color = "black")
    )
  )
```

![](https://i.imgur.com/Qww9KnB.png)

Created on 2018-08-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by steveharoz** [comment] 2018-08-22 05:03
Fantastic! `override.aes` completely solves all the weird rendering issues I've been having. Thank you!

**Comment by hadley** [comment] 2019-06-18 14:42
Closing because this issue seems to have been resolved (at least for the case at hand, and solving in general looks like a lot of work)

**Closed by hadley** 2019-06-18 14:42 UTC
Labels: feature, guides :straight_ruler:
