### ISSUE TITLE
Error in scale_apply() when facetting by two identical variables

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#2098] opened 2017-04-06 22:46 UTC
Apparently this used to work (initially reported in https://github.com/ropensci/plotly/issues/643)

```r
data("mtcars")
require(ggplot2)

ggplot(data= mtcars, aes(x = gear, y = carb, colour = factor(cyl))) +
  geom_point(size = 2) +
  facet_grid(cyl~cyl, drop= FALSE) +
  theme_set(theme_gray(base_size = 12)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust= 0)) +
  labs(title = 'Cars', x = 'gear', y= 'carb') 
```

**Comment by hadley** [comment] 2017-06-01 12:52
Duplicate of #1928

**Closed by hadley** 2017-06-01 12:52 UTC
