### ISSUE TITLE
Mangled stacked geom_bar() with particular set of data using Date class on x axis

### ISSUE THREAD

**Issue by stragu** [tidyverse/ggplot2#4205] opened 2020-09-20 03:10 UTC
With a particular dataset, plotting a stacked barplot with the date as character on the x axis works fine. But converting to a `Date` class creates an issue with a bar showing erroneous data, layered beside the other bars, and spreading outside of the date range. It also prints the warning message:

> Warning: position_stack requires non-overlapping x intervals

I can't make sense of it...

Here is a reprex:

``` r
# example data
df <- structure(
  list(
    date = c("2020-09-06", "2020-09-06", "2020-09-06", "2020-09-07",
             "2020-09-07", "2020-09-07", "2020-09-07", "2020-09-07",
             "2020-09-17", "2020-09-18", "2020-09-18", "2020-09-18",
             "2020-09-18", "2020-09-19", "2020-09-19", "2020-09-19"),
    language = c("en", "fr", "fr", "en", "en", "en", "de", "es",
                 "fr", "en", "en", "fr", "en", "en", "de", "en")),
  class = "data.frame", row.names = c(NA, -16L))
# date variable is character
class(df$date)
#> [1] "character"

# plot it
library(ggplot2)
ggplot(df, aes(x = date, fill = language)) +
  geom_bar()
```

![](https://i.imgur.com/8cuGMk7.png)

``` r

# convert to date (same as importing with readr::read_csv())
df$date <- as.Date(df$date)
class(df$date) # Date
#> [1] "Date"
# plot it
ggplot(df, aes(x = date, fill = language)) +
  geom_bar()
#> Warning: position_stack requires non-overlapping x intervals
```

![](https://i.imgur.com/2DSe8d8.png)

``` r
# "de" not stacked, and spread further than actual dates:
range(df$date)
#> [1] "2020-09-06" "2020-09-19"
```

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Versions:

* ggplot2 3.3.2
* R 4.0.2
* RStudio 1.3.1073 on Ubuntu 18.04

**Comment by karawoo** [comment] 2020-09-20 20:58
This may be a duplicate of #2047 but it's hard to tell without a reprex. Can you `dput()` a small subset of your data that can be used to reproduce the problem?

**Comment by stragu** [comment] 2020-09-21 00:13
Thanks @karawoo for the help! I updated the original report with a smaller dataset that would still reproduce, and integrated it to the code thanks to `dput()`.

**Comment by stragu** [comment] 2020-09-21 00:36
And looks like you are right about the duplicate. If I fix the bar width, I get the correct plot, like @hadley showed in [his minimal reprex](https://github.com/tidyverse/ggplot2/issues/2047#issuecomment-387900464):

```r
ggplot(df, aes(x = date, fill = language)) +
  geom_bar(width = 0.9)
```
![image](https://user-images.githubusercontent.com/1747497/93725902-32bd1300-fbf6-11ea-8c6d-653c4626d3b1.png)

**Comment by karawoo** [comment] 2020-09-25 00:17
Thanks @stragu, I'm going to close this issue since it's a duplicate of one that's already open. You can subscribe to notifications on that one if you want to be informed of any updates.

**Closed by karawoo** 2020-09-25 00:17 UTC
